
package com.augurit.xm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWorkFlowWebService", targetNamespace = "http://service.xm.augurit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWorkFlowWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompletedTasks", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetCompletedTasks")
    @ResponseWrapper(localName = "getCompletedTasksResponse", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetCompletedTasksResponse")
    public String getCompletedTasks(
        @WebParam(name = "arg0", targetNamespace = "http://service.xm.augurit.com/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendTask", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.SendTask")
    @ResponseWrapper(localName = "sendTaskResponse", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.SendTaskResponse")
    public String sendTask(
        @WebParam(name = "arg0", targetNamespace = "http://service.xm.augurit.com/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startProc", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.StartProc")
    @ResponseWrapper(localName = "startProcResponse", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.StartProcResponse")
    public String startProc(
        @WebParam(name = "arg0", targetNamespace = "http://service.xm.augurit.com/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDZbTasks", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetDZbTasks")
    @ResponseWrapper(localName = "getDZbTasksResponse", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetDZbTasksResponse")
    public String getDZbTasks(
        @WebParam(name = "arg0", targetNamespace = "http://service.xm.augurit.com/")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommonTask", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetCommonTask")
    @ResponseWrapper(localName = "getCommonTaskResponse", targetNamespace = "http://service.xm.augurit.com/", className = "com.augurit.xm.service.GetCommonTaskResponse")
    public String getCommonTask(
        @WebParam(name = "arg0", targetNamespace = "http://service.xm.augurit.com/")
        String arg0);

}
