
package com.augurit.xm.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WorkFlowWebServiceImplService", targetNamespace = "http://service.xm.augurit.com/", wsdlLocation = "http://10.26.6.122:8086/agsupport/ws/workFlowWebService?wsdl")
public class WorkFlowWebServiceImplService
    extends Service
{

    private final static URL WORKFLOWWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.augurit.xm.service.WorkFlowWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.augurit.xm.service.WorkFlowWebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://10.26.6.122:8086/agsupport/ws/workFlowWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.26.6.122:8086/agsupport/ws/workFlowWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WORKFLOWWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WorkFlowWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkFlowWebServiceImplService() {
        super(WORKFLOWWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.xm.augurit.com/", "WorkFlowWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns IWorkFlowWebService
     */
    @WebEndpoint(name = "WorkFlowWebServiceImplPort")
    public IWorkFlowWebService getWorkFlowWebServiceImplPort() {
        return super.getPort(new QName("http://service.xm.augurit.com/", "WorkFlowWebServiceImplPort"), IWorkFlowWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWorkFlowWebService
     */
    @WebEndpoint(name = "WorkFlowWebServiceImplPort")
    public IWorkFlowWebService getWorkFlowWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.xm.augurit.com/", "WorkFlowWebServiceImplPort"), IWorkFlowWebService.class, features);
    }

}
