function attachEvent(){for(var b=0;b<document.all.length;b++)if("TD"==document.all[b].tagName&&"ToolBar"==document.all[b].className)gaTools[gaTools.length]=document.all[b],document.all[b].onmouseover=ToolMouseOver,document.all[b].onmouseout=ToolMouseOut,document.all[b].onmousedown=ToolMouseDown,document.all[b].onmouseup=ToolMouseUp;else if("TD"==document.all[b].tagName&&("Menu"==document.all[b].className||"Menu_Big"==document.all[b].className))document.all[b].onmouseover=MenuMouseOver,document.all[b].onmouseout=
MenuMouseOut,document.all[b].onmousedown=MenuMouseDown,document.all[b].onmouseup=MenuMouseUp}function ToolMouseOver(){"ToolBar"==this.className&&(this.className="ToolOutset")}function ToolMouseOut(){"ToolInset"!=this.className&&(this.className="ToolBar")}function ToolMouseDown(){this.className="ToolInset";null!=goSelectedTool&&(goSelectedTool.className="ToolBar");goSelectedTool=this;showToolMsg()}function ToolMouseUp(){}var goSelectedTool=null,gaTools=[];
function MenuMouseOver(){this.className="MenuOutset"+(-1!=this.className.indexOf("_Big")?"_Big":"")}function MenuMouseOut(){this.className="Menu"+(-1!=this.className.indexOf("_Big")?"_Big":"")}function MenuMouseDown(){this.className="MenuInset"+(-1!=this.className.indexOf("_Big")?"_Big":"")}function MenuMouseUp(){this.className="Menu"+(-1!=this.className.indexOf("_Big")?"_Big":"")}
function HideDoing_(){"object"==typeof ID_PromptDoing&&(ID_PromptDoing.style.display="none",ID_PromptDoing.innerHTML="")}var goWorkFlow=null,saveSetting=!0;function saveCurrentSetting(){saveSetting?$("#btn_save").trigger("click"):saveSetting=!0}function setFlowProperty(b){goWorkFlow=b;var d=goWorkFlow.flowXML.selectSingleNode("property");saveCurrentSetting();$.get(ctx+"/workflow/flow2.htm",function(a){$("#eProperty").html(a);FlowLoadEvent(d);FlowInitEvent(d)})}
function setTaskProperty(b,d,a){goWorkFlow=a;saveCurrentSetting();"SUBFLOW"==b.Type?$.get(ctx+"/workflow/sub/flow2.htm",function(a){$("#eProperty").html(a);SubFlowLoadEvent(b,b.xmlObject);SubFlowLoadInitEvent(b,b.xmlObject)}):"CONDITION"==b.Type?$.get(ctx+"/workflow/condition2.htm",function(a){$("#eProperty").html(a);ConditionLoadEvent(b,b.xmlObject)}):$.get(ctx+"/workflow/task2.htm",function(a){$("#eProperty").html(a);TaskLoadEvent(b,b.xmlObject);TaskInitEvent(b,b.xmlObject)})}
function FlowLoadEvent(b){var d=$("#flowForm")[0];goWorkFlow.equalFlowID=null;var a=goWorkFlow.dictionXML.selectNodes("/diction/categorys/category");if(null!=a&&0<a.length){var c=null!=b.selectSingleNode("categorySN")?b.selectSingleNode("categorySN").text():null;a.each(function(){var a=$(this),b=a.selectSingleNode("code").text();bAddEntry($("#DCategory",d)[0],a.selectSingleNode("name").text(),b,b==c?!1:!0)})}a=goWorkFlow.dictionXML.selectNodes("/diction/forms/form");null!=a&&0<a.length&&(c=null!=
b.selectSingleNode("formID")?b.selectSingleNode("formID").text():null,a.each(function(){var a=$(this),b=a.selectSingleNode("id").text();bAddEntry($("#DForm",d)[0],a.selectSingleNode("name").text(),b,b==c?!1:!0)}));a=goWorkFlow.flowXML.selectNodes("./timers/timer");null!=a&&0<a.length&&a.each(function(){var a=$(this).selectSingleNode("name").text();bAddEntry($("#DTimer",d)[0],a,a,!0)});a=b.selectSingleNode("equalFlow");null!=a&&0<a.length&&(c=null!=a.selectSingleNode("name")?a.selectSingleNode("name").text():
null,null!=c&&""!=c&&$("#EQFlowName",d).val(c),c=null!=a.selectSingleNode("id")?a.selectSingleNode("id").text():null,null!=c&&""!=c&&$("#EQFlowID",d).val(c));for(var e=["beginDirections","endDirections"],f=0;f<e.length;f++)if(a=b.selectSingleNode(e[f]),null!=a&&0!=a.length&&(a=a.selectNodes("unit"),null!=a&&0!=a.length)){for(var g=[],j=[],k=aGetDirections(),h=0;h<a.length;h++)for(var l=$(a[h]).selectSingleNode("value").text(),n=$(a[h]).selectSingleNode("argValue").text(),p=0;p<k.length;p++){var r=
k[p].split("|");if(r[3]==l&&r[5]==n){g.push(r[0]+"("+r[2]+"-"+r[4]+")");j.push(l+"|"+n);break}}a=d["D"+e[f]];a.value=g.join("\n");a=d[e[f]];a.value=j.join(";")}a=b.selectSingleNode("bakUsers");if(null!=a&&0!=a.length&&(a=a.selectNodes("unit"),null!=a&&0!=a.length))for(h=0;h<a.length;h++)f=$(a[h]).selectSingleNode("value").text(),e=$(a[h]).selectNodes("argValue").text(),r=f.split("|"),e=e.split("|"),bAddEntry(d.DBackUser,r[0]+"->"+e[0],r[1]+"->"+e[1],!0);a=b.selectSingleNode("messageTemplates");if(null!=
a&&0!=a.length&&(a=a.selectNodes("template"),null!=a&&0!=a.length))for(h=0;h<a.length;h++)r=$(a[h]).selectSingleNode("type").text(),g=$(a[h]).selectSingleNode("typeName").text(),j=$(a[h]).selectSingleNode("id").text(),k=$(a[h]).selectSingleNode("name").text(),f=$(a[h]).selectSingleNode("condition").text(),e={},e.type=r,e.typeName=g,e.id=j,e.name=k,e.condition=f,r=g+" "+k,null!=f&&""!=$.trim(f)&&(r=r+"("+f+")"),f=$("<option>"+r+"</option>"),f.data("value",e),$(d.DMessageTemplate,d).append(f);d.name.value=
null==goWorkFlow.flowXML.getAttribute("name")?"":goWorkFlow.flowXML.getAttribute("name");d.id.value=null==goWorkFlow.flowXML.getAttribute("id")?"":goWorkFlow.flowXML.getAttribute("id");d.code.value=null==goWorkFlow.flowXML.getAttribute("code")?"":goWorkFlow.flowXML.getAttribute("code");e="creator user monitor admin fileRecipient msgRecipient".split(" ");for(h=0;h<e.length;h++)bGetUnitXMLToField(b,d,e[h]);e="isFree isActive dueTime timeUnit isSendFile isSendMsg fileTemplate printTemplate printTemplateId listenerName listener".split(" ");
for(h=0;h<e.length;h++)c=null!=b.selectSingleNode(e[h])?b.selectSingleNode(e[h]).text():null,null!=c&&""!=c&&bSetFormFieldValue(d,e[h],c);bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),window)}
function FlowInitEvent(b){var d=$("#flowForm")[0];$(".tabs",d).tabs();$("#btn_save",d).button().click(function(){FlowOKEvent(b)});$("#btn_abandon",d).button().click(function(){saveSetting=!1;setFlowProperty(goWorkFlow,window.eWorkFlow.contentWindow)});$("#EQFlowName").click(function(a){a.target.title="\u9009\u62e9\u7b49\u4ef7\u6d41\u7a0b";bFlowActions(10,a,d)});$("#Dcreators").click(function(a){a.target.title="\u9009\u62e9\u53d1\u8d77\u4eba";bFlowActions(1,a,d)});$("#Dusers").click(function(a){a.target.title=
"\u9009\u62e9\u53c2\u4e0e\u4eba";bFlowActions(2,a,d)});$("#Dmonitors").click(function(a){a.target.title="\u9009\u62e9\u7763\u529e\u4eba";bFlowActions(3,a,d)});$("#Dadmins").click(function(a){a.target.title="\u9009\u62e9\u76d1\u63a7\u8005";bFlowActions(4,a,d)});$("#timerAdd").click(function(a){bFlowActions(11,a,d)});$("#timerEdit").click(function(a){bFlowActions(12,a,d)});$("#DTimer").dblclick(function(a){bFlowActions(12,a,d)});$("#timerDelete").click(function(a){bFlowActions(13,a,d)});var a=goWorkFlow.flowXML.selectSingleNode("./property/formID"),
a=null!=a?a.text():"";JDS.call({service:"flowSchemeService.getFormFields",data:[-1,a],success:function(a){onGetFormFields("#dueTimeLabel",d,a.data);$("#dueTimeLabel").val($("#dueTime").val())}});$("#dueTimeLabel").change(function(){$("#dueTime").val($(this).val())});$("#id").removeAttr("disabled");$("#DbeginDirections").click(function(a){a.target.title="\u9009\u62e9\u5f00\u59cb\u6d41\u5411";bFlowActions(6,a,d)});$("#DendDirections").click(function(a){a.target.title="\u9009\u62e9\u7ed3\u675f\u6d41\u5411";
bFlowActions(7,a,d)});$("#printTemplate").comboTree({labelField:"printTemplate",valueField:"printTemplateId",treeSetting:{view:{showIcon:!1,showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getPrintTemplates"}}},autoInitValue:!1,width:530,height:260});$("#listenerName").comboTree({labelField:"listenerName",valueField:"listener",treeSetting:{view:{showIcon:!1,showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getFlowListeners"}}},autoInitValue:!1,
width:530,height:260});$("input[name=isSendFile]").change(function(){"sendFile"===this.id&&this.checked&&$("#ID_SendFile").show();"noSendFile"===this.id&&this.checked&&$("#ID_SendFile").hide()}).trigger("change");$("#DfileRecipients").click(function(a){a.target.title="\u9009\u62e9\u6587\u4ef6\u5206\u53d1\u5bf9\u8c61";bFlowActions(8,a,d)});$("input[name=isSendMsg]").change(function(){"sendMsg"===this.id&&this.checked&&$("#ID_SendMsg").show();"noSendMsg"===this.id&&this.checked&&$("#ID_SendMsg").hide()}).trigger("change");
$("#DmsgRecipients").click(function(a){a.target.title="\u9009\u62e9\u6d88\u606f\u5206\u53d1\u5bf9\u8c61";bFlowActions(9,a,d)});$("#backuserAdd").click(function(a){bFlowActions(14,a,d)});$("#backuserEdit").click(function(a){bFlowActions(15,a,d)});$("#backuserDelete").click(function(a){bFlowActions(16,a,d)});$("#messageTemplateAdd").click(function(a){bFlowActions(17,a,d)});$("#messageTemplateEdit").click(function(a){bFlowActions(18,a,d)});$("#messageTemplateDelete").click(function(a){bFlowActions(19,
a,d)})}
function FlowOKEvent(b){var d=$("#flowForm")[0];goWorkFlow.equalFlowID=null;oSetElement(b,"categorySN",sGetFormFieldValue(d,"DCategory"));oSetElement(b,"formID",sGetFormFieldValue(d,"DForm"));var a=oSetElement(b,"equalFlow");oSetElement(a,"name",d.EQFlowName.value);oSetElement(a,"id",d.EQFlowID.value);for(var c=["beginDirections","endDirections"],e=0;e<c.length;e++){a=b.selectSingleNode(c[e]);null!=a&&0!=a.length&&b.removeChild(a);var f=$("form #"+c[e]);if(""!=f.val())for(var a=oSetElement(b,c[e]),
g=f.val().split(";"),f=0;f<g.length;f++){var j=g[f].split("|"),k=oAddElement(a,"unit");k.setAttribute("type","16");oAddElement(k,"value",j[0]);oAddElement(k,"argValue",j[1])}}a=b.selectSingleNode("bakUsers");null!=a&&0!=a.length&&b.removeChild(a);a=oSetElement(b,"bakUsers");f=d.DBackUser;for(e=0;e<f.options.length;e++)g=f.options[e].value,c=f.options[e].text.split("->"),g=g.split("->"),k=oAddElement(a,"unit"),k.setAttribute("type","16"),oAddElement(k,"value",c[0]+"|"+g[0]),oAddElement(k,"argValue",
c[1]+"|"+g[1]);a=b.selectSingleNode("messageTemplates");null!=a&&0!=a.length&&b.removeChild(a);f=d.DMessageTemplate;a=oSetElement(b,"messageTemplates");for(e=0;e<f.options.length;e++)g=$(d.DMessageTemplate.options[e]).data("value"),k=oAddElement(a,"template"),oAddElement(k,"type",g.type),oAddElement(k,"typeName",g.typeName),oAddElement(k,"id",g.id),oAddElement(k,"name",g.name),oAddElement(k,"condition",g.condition);goWorkFlow.flowXML.setAttribute("name",d.name.value);goWorkFlow.flowXML.setAttribute("id",
d.id.value);goWorkFlow.flowXML.setAttribute("code",d.code.value);for(var c="creator user monitor admin fileRecipient msgRecipient".split(" "),e=0;e<c.length;e++)bSetUnitFieldToXML(b,d,c[e]);c="isFree isActive dueTime timeUnit isSendFile isSendMsg fileTemplate printTemplate printTemplateId listenerName listener".split(" ");for(e=0;e<c.length;e++)oSetElement(b,c[e],sGetFormFieldValue(d,c[e]))}
function TaskLoadEvent(b,d){var a=$("#taskForm")[0],c=goWorkFlow.dictionXML.selectNodes("/diction/forms/form");if(null!=c&&0!=c.length)for(var e=null!=d.selectSingleNode("formID")?d.selectSingleNode("formID").text():null,f=0;f<c.length;f++){var g=$(c[f]).selectSingleNode("id").text();bAddEntry(a.DForm,$(c[f]).selectSingleNode("name").text(),g,g==e?!1:!0)}e=aGetXMLFieldValue(d,"untreadTasks");if(null!=e){a.untreadTasks.value=e.join(";");for(f=0;f<e.length;f++)e[f]="<"+sGetTaskNameByID(e[f])+">";a.DuntreadTasks.value=
e.join(";")}c=["readFields","editFields","hideFields","notNullFields"];for(f=0;f<c.length;f++)e=aGetXMLFieldValue(d,c[f]),null!=e&&(a[c[f]].value=e.join(";"));e=aGetXMLFieldValue(d,"rights");aSetButtonRight(a.DTaskRight,"/diction/rights/right",e);e=aGetXMLFieldValue(d,"doneRights");aSetButtonRight(a.DTaskDoneRight,"/diction/doneRights/right",e);e=aGetXMLFieldValue(d,"monitorRights");aSetButtonRight(a.DTaskMonitorRight,"/diction/monitorRights/right",e);e=aGetXMLFieldValue(d,"adminRights");aSetButtonRight(a.DTaskAdminRight,
"/diction/adminRights/right",e);f=d.selectSingleNode("buttons");a.DButton.uuid="";if(null!=f&&0!=f.length&&(c=f.selectNodes("button"),null!=c&&0!=c.length)){g=[];for(f=0;f<c.length;f++){var j=null!=$(c[f]).getAttribute("uuid")?$(c[f]).getAttribute("uuid"):"",e=$(c[f]).selectSingleNode("btnValue").text(),k=$(c[f]).selectSingleNode("newName").text(),h=$(c[f]).selectSingleNode("newCode"),l=null==h?"":h.text(),n=$(c[f]).selectSingleNode("useWay").text(),p=$(c[f]).selectSingleNode("btnArgument").text(),
r=$(c[f]).selectSingleNode("btnOwners").text(),t=$(c[f]).selectSingleNode("btnOwnerIds").text(),m=$(c[f]).selectSingleNode("btnUsers").text(),u=$(c[f]).selectSingleNode("btnUserIds").text(),v=$(c[f]).selectSingleNode("btnCopyUsers").text(),q=$(c[f]).selectSingleNode("btnCopyUserIds").text(),s=goWorkFlow.dictionXML.selectSingleNode("/diction/buttons/button[value='"+e+"']"),h="";null!=s&&(h=s.selectSingleNode("name").text());s={};s.btnValue=e;s.newName=k;s.newCode=l;s.useWay=n;s.btnArgument=p;s.btnOwners=
r;s.btnOwnerIds=t;s.btnUsers=m;s.btnUserIds=u;s.btnCopyUsers=v;s.btnCopyUserIds=q;e=$("<option>"+h+"->"+k+(""!=p?"("+sGetTaskNameByID(p)+")":"")+"</option>");e.data("value",s);$(a.DButton,a).append(e);""!=j&&g.push(j)}a.DButton.uuid=g.join(";")}f=d.selectSingleNode("optNames");if(null!=f&&0!=f.length&&(c=f.selectNodes("unit"),null!=c&&0!=c.length))for(f=0;f<c.length;f++)e=$(c[f]).selectSingleNode("value").text(),g=$(c[f]).selectSingleNode("argValue").text(),bAddEntry(a.DOption,g+"|"+e,g+"|"+e,!0);
f=d.selectSingleNode("records");a.DRemark.uuid="";if(null!=f&&0!=f.length&&(c=f.selectNodes("record"),null!=c&&0!=c.length)){g=[];for(f=0;f<c.length;f++)j=null!=$(c[f]).getAttribute("uuid")?$(c[f]).getAttribute("uuid"):"",h=$(c[f]).selectSingleNode("name").text(),k=$(c[f]).selectSingleNode("field").text(),e=$(c[f]).selectSingleNode("way"),n=null==e?"":e.text(),e=$(c[f]).selectSingleNode("value").text(),""!=j&&g.push(j),l={},l.uuid=j,l.name=h,l.field=k,l.way=n,l.value=e,e=$("<option>"+h+"</option>"),
e.data("value",l),$(a.DRemark,a).append(e);a.DRemark.uuid=g.join(";")}a.name.value=null==d.getAttribute("name")?"":d.getAttribute("name");a.id.value=null==d.getAttribute("id")?"":d.getAttribute("id");a.sn.value=null==d.getAttribute("code")?"":d.getAttribute("code");c=["user","copyUser","monitor"];for(f=0;f<c.length;f++)bGetUnitXMLToField(d,a,c[f]);c="isSetUser isSetCopyUser isSetUserEmpty emptyToTask emptyNoteDone isSelectAgain isOnlyOne isAnyone isByOrder sameUserSubmit isSetMonitor isInheritMonitor untreadType snName serialNo printTemplate printTemplateId listenerName listener".split(" ");
for(f=0;f<c.length;f++)e=null!=d.selectSingleNode(c[f])?d.selectSingleNode(c[f]).text():null,null!=e&&""!=e&&bSetFormFieldValue(a,c[f],e);""!=a.emptyToTask.value&&(a.DemptyToTask.value="<"+sGetTaskNameByID(a.emptyToTask.value)+">");bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),window)}
function TaskInitEvent(b,d){var a=$("#taskForm")[0];$(".tabs",a).tabs();$("#btn_save",a).button().click(function(){TaskOKEvent(b,d);null!=b.xmlObject&&bSetObjectText(b)});$("#btn_abandon",a).button().click(function(){saveSetting=!1;setTaskProperty(b,window.eWorkFlow.contentWindow,goWorkFlow)});$("#isSetUser",a).change(function(){"1"===$(this).val()?$("#ID_SetUser_0").show():$("#ID_SetUser_0").hide()}).trigger("change");$("#task_Dusers",a).click(function(b){b.target.title="\u9009\u62e9\u627f\u529e\u4eba";
bTaskActions(0,"",b,a)});$("#isSetCopyUser").change(function(){"1"===$(this).val()?$("#ID_SetUser_1").show():$("#ID_SetUser_1").hide()}).trigger("change");$("#task_DcopyUsers").click(function(b){b.target.title="\u9009\u62e9\u6284\u9001\u4eba";bTaskActions(1,"",b,a)});$("#isSetUserEmpty").change(function(){this.checked?($("#ID_SetUserEmpty1").show(),$("#ID_SetUserEmpty2").show()):($("#ID_SetUserEmpty1").hide(),$("#ID_SetUserEmpty2").hide())}).trigger("change");$("#DemptyToTask").click(function(b){bTaskActions(2,
"",b,a)});$("#isSelectAgain").change(function(){this.checked?$("#ID_OnlyOne").show():$("#ID_OnlyOne").hide()}).trigger("change");$("#isAnyone").click(function(){this.checked&&$("#isByOrder").removeAttr("checked")});$("#isByOrder").click(function(){this.checked&&$("#isAnyone").removeAttr("checked")});$("#isSetMonitor").change(function(){"0"!=$(this).val()?$("#ID_InheritMonitors").show():$("#ID_InheritMonitors").hide();"1"==$(this).val()?$("#ID_SetMonitor").show():$("#ID_SetMonitor").hide()}).trigger("change");
$("#task_Dmonitors").click(function(b){bTaskActions(3,"",b,a)});$("#todoRightAdd").click(function(b){bTaskActions(11,"",b,a)});$("#todoRightDelete").click(function(b){bTaskActions(12,"",b,a)});$("#todoRightClear").click(function(b){bTaskActions(13,"",b,a)});$("#doneRightAdd").click(function(b){bTaskActions(111,"",b,a)});$("#doneRightDelete").click(function(b){bTaskActions(112,"",b,a)});$("#doneRightClear").click(function(b){bTaskActions(113,"",b,a)});$("#monitorRightAdd").click(function(b){bTaskActions(211,
"",b,a)});$("#monitorRightDelete").click(function(b){bTaskActions(212,"",b,a)});$("#monitorRightClear").click(function(b){bTaskActions(213,"",b,a)});$("#adminRightAdd").click(function(b){bTaskActions(311,"",b,a)});$("#adminRightDelete").click(function(b){bTaskActions(312,"",b,a)});$("#adminRightClear").click(function(b){bTaskActions(313,"",b,a)});$("#buttonAdd").click(function(b){bTaskActions(14,"",b,a)});$("#buttonEdit").click(function(b){bTaskActions(15,"",b,a)});$("#buttonDelete").click(function(b){bTaskActions(16,
"",b,a)});$("#optionAdd").click(function(b){bTaskActions(17,"",b,a)});$("#optionDelete").click(function(b){bTaskActions(18,"",b,a)});$("#optionDefault").click(function(b){bTaskActions(19,"\u540c\u610f|1;\u4e0d\u540c\u610f|0;\u5df2\u9605|2",b,a)});var c={async:{otherParam:{serviceName:"flowSchemeService",methodName:"getFormFields",data:$("#DForm").val()}}};$("#editFieldLabels",a).comboTree({labelField:"editFieldLabels",valueField:"editFields",initService:"flowSchemeService.getFormFieldByFieldNames",
initServiceParam:[$("#DForm",a).val()],treeSetting:c,width:540,height:230});$("#readFieldLabels",a).comboTree({labelField:"readFieldLabels",valueField:"readFields",initService:"flowSchemeService.getFormFieldByFieldNames",initServiceParam:[$("#DForm",a).val()],treeSetting:c,width:540,height:230});$("#hideFieldLabels",a).comboTree({labelField:"hideFieldLabels",valueField:"hideFields",initService:"flowSchemeService.getFormFieldByFieldNames",initServiceParam:[$("#DForm",a).val()],treeSetting:c,width:540,
height:230});$("#notNullFieldLabels",a).comboTree({labelField:"notNullFieldLabels",valueField:"notNullFields",initService:"flowSchemeService.getFormFieldByFieldNames",initServiceParam:[$("#DForm",a).val()],treeSetting:c,width:540,height:230});0==$("#DForm",a).val()&&($("#editFieldLabels").comboTree("disable"),$("#readFieldLabels").comboTree("disable"),$("#hideFieldLabels").comboTree("disable"),$("#notNullFieldLabels").comboTree("disable"));$("#DForm",a).change(function(){var b=$(this).val();$("#editFieldLabels",
a).comboTree("clear");$("#readFieldLabels",a).comboTree("clear");$("#hideFieldLabels",a).comboTree("clear");$("#notNullFieldLabels",a).comboTree("clear");$("#editFieldLabels",a).comboTree("disable");$("#readFieldLabels",a).comboTree("disable");$("#hideFieldLabels",a).comboTree("disable");$("#notNullFieldLabels",a).comboTree("disable");0!=b&&(b={async:{otherParam:{data:b}}},$("#editFieldLabels",a).comboTree("enable"),$("#readFieldLabels",a).comboTree("enable"),$("#hideFieldLabels",a).comboTree("enable"),
$("#notNullFieldLabels",a).comboTree("enable"),$("#editFieldLabels",a).comboTree("setParams",{treeSetting:b}),$("#readFieldLabels",a).comboTree("setParams",{treeSetting:b}),$("#hideFieldLabels",a).comboTree("setParams",{treeSetting:b}),$("#notNullFieldLabels",a).comboTree("setParams",{treeSetting:b}))});$("#remarkAdd").click(function(b){bTaskActions(21,"",b,a)});$("#remarkEdit").click(function(b){bTaskActions(22,"",b,a)});$("#remarkDelete").click(function(b){bTaskActions(23,"",b,a)});c={view:{showIcon:!1,
showLine:!1},check:{enable:!0,chkStyle:"radio",radioType:"level"},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getSerialNumbers"}},callback:{onClick:function(a,b,c){null!=c&&(a=!c.checked,$.fn.zTree.getZTreeObj(b).checkNode(c,a),a?($("#snName").val(c.name),$("#serialNo").val(c.data)):($("#snName").val(""),$("#serialNo").val("")))}}};$("#snName").comboTree({labelField:"snName",valueField:"serialNo",treeSetting:c,autoInitValue:!1,width:540,height:230});$("#task_printTemplate").comboTree({labelField:"task_printTemplate",
valueField:"task_printTemplateId",treeSetting:{view:{showIcon:!1,showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getPrintTemplates"}}},autoInitValue:!1,width:540,height:230});$("#listenerName").comboTree({labelField:"listenerName",valueField:"listener",treeSetting:{view:{showIcon:!1,showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getTaskListeners"}}},autoInitValue:!1,width:540,height:230})}
function bTaskActions(b,d,a,c){switch(b){case 0:SelectUsers("","user",a.target.title,null,c);break;case 1:SelectUsers("","copyUser",a.target.title,null,c);break;case 2:SelectUsers("alltask","emptyToTask",a.target.title,!0,c);break;case 3:SelectUsers("","monitor",a.target.title,null,c);break;case 4:SelectUsers("task","untreadTasks",a.target.title);break;case 6:bSetField("editFields",!0,!0);break;case 7:bSetField("readFields",!0,!0);break;case 8:bSetField("hideFields",!0,!0);break;case 9:bSetField("notNullFields",
!0,!0);break;case 11:sGetButtonRight(c.DTaskRight,"/diction/rights/right");break;case 12:bMoveEntry(c.DTaskRight);break;case 13:for(b=c.DTaskRight.options.length-1;0<=b;b--)c.DTaskRight.options[b]=null;break;case 111:sGetButtonRight(c.DTaskDoneRight,"/diction/doneRights/right");break;case 112:bMoveEntry(c.DTaskDoneRight);break;case 113:for(b=c.DTaskDoneRight.options.length-1;0<=b;b--)c.DTaskDoneRight.options[b]=null;break;case 211:sGetButtonRight(c.DTaskMonitorRight,"/diction/monitorRights/right");
break;case 212:bMoveEntry(c.DTaskMonitorRight);break;case 213:for(b=c.DTaskMonitorRight.options.length-1;0<=b;b--)c.DTaskMonitorRight.options[b]=null;break;case 311:sGetButtonRight(c.DTaskAdminRight,"/diction/adminRights/right");break;case 312:bMoveEntry(c.DTaskAdminRight);break;case 313:for(b=c.DTaskAdminRight.options.length-1;0<=b;b--)c.DTaskAdminRight.options[b]=null;break;case 14:d=function(a){if(!(null==a||""==a)){var b=goWorkFlow.dictionXML.selectSingleNode("/diction/buttons/button[value='"+
a.btnValue+"']"),d="";null!=b&&(d=b.selectSingleNode("name").text());b=d+"->"+a.newName+(""!=a.btnArgument?"("+sGetTaskNameByID(a.btnArgument)+")":"");b=$("<option>"+b+"</option>");b.data("value",a);$("#DButton",c).append(b)}};sGetButton(null,d,c);break;case 15:var e=$("#DButton > option:selected",c);if(0==e.length)return!1;b=e.data("value")||{};d=function(a){if(!(null==a||""==a)){var b=goWorkFlow.dictionXML.selectSingleNode("/diction/buttons/button[value='"+a.btnValue+"']"),c="";null!=b&&(c=b.selectSingleNode("name").text());
b=c+"->"+a.newName+(""!=a.btnArgument?"("+sGetTaskNameByID(a.btnArgument)+")":"");e.text(b);e.data("value",a)}};sGetButton(b,d,c);break;case 16:bMoveEntry(c.DButton);break;case 17:d=function(a){null!=a&&""!=a&&bAddEntry(c.DOption,a,a)};b=[];b.Exist=";"+sGetAllEntryValue(c.DOption)+";";GetOption(c,b,d);break;case 18:bMoveEntry(c.DOption);break;case 19:for(b=c.DOption.options.length-1;0<=b;b--)c.DOption.options[b]=null;d=d.split(";");for(b=0;b<d.length;b++)bAddEntry(c.DOption,d[b],d[b],!0);break;case 21:d=
function(a){if(null!=a){var b=$("<option>"+a.name+"</option>");b.data("value",a);$(c.DRemark,c).append(b)}};sGetRemark({name:""},d);break;case 22:e=$("#DRemark > option:selected",c);if(0==e.length)return!1;b=e.data("value")||{};d=function(a){null!=a&&(e.text(a.name),e.data("value",a))};sGetRemark(b,d);break;case 23:bMoveEntry(c.DRemark)}}
function sGetRemark(b,d){var a=[];a.value=null==b?{}:b;$.get(ctx+"/workflow/remark2.htm",function(b){$("#dlg_remark").dialog({title:"\u4fe1\u606f\u8bb0\u5f55",autoOpen:!0,resizable:!1,width:400,height:230,modal:!0,close:function(){$("#dlg_remark").dialog("destroy");$("#dlg_remark").html("<div/>")},open:function(){$("#dlg_remark").html(b);bInitRemarkValue(a)},buttons:{"\u786e\u5b9a":function(){if(sRemarkCheck(a)){var b=sRemarkBuildValue(a);d(b);$(this).dialog("close")}},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function bInitRemarkValue(b){b=b.value;var d=$("#remarkForm")[0],a=goWorkFlow.dictionXML.selectNodes("/diction/formats/format");if(null!=a)for(var c=0;c<a.length;c++){var e=$(a[c]).selectSingleNode("value").text(),f=$(a[c]).selectSingleNode("name").text();bAddEntry(d.DFormat,f,e,!0)}null!=b&&""!=b&&(d.name.value=b.name,d.field.value=b.field,$(d.way,d).filter("[value="+b.way+"]").prop("checked",!0),bSetFormFieldValue(d,"DFormat",b.value));b=goWorkFlow.flowXML.selectSingleNode("./property/formID");
b=null!=b?b.text():"";d={async:{otherParam:{serviceName:"flowSchemeService",methodName:"getFormFields",data:b}}};$("#fieldLabel").comboTree({labelField:"fieldLabel",valueField:"field",initService:"flowSchemeService.getFormFieldByFieldNames",initServiceParam:[b],treeSetting:d,width:283,height:230});return!0}
function sRemarkCheck(){var b=$("#remarkForm")[0];return""==b.name.value?(alert(sGetLang("FLOW_WF_INFONAMEISEMPTY")),!1):""==b.field.value?(alert(sGetLang("FLOW_WF_INFOFIELDISEMPTY")),!1):""==b.DFormat.value?(alert(sGetLang("FLOW_WF_INFOFORMATISEMPTY")),!1):!0}function sRemarkBuildValue(b){b=b.value;var d=$("#remarkForm")[0],a={};a.uuid=b.uuid;a.name=d.name.value;a.field=d.field.value;a.way=$("input[name=way]:checked",d).val();a.value=d.DFormat.value;return a}
function GetOption(b,d,a){$.get(ctx+"/workflow/option2.htm",function(b){$("#dlg_option").dialog({title:"\u610f\u89c1\u7acb\u573a",autoOpen:!0,resizable:!1,width:400,height:200,modal:!0,close:function(){$("#dlg_option").dialog("destroy");$("#dlg_option").html("<div/>")},open:function(){$("#dlg_option").html(b)},buttons:{"\u786e\u5b9a":function(){var b=d.Exist,c=$("#optionForm")[0];""==c.Name.value?alert("\u8bf7\u8f93\u5165\u610f\u89c1\u7acb\u573a\u540d\u79f0\u3002"):""==c.Value.value?alert("\u8bf7\u8f93\u5165\u610f\u89c1\u7acb\u573a\u503c\u3002"):
-1!=b.indexOf(";"+c.Name.value+"|")?alert("\u540d\u79f0\u5df2\u7ecf\u5b58\u5728\u3002"):-1!=b.indexOf("|"+c.Value.value+";")?alert("\u503c\u5df2\u7ecf\u5b58\u5728\u3002"):(a(c.Name.value+"|"+c.Value.value),$(this).dialog("close"))},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function sGetButtonRight(b,d){var a=";"+sGetAllEntryValue(b)+";",c="",e=goWorkFlow.dictionXML.selectNodes(d);if(null!=e)for(var f=0;f<e.length;f++){var g=$(e[f]).selectSingleNode("value").text();if(-1==a.indexOf(";"+g+";"))var j=$(e[f]).selectSingleNode("name").text(),c=""==c?j+"|"+g:c+(";"+j+"|"+g)}sSelectArray_("Multiple",b.title,"",c,null,null,null,function(a){if(null!=a&&(a=";"+a+";",null!=e))for(var c=0;c<e.length;c++){var d=$(e[c]).selectSingleNode("value").text();if(-1!=a.indexOf(";"+d+";")){var f=
$(e[c]).selectSingleNode("name").text();bAddEntry(b,f,d,!0)}}})}
function sGetButton(b,d,a){var c=sGetAllEntryValue(a.DButton),e=[],f=goWorkFlow.dictionXML.selectNodes("/diction/buttons/button");if(null!=f){for(var c=c.split(";"),g=0;g<c.length;g++)c[g]=c[g].split("|")[1];c=";"+c.join(";")+";";for(g=0;g<f.length;g++){var j=$(f[g]).selectSingleNode("value").text();c.indexOf(";"+j+";");var k=$(f[g]).selectSingleNode("name").text();e.push(k+"|"+j)}}a=aGetTasks("TASK/SUBFLOW",a.id.value,!0);var h=[];h.Value=null!=b?b:{};h.Button=e;h.Task=a;$.get(ctx+"/workflow/button2.htm",
function(a){$("#dlg_button_define").dialog({title:"\u64cd\u4f5c\u5b9a\u4e49",autoOpen:!0,resizable:!1,width:450,height:395,modal:!0,close:function(){$("#dlg_button_define").dialog("destroy");$("#dlg_button_define").html("<div/>")},open:function(){$("#dlg_button_define").html(a);ButtonLoadEvent(h)},buttons:{"\u786e\u5b9a":function(){if(ButtonOKCheck(h)){var a=ButtonOKEvent(h);d(a);$(this).dialog("close")}},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function ButtonLoadEvent(b){var d=b.Value,a=b.Button;b=b.Task;for(var c=$("#buttonForm")[0],e=0;e<a.length;e++){var f=a[e].split("|");bAddEntry(c.DButton,f[0],f[1],!0)}for(e=0;e<b.length;e++)f=b[e].split("|"),bAddEntry(c.DTask,f[0],f[1],!0);if(""!=d){f=d;bSetFormFieldValue(c,"DButton",f.btnValue);c.newName.value=null==f.newName?"":f.newName;c.newCode.value=null==f.newCode?"":f.newCode;$(c.useWay).filter("[value="+f.useWay+"]").prop("checked",!0);bSetFormFieldValue(c,"DTask",f.btnArgument);c.DUnits.value=
null==f.btnOwners?"":f.btnOwners;c.Units.value=null==f.btnOwnerIds?"":f.btnOwnerIds;null!=f.btnUserIds&&(c.Dusers.value=null==f.btnUsers?"":f.btnUsers,d=f.btnUserIds.split(","),5==d.length&&(c.Duser1.value=d[0],c.user1.value=d[1],c.user2.value=d[2],c.user4.value=d[3],c.user8.value=d[4]));null!=f.btnCopyUserIds&&(c.DcopyUsers.value=null==f.btnCopyUsers?"":f.btnCopyUsers,d=f.btnCopyUserIds.split(","),5==d.length&&(c.DcopyUser1.value=d[0],c.copyUser1.value=d[1],c.copyUser2.value=d[2],c.copyUser4.value=
d[3],c.copyUser8.value=d[4]));var g={view:{showIcon:!1},check:{chkStyle:"radio"},async:{enable:!0,contentType:"application/json",url:ctx+"/json/data/services",otherParam:{serviceName:"resourceService",methodName:"getResourceButtonTree",data:"-1"},type:"POST"}};$(c.newName,c).click(function(){$("#dlg_select_button").popupTreeWindow({title:"\u6743\u9650\u6309\u94ae\u9009\u62e9",initValues:f.newCode,treeSetting:g,afterSelect:function(a){$(c.newName,c).val(a.name);$(c.newCode,c).val(a.value)},afterCancel:function(){$("#dlg_select_button").html("")},
close:function(){$("#dlg_select_button").html("")}});$("#dlg_select_button").popupTreeWindow("open")})}$("#button_DUnits").click(function(){$.unit.open({initNames:c.DUnits.value,initIDs:c.Units.value,title:"\u4eba\u5458\u9009\u62e9",multiple:!0,selectType:6,nameType:"21",showType:!0,type:"MyUnit",loginStatus:!1,excludeValues:null,afterSelect:function(a){null!=a&&(c.DUnits.value=a.name,c.Units.value=a.id)}})});$("#button_Dusers").click(function(a){a.target.title="\u9009\u62e9\u53c2\u4e0e\u4eba";SelectUsers("",
"user",a.target.title,null,c)});$("#button_DcopyUsers").click(function(a){a.target.title="\u9009\u62e9\u6284\u9001\u4eba";SelectUsers("","copyUser",a.target.title,null,c)})}function ButtonOKCheck(){var b=$("#buttonForm")[0],d=[];d[0]=sGetAllEntryValue(b.DButton,!0);return""==d[0]?(alert("\u8bf7\u9009\u62e9\u6309\u94ae!"),!1):""==b.newName.value?(alert("\u8bf7\u8f93\u5165\u65b0\u7684\u540d\u79f0!"),!1):""==b.DTask.value?(alert("\u8bf7\u9009\u62e9\u76ee\u6807\u73af\u8282!"),!1):!0}
function ButtonOKEvent(b){var d=b.Value;b=$("#buttonForm")[0];var a=[];a[0]=sGetAllEntryValue(b.DButton,!0);if(""==a[0])alert(b.DButton.emptyMsg);else if(""==b.newName.value)alert(b.newName.emptyMsg);else return a={unid:""},""!=d&&(a.unid=d.uunid),a.btnValue=sGetAllEntryValue(b.DButton,!0),a.newName=b.newName.value,a.newCode=b.newCode.value,a.useWay=$("input[name=useWay]:checked").val(),d=sGetAllEntryValue(b.DTask,!0),a.btnArgument="0"==d?"":d,a.btnOwners=b.DUnits.value,a.btnOwnerIds=b.Units.value,
a.btnUsers=b.Dusers.value,d=$("input[name='Duser1']",b).val()+","+$("input[name='user1']",b).val()+","+$("input[name='user2']",b).val()+","+$("input[name='user4']",b).val()+","+$("input[name='user8']",b).val(),a.btnUserIds=d,a.btnCopyUsers=b.DcopyUsers.value,laTempbtnCopyUserIds=$("input[name='DcopyUser1']",b).val()+","+$("input[name='copyUser1']",b).val()+","+$("input[name='copyUser2']",b).val()+","+$("input[name='copyUser4']",b).val()+","+$("input[name='copyUser8']",b).val(),a}
function sSelectArray_(b,d,a,c,e,f,g,j){var k={};k.Title=d;k.PromptInfo=a;k.ArgPara=c;k.Limit=null==e||e?"1":"0";k.Empty=!0==f?"1":"0";k.SetDefault=!0!=g?"1":"0";"single"==b.toLowerCase()&&(b="Radio");"multiple"==b.toLowerCase()&&(b="Checkbox");$.get(ctx+"/workflow/checkbox/select2.htm",function(a){$("#dlg_checkbox_select").dialog({title:d,autoOpen:!0,resizable:!1,width:400,height:270,modal:!0,close:function(){$("#dlg_checkbox_select").dialog("destroy");$("#dlg_checkbox_select").html("<div/>")},open:function(){$("#dlg_checkbox_select").html(a);
CheckboxSelectInitEvent(k)},buttons:{"\u786e\u5b9a":function(){var a=CheckboxSelectOKEvent(k);j(a);$(this).dialog("close")},"\u5168\u9009":function(){CheckboxSelectCheckAll(!0)},"\u5168\u4e0d\u9009":function(){CheckboxSelectCheckAll(!1)},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function CheckboxSelectInitEvent(b){b=b.ArgPara.split(";");$.each(b,function(b){if(0<this.indexOf("|")){var a=this.substr(0,this.indexOf("|")),c=this.substr(this.indexOf("|")+1);$("#select_checkbox").append('<div><input id="checkbox_'+b+'" type="checkbox" value="'+c+'" /><label for="checkbox_'+b+'">'+a+"</label></div>")}})}function CheckboxSelectCheckAll(b){$("#select_checkbox").find(":checkbox").each(function(){this.checked=b})}
function CheckboxSelectOKEvent(){var b="";$("#select_checkbox").find(":checkbox:checked").each(function(d){b=0==d?this.value:b+";"+this.value});return b}
function TaskOKEvent(b,d){var a=$("#taskForm")[0],c=sGetFormFieldValue(a,"DForm");oSetElement(d,"formID","0"==c?"":c);bSetXMLFieldValue(d,"untreadTasks",""!=a.untreadTasks.value?a.untreadTasks.value.split(";"):null);for(var e=["readFields","editFields","hideFields","notNullFields"],c=0;c<e.length;c++){var f=a[e[c]];bSetXMLFieldValue(d,e[c],""!=f.value?f.value.split(";"):null)}e=[];for(c=0;c<a.DTaskRight.options.length;c++)e.push(a.DTaskRight.options[c].value);bSetXMLFieldValue(d,"rights",e);e=[];
for(c=0;c<a.DTaskDoneRight.options.length;c++)e.push(a.DTaskDoneRight.options[c].value);bSetXMLFieldValue(d,"doneRights",e);e=[];for(c=0;c<a.DTaskMonitorRight.options.length;c++)e.push(a.DTaskMonitorRight.options[c].value);bSetXMLFieldValue(d,"monitorRights",e);e=[];for(c=0;c<a.DTaskAdminRight.options.length;c++)e.push(a.DTaskAdminRight.options[c].value);bSetXMLFieldValue(d,"adminRights",e);loNode=d.selectSingleNode("buttons");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"buttons");f=
a.DButton.uuid.split(";");for(c=0;c<a.DButton.options.length;c++){var e=$(a.DButton.options[c]).data("value"),g=oAddElement(loNode,"button");g.setAttribute("uunid",e.uunid);oAddElement(g,"btnValue",e.btnValue);oAddElement(g,"newName",e.newName);oAddElement(g,"newCode",e.newCode);oAddElement(g,"useWay",e.useWay);oAddElement(g,"btnArgument",e.btnArgument);oAddElement(g,"btnOwners",e.btnOwners);oAddElement(g,"btnOwnerIds",e.btnOwnerIds);oAddElement(g,"btnUsers",e.btnUsers);oAddElement(g,"btnUserIds",
e.btnUserIds);oAddElement(g,"btnCopyUsers",e.btnCopyUsers);oAddElement(g,"btnCopyUserIds",e.btnCopyUserIds);if(""!=e[0])for(g=0;g<f.length;g++)if(e[0]==f[g]){f[g]="";break}}loNode=goWorkFlow.flowXML.selectSingleNode("deletes");for(g=0;g<f.length;g++)""!=f[g]&&oAddElement(loNode,"button",f[g]);loNode=d.selectSingleNode("optNames");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"optNames");for(c=0;c<a.DOption.options.length;c++)e=a.DOption.options[c].value.split("|"),f=oAddElement(loNode,
"unit"),f.setAttribute("type","16"),oAddElement(f,"value",e[1]),oAddElement(f,"argValue",e[0]);loNode=d.selectSingleNode("records");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"records");f=a.DRemark.uuid.split(";");for(c=0;c<a.DRemark.options.length;c++)if(e=$(a.DRemark.options[c]).data("value"),g=oAddElement(loNode,"record"),g.setAttribute("uunid",e.uuid),oAddElement(g,"name",e.name),oAddElement(g,"field",e.field),oAddElement(g,"way",e.way),oAddElement(g,"value",e.value),""!=e[0])for(g=
0;g<f.length;g++)if(e[0]==f[g]){f[g]="";break}loNode=goWorkFlow.flowXML.selectSingleNode("deletes");for(g=0;g<f.length;g++)""!=f[g]&&oAddElement(loNode,"record",f[g]);d.setAttribute("name",a.name.value);d.setAttribute("id",a.id.value);d.setAttribute("code",a.sn.value);e=["user","copyUser","monitor"];for(c=0;c<e.length;c++)bSetUnitFieldToXML(d,a,e[c]);e="isSetUser isSetCopyUser isSetUserEmpty emptyToTask emptyNoteDone isSelectAgain isOnlyOne isAnyone isByOrder sameUserSubmit isSetMonitor isInheritMonitor untreadType snName serialNo printTemplate printTemplateId listenerName listener".split(" ");
for(c=0;c<e.length;c++)oSetElement(d,e[c],sGetFormFieldValue(a,e[c]))}
function SubFlowLoadEvent(b,d){var a=$("#subFlowForm")[0];a.name.value=null==d.getAttribute("name")?"":d.getAttribute("name");a.id.value=null==d.getAttribute("id")?"":d.getAttribute("id");var c=d.selectSingleNode("newFlows");if(null!=c&&(c=c.selectNodes("newFlow"),null!=c))for(var e=0;e<c.length;e++){var f={};f.name=$(c[e]).selectSingleNode("name").text();f.value=$(c[e]).selectSingleNode("value").text();f.conditionName=$(c[e]).selectSingleNode("conditionName").text();f.conditionValue=$(c[e]).selectSingleNode("conditionValue").text();
f.createName=null==$(c[e]).selectSingleNode("createName")?"":$(c[e]).selectSingleNode("createName").text();f.createValue=null==$(c[e]).selectSingleNode("createValue")?"":$(c[e]).selectSingleNode("createValue").text();f.isMerge=$(c[e]).selectSingleNode("isMerge").text();f.isWait=$(c[e]).selectSingleNode("isWait").text();f.isShare=$(c[e]).selectSingleNode("isShare").text();f.toTaskName=$(c[e]).selectSingleNode("toTaskName").text();f.toTaskId=$(c[e]).selectSingleNode("toTaskId").text();f.copyFieldNames=
null==$(c[e]).selectSingleNode("copyFieldNames")?"":$(c[e]).selectSingleNode("copyFieldNames").text();f.copyFields=$(c[e]).selectSingleNode("copyFields").text();f.returnOverrideFieldNames=null==$(c[e]).selectSingleNode("returnOverrideFieldNames")?"":$(c[e]).selectSingleNode("returnOverrideFieldNames").text();f.returnOverrideFields=$(c[e]).selectSingleNode("returnOverrideFields").text();f.returnAdditionFieldNames=null==$(c[e]).selectSingleNode("returnAdditionFieldNames")?"":$(c[e]).selectSingleNode("returnAdditionFieldNames").text();
f.returnAdditionFields=$(c[e]).selectSingleNode("returnAdditionFields").text();f.notifyDoing=null==$(c[e]).selectSingleNode("notifyDoing")?"":$(c[e]).selectSingleNode("notifyDoing").text();var g=f.name+"|"+f.conditionName+"|"+f.createName+"|"+("1"==f.isMerge?"\u662f":"\u5426")+"|"+("1"==f.isWait?"\u662f":"\u5426")+"|"+("1"==f.isShare?"\u662f":"\u5426")+"|"+f.toTaskName,g=$("<option>"+g+"</option>");g.data("value",f);$("#DNewFlows",a).append(g)}c=d.selectSingleNode("relations");if(null!=c&&(c=c.selectNodes("relation"),
null!=c))for(e=0;e<c.length;e++)f={},f.newFlowName=$(c[e]).selectSingleNode("newFlowName").text(),f.newFlowId=$(c[e]).selectSingleNode("newFlowId").text(),f.taskName=$(c[e]).selectSingleNode("taskName").text(),f.taskId=$(c[e]).selectSingleNode("taskId").text(),f.frontNewFlowName=$(c[e]).selectSingleNode("frontNewFlowName").text(),f.frontNewFlowId=$(c[e]).selectSingleNode("frontNewFlowId").text(),f.frontTaskName=$(c[e]).selectSingleNode("frontTaskName").text(),f.frontTaskId=$(c[e]).selectSingleNode("frontTaskId").text(),
g=f.newFlowName+" | "+f.taskName+" | "+f.frontNewFlowName+" | "+f.frontTaskName,g=$("<option>"+g+"</option>"),g.data("value",f),$("#DRelations",a).append(g);bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),window)}
function SubFlowLoadInitEvent(b,d){var a=$("#subFlowForm")[0];$(".tabs",a).tabs();$("#btn_save",a).button().click(function(){SubFlowOKEvent(b,d);null!=b.xmlObject&&bSetObjectText(b)});$("#btn_abandon",a).button().click(function(){saveSetting=!1;setTaskProperty(b,window.eWorkFlow.contentWindow,goWorkFlow)});$("#newFlowAdd",a).click(function(){sGetNewFlow({},function(b){if(null!=b){var d=$("<option>"+(b.name+"|"+b.conditionName+"|"+b.createName+"|"+("1"==b.isMerge?"\u662f":"\u5426")+"|"+("1"==b.isWait?
"\u662f":"\u5426")+"|"+("1"==b.isShare?"\u662f":"\u5426")+"|"+b.toTaskName)+"</option>");d.data("value",b);$("#DNewFlows",a).append(d)}})});$("#DNewFlows").dblclick(function(){$("#newFlowEdit",a).trigger("click")});$("#newFlowEdit",a).click(function(){var b=$("#DNewFlows > option:selected",a);if(0==b.length)return!1;var d=b.data("value")||{};sGetNewFlow(d,function(a){null!=a&&(b.text(a.name+"|"+a.conditionName+"|"+a.createName+"|"+("1"==a.isMerge?"\u662f":"\u5426")+"|"+("1"==a.isWait?"\u662f":"\u5426")+
"|"+("1"==a.isShare?"\u662f":"\u5426")+"|"+a.toTaskName),b.data("value",a))})});$("#newFlowDelete",a).click(function(){bMoveEntry(a.DNewFlows)});$("#relationAdd",a).click(function(){var b=getNewFlows(a);sGetRelation(b,{},function(b){if(null!=b){var c=$("<option>"+(b.newFlowName+"  |  "+b.taskName+"  |  "+b.frontNewFlowName+"  |  "+b.frontTaskName)+"</option>");c.data("value",b);$("#DRelations",a).append(c)}})});$("#DRelations",a).dblclick(function(){$("#relationEdit",a).trigger("click")});$("#relationEdit",
a).click(function(){var b=getNewFlows(a),d=$("#DRelations > option:selected",a);if(0==d.length)return!1;var f=d.data("value")||{};sGetRelation(b,f,function(a){null!=a&&(d.text(a.newFlowName+"  |  "+a.taskName+"  |  "+a.frontNewFlowName+"  |  "+a.frontTaskName),d.data("value",a))})});$("#relationDelete",a).click(function(){bMoveEntry(a.DRelations)})}
function getNewFlows(b){for(var d=[],a=0;a<b.DNewFlows.options.length;a++){var c=$(b.DNewFlows.options[a]).data("value");c.name=c.name;c.id=c.value;d.push(c)}return d}
function sGetNewFlow(b,d){$.get(ctx+"/workflow/flow/select2.htm",function(a){$("#dlg_new_flow").dialog({title:"\u65b0\u6d41\u7a0b",autoOpen:!0,resizable:!1,width:500,height:450,overlay:!1,modal:!0,close:function(){$("#dlg_new_flow").dialog("destroy");$("#dlg_new_flow").html("<div/>")},open:function(){$("#dlg_new_flow").html(a);NewFlowLoadEvent(b)},buttons:{"\u786e\u5b9a":function(){var a=$("#newFlowValue","#newFlowForm").val();null==a||""==a?alert("\u8bf7\u9009\u62e9\u6d41\u7a0b!"):(a=NewFlowOKEvent(),
d(a),$(this).dialog("close"))},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function sGetRelation(b,d,a){$.get(ctx+"/workflow/flow/relation.htm",function(c){$("#dlg_new_relation").dialog({title:"\u524d\u7f6e\u6d41\u7a0b\u5173\u7cfb",autoOpen:!0,resizable:!1,width:500,height:440,overlay:!1,modal:!0,close:function(){$("#dlg_new_relation").dialog("destroy");$("#dlg_new_relation").html("<div/>")},open:function(){$("#dlg_new_relation").html(c);NewRelationLoadEvent(b,d);NewRelationInitEvent(b,d)},buttons:{"\u786e\u5b9a":function(){var b=$("#frontNewFlowName","#relationForm").val();
null==b||""==b||"0"==b?alert("\u8bf7\u9009\u62e9\u524d\u7f6e\u6d41\u7a0b!"):(b=NewRelationOKEvent(),a(b),$(this).dialog("close"))},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}function setFrontNewFlow(b,d){$("#frontNewFlowName",b).find("option[value!=0]").remove();$.each(d,function(){var a=$("#newFlowName",b).val();this.id!==a&&(a="<option value='"+this.id+"'>"+this.name+"</option>",$("#frontNewFlowName",b).append(a))})}
function NewRelationLoadEvent(b,d){var a=$("#relationForm")[0];$.each(b,function(){var b="<option value='"+this.id+"'>"+this.name+"</option>";$("#newFlowName",a).append(b)});$("#newFlowName",a).val(d.newFlowId);setFrontNewFlow(a,b);$("#frontNewFlowName",a).val(d.frontNewFlowId);var c=d.newFlowId;if(null==c||""==c)c=$("#newFlowName",a).val();initTask(a,"#taskName",c,!1,!1,!1);$("#taskName",a).val(d.taskId);c=d.frontNewFlowId;if(null==c||""==c)c=$("#frontNewFlowName",a).val();initTask(a,"#frontTaskName",
c,!1,!1,!1);$("#frontTaskName",a).val(d.frontTaskId)}function NewRelationInitEvent(b){var d=$("#relationForm")[0];$("#newFlowName",d).change(function(){var a=$(this).val();initTask(d,"#taskName",a,!1,!1,!1);setFrontNewFlow(d,b);$("#frontNewFlowName",d).trigger("change")});$("#frontNewFlowName",d).change(function(){var a=$(this).val();initTask(d,"#frontTaskName",a,!1,!1,!1)})}
function NewRelationOKEvent(){var b=$("#relationForm")[0],d={};d.newFlowName=$("#newFlowName > option:selected",b).text();d.newFlowId=$("#newFlowName",b).val();d.taskName=$("#taskName > option:selected",b).text();d.taskId=$("#taskName",b).val();d.frontNewFlowName=$("#frontNewFlowName > option:selected",b).text();d.frontNewFlowId=$("#frontNewFlowName",b).val();d.frontTaskName=$("#frontTaskName > option:selected",b).text();d.frontTaskId=$("#frontTaskName",b).val();return d}
function NewFlowLoadEvent(b){function d(b,c,d){var j=$.fn.zTree.getZTreeObj(c);b=j.getCheckedNodes(!0);$.each(b,function(){j.checkNode(this,!1)});j.checkNode(d,!0);d.isParent?($("#newFlowName",a).val(""),$("#newFlowValue",a).val("")):($("#newFlowName",a).val(d.name),$("#newFlowValue",a).val(d.data),initToTask(d.data,!0))}var a=$("#newFlowForm")[0],c=goWorkFlow.flowXML.selectSingleNode("./property/formID"),c=null!=c?c.text():"";$("#newFlowName",a).val(b.name);$("#newFlowValue",a).val(b.value);$("#conditionName",
a).val(b.conditionName);$("#conditionValue",a).val(b.conditionValue);$("#createName",a).val(b.createName);$("#createValue",a).val(b.createValue);$("#isMerge",a)[0].checked="1"==b.isMerge?!0:!1;$("#isWait",a)[0].checked="1"==b.isWait?!0:!1;$("#isShare",a)[0].checked="1"==b.isShare?!0:!1;$("#copyFieldNames",a).val(b.copyFieldNames);$("#copyFields",a).val(b.copyFields);$("#returnOverrideFieldNames",a).val(b.returnOverrideFieldNames);$("#returnOverrideFields",a).val(b.returnOverrideFields);$("#returnAdditionFieldNames",
a).val(b.returnAdditionFieldNames);$("#returnAdditionFields",a).val(b.returnAdditionFields);$("#notifyDoing",a)[0].checked="1"==b.notifyDoing?!0:!1;null!=b.value&&""!=b.value&&(initToTask(b.value,!1),$("#toTaskName",a).val(b.toTaskId));b={view:{showIcon:!1,showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getFlowTree",data:c}},check:{enable:!0,chkStyle:"radio"},callback:{onClick:function(a,b,c){d(a,b,c)},onCheck:function(a,b,c){d(a,b,c)}}};$("#newFlowName",a).comboTree({labelField:"newFlowName",
valueField:"newFlowValue",autoInitValue:!1,treeSetting:b,width:360,height:230});JDS.call({service:"flowSchemeService.getFormFields",data:[-1,c],success:function(b){onGetFormFields("#createName",a,b.data);$("#createName").val($("#createValue").val())}});$("#createName").change(function(){$("#createValue").val($(this).val())});$("#copyFieldNames",a).click(function(){newFlowSelectField("copyFieldNames","copyFields")});$("#returnOverrideFieldNames",a).click(function(){newFlowSelectField("returnOverrideFieldNames",
"returnOverrideFields")});$("#returnAdditionFieldNames",a).click(function(){newFlowSelectField("returnAdditionFieldNames","returnAdditionFields")});$("#isMerge",a)[0].checked?$("#span_isWait").show():($("#isWait",a)[0].checked=!1,$("#span_isWait",a).hide());$("#isMerge",a).change(function(){$("#isMerge",a)[0].checked?$("#span_isWait",a).show():$("#span_isWait",a).hide()})}
function newFlowSelectField(b,d){var a=$("#newFlowForm")[0],c=goWorkFlow.flowXML.selectSingleNode("./property/formID"),c=null!=c?c.text():"",e=$("#newFlowValue",a).val();if(null==c||""==c)alert("\u8bf7\u8bbe\u7f6e\u6d41\u7a0b\u8868\u5355!");else if(null==e||""==e)alert("\u8bf7\u8bbe\u7f6e\u5b50\u6d41\u7a0b!");else{var f=$("#"+b).val(),g=$("#"+d).val(),j={formUuid:c,newFlowId:e,initNames:f,initValues:g};$.get(ctx+"/workflow/field/select.htm",function(c){$("#dlg_select_field").dialog({title:"\u5b57\u6bb5\u8bbe\u7f6e",
autoOpen:!0,resizable:!1,width:500,height:450,overlay:!1,modal:!0,close:function(){$("#dlg_select_field").dialog("destroy");$("#dlg_select_field").html("<div/>")},open:function(){$("#dlg_select_field").html(c);FieldSelectInitEvent(j)},buttons:{"\u786e\u5b9a":function(){var c=FieldSelectOKEvent();null!=c?($("#"+b,a).val(c.name),$("#"+d,a).val(c.value)):($("#"+b,a).val(""),$("#"+d,a).val(""));$(this).dialog("close")},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}}
function FieldSelectInitEvent(b){var d=$("#fieldSelectForm")[0],a=b.newFlowId;JDS.call({service:"flowSchemeService.getFormFields",data:[-1,b.formUuid],async:!1,success:function(a){onGetFormFields("select[name=fields1]",d,a.data)}});JDS.call({service:"flowSchemeService.getFormFieldsByFlowDefId",data:[a],async:!1,success:function(a){onGetFormFields("select[name=fields2]",d,a.data)}});var a=b.initNames,c=b.initValues;if(null!=a&&(""!=a&&null!=c&&""!=c)&&(b=a.split(";"),a=c.split(";"),b.length===a.length)){for(var c=
[],e=0;e<b.length;e++)c.push({name:b[e],data:a[e]});onGetFormFields("select[name=selectFields]",d,c);b=$("#selectFields > option");$.each(b,function(){$(this).click(function(){var a=$(this).val();null!=a&&-1!=a.indexOf("|")&&(a=a.split("|"),$("#fields1",d).val(a[0]),$("#fields2",d).val(a[1]))})})}$("#fieldAdd",d).click(function(){var a=$("#fields1 > option:selected",d).text(),b=$("#fields1",d).val(),c=$("#fields2 > option:selected",d).text(),e=$("#fields2",d).val(),a=a+"|"+c,c=b+"|"+e;"-1"==b?alert("\u8bf7\u9009\u62e9\u4e3b\u6d41\u7a0b\u8868\u5355\u5b57\u6bb5!"):
"-1"==e?alert("\u8bf7\u9009\u62e9\u5b50\u6d41\u7a0b\u8868\u5355\u5b57\u6bb5!"):(b=$('<option value="'+c+'">'+a+"</option>"),$("#selectFields",d).append(b),b.click(function(){var a=$(this).val();null!=a&&-1!=a.indexOf("|")&&(a=a.split("|"),$("#fields1",d).val(a[0]),$("#fields2",d).val(a[1]))}))});$("#selectFieldDelete",d).click(function(){var a=$("#selectFields > option:selected",d);0==a.length?alert("\u8bf7\u9009\u62e9\u8bb0\u5f55!"):a.remove()})}
function FieldSelectOKEvent(){var b=$("#fieldSelectForm")[0],b=$("#selectFields > option",b),d={},a=[],c=[];$.each(b,function(){a.push($(this).text());c.push($(this).val())});d.name=a.join(";");d.value=c.join(";");return d}
function NewFlowOKEvent(){var b=$("#newFlowForm")[0],d={};d.name=$("#newFlowName",b).val();d.value=$("#newFlowValue",b).val();d.conditionName=$("#conditionName",b).val();d.conditionValue=d.conditionName;d.createName=$("#createName > option:selected",b).text();d.createValue=$("#createValue",b).val();d.isMerge=!0==$("#isMerge",b)[0].checked?"1":"0";d.isWait=!0==$("#isWait",b)[0].checked?"1":"0";d.isShare=!0==$("#isShare",b)[0].checked?"1":"0";d.toTaskName=$("#toTaskName > option:selected",b).text();
d.toTaskId=$("#toTaskName",b).val();d.copyFieldNames=$("#copyFieldNames",b).val();d.copyFields=$("#copyFields",b).val();d.returnOverrideFieldNames=$("#returnOverrideFieldNames",b).val();d.returnOverrideFields=$("#returnOverrideFields",b).val();d.returnAdditionFieldNames=$("#returnAdditionFieldNames",b).val();d.returnAdditionFields=$("#returnAdditionFields",b).val();d.notifyDoing=$("#notifyDoing",b).val();return d}
function initTask(b,d,a,c,e,f,g){if(null==a||""==a)$(d).html("");else{var j=$(b)[0];$(d,j).html("");JDS.call({service:"flowSchemeService.getFlowTasks",data:[a],async:c,success:function(a){a=a.data;e&&$(d,j).append("<option value='DRAFT'>\u8349\u641e</option>");f&&$(d,j).append("<option value='AUTO_SUBMIT'>\u81ea\u52a8\u63d0\u4ea4</option>");$.each(a,function(){var a=this.id,b=this.name;g!==a&&$(d,j).append("<option value='"+a+"'>"+b+"</option>")})}})}}
function initToTask(b,d){initTask("#newFlowForm","#toTaskName",b,d,!0,!0)}
function SubFlowOKEvent(b,d){var a=$("#subFlowForm")[0];d.setAttribute("name",a.name.value);d.setAttribute("id",a.id.value);loNode=d.selectSingleNode("newFlows");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"newFlows");for(var c=0;c<a.DNewFlows.options.length;c++){var e=$(a.DNewFlows.options[c]).data("value"),f=oAddElement(loNode,"newFlow");oAddElement(f,"name",e.name);oAddElement(f,"value",e.value);oAddElement(f,"conditionName",e.conditionName);oAddElement(f,"conditionValue",e.conditionValue);
oAddElement(f,"createName",e.createName);oAddElement(f,"createValue",e.createValue);oAddElement(f,"isMerge",e.isMerge);oAddElement(f,"isWait",e.isWait);oAddElement(f,"isShare",e.isShare);oAddElement(f,"toTaskName",e.toTaskName);oAddElement(f,"toTaskId",e.toTaskId);oAddElement(f,"copyFieldNames",e.copyFieldNames);oAddElement(f,"copyFields",e.copyFields);oAddElement(f,"returnOverrideFieldNames",e.returnOverrideFieldNames);oAddElement(f,"returnOverrideFields",e.returnOverrideFields);oAddElement(f,"returnAdditionFieldNames",
e.returnAdditionFieldNames);oAddElement(f,"returnAdditionFields",e.returnAdditionFields);oAddElement(f,"notifyDoing",e.notifyDoing)}loNode=d.selectSingleNode("relations");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"relations");for(c=0;c<a.DRelations.options.length;c++)e=$(a.DRelations.options[c]).data("value"),f=oAddElement(loNode,"relation"),oAddElement(f,"newFlowName",e.newFlowName),oAddElement(f,"newFlowId",e.newFlowId),oAddElement(f,"taskName",e.taskName),oAddElement(f,"taskId",
e.taskId),oAddElement(f,"frontNewFlowName",e.frontNewFlowName),oAddElement(f,"frontNewFlowId",e.frontNewFlowId),oAddElement(f,"frontTaskName",e.frontTaskName),oAddElement(f,"frontTaskId",e.frontTaskId)}
function ConditionLoadEvent(b,d){var a=$("#conditionForm")[0];$(".tabs",a).tabs();$("#btn_save",a).button();a.name.value=d.getAttribute("name");a.description.value=d.text();$("#btn_save",a).unbind("click");$("#btn_save",a).click(function(){d.setAttribute("name",a.name.value);d.get(0).childNodes[0].nodeValue=a.description.value;null!=b.xmlObject&&bSetObjectText(b)});$("#btn_abandon",a).button().click(function(){saveSetting=!1;setTaskProperty(b,window.eWorkFlow.contentWindow,goWorkFlow)})}
function setDirectionProperty(b,d,a){goWorkFlow=a;d=[];a=null;a="CONDITION"==b.fromTask.Type?null!=b.fromTask.inLines&&0<b.fromTask.inLines.length?b.fromTask.inLines[0].fromTask:null:b.fromTask;if(null!=a&&(a=a.xmlObject.selectSingleNode("optNames"),null!=a&&(a=a.selectNodes("unit"),null!=a)))for(var c=0;c<a.length;c++){var e=$(a[c]).selectSingleNode("value").text(),f=$(a[c]).selectSingleNode("argValue").text();d.push(f+"|"+e)}if(void 0!=b.xmlObject){var g=[];g.optname=d.join(";");saveCurrentSetting();
$.get(ctx+"/workflow/direction2.htm",function(a){$("#eProperty").html(a);DirectionLoadEvent(b,b.xmlObject,g.optname);DirectionInitEvent(b,b.xmlObject,g.optname)})}}
function DirectionLoadEvent(b,d,a){b=$("#directionForm")[0];"2"==d.getAttribute("type")?(b.DCondition.optnames=a,$(".fork_condition",b).show()):$(".fork_condition",b).hide();$(".tabs",b).tabs();a=d.selectSingleNode("conditions");if(null!=a){var c=a.selectNodes("unit");if(null!=c)for(a=0;a<c.length;a++){var e=$(c[a]).selectSingleNode("value").text(),f=$(c[a]).selectSingleNode("argValue").text();bAddEntry(b.DCondition,f,e,!0)}}b.name.value=null==d.getAttribute("name")?"":d.getAttribute("name");b.id.value=
null==d.getAttribute("id")?"":d.getAttribute("id");c=["fileRecipient","msgRecipient"];for(a=0;a<c.length;a++)bGetUnitXMLToField(d,b,c[a]);c="isDefault isEveryCheck isSendFile isSendMsg listenerName listener".split(" ");for(a=0;a<c.length;a++)e=null!=d.selectSingleNode(c[a])?d.selectSingleNode(c[a]).text():null,null!=e&&""!=e&&bSetFormFieldValue(b,c[a],e);bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),window)}
function DirectionInitEvent(b,d){var a=$("#directionForm")[0];$(".tabs",a).tabs();$("#btn_save",a).button().click(function(){DirectionOKEvent(a,d);b.xmlObject&&bSetObjectText(b.labelObject)});$("#btn_abandon",a).button().click(function(){saveSetting=!1;setDirectionProperty(b,window.eWorkFlow.contentWindow,goWorkFlow)});$("input[name=isDefault]",a).change(function(){"isDefault_0"===this.id&&this.checked?$("#ID_DefaultDirection").show():"isDefault_1"===this.id&&this.checked&&$("#ID_DefaultDirection").hide()}).trigger("change");
$("input[name=isSendFile]").change(function(){"isSendFile_1"===this.id&&this.checked&&$("#ID_IsSendFile").show();"isSendFile_0"===this.id&&this.checked&&$("#ID_IsSendFile").hide()}).trigger("change");$("input[name=isSendMsg]").change(function(){"isSendMsg_1"===this.id&&this.checked&&$("#ID_IsSendMsg").show();"isSendMsg_0"===this.id&&this.checked&&$("#ID_IsSendMsg").hide()}).trigger("change");$("#conditionAdd").click(function(b){bDirectionActions(1,b,a)});$("#conditionInsert").click(function(b){bDirectionActions(2,
b,a)});$("#conditionEdit").click(function(b){bDirectionActions(3,b,a)});$("#conditionDelete").click(function(b){bDirectionActions(4,b,a)});$("#Dir_DfileRecipients").click(function(b){b.target.title="\u9009\u62e9\u6587\u4ef6\u5206\u53d1\u5bf9\u8c61";bDirectionActions(5,b,a)});$("#Dir_DmsgRecipients").click(function(b){b.target.title="\u9009\u62e9\u6d88\u606f\u5206\u53d1\u5bf9\u8c61";bDirectionActions(6,b,a)});$("#listenerName").comboTree({labelField:"listenerName",valueField:"listener",treeSetting:{view:{showIcon:!1,
showLine:!1},async:{otherParam:{serviceName:"flowSchemeService",methodName:"getDirectionListeners"}}},autoInitValue:!1,width:530,height:260})}
function bDirectionActions(b,d,a){switch(b){case 1:b=function(b){null==b||0==b.length||bAddEntry(a.DCondition,b[0],b[1])};aGetCondition(-1,b,a);break;case 2:b=function(b){null==b||0==b.length||bInsertEntry(a.DCondition,b[0],b[1])};aGetCondition(-2,b,a);break;case 3:b=function(b){null==b||0==b.length||bEditEntry(a.DCondition,b[0],b[1])};aGetCondition(a.DCondition.selectedIndex,b,a);break;case 4:bMoveEntry(a.DCondition);break;case 5:SelectUsers("","fileRecipient",d.target.title,null,a);break;case 6:SelectUsers("",
"msgRecipient",d.target.title,null,a)}}
function aGetCondition(b,d,a){var c=goWorkFlow.flowXML.selectSingleNode("./property/formID");if(""==(null!=c?c.text():""))return alert(parent.sGetLang("FLOW_WF_FLOWFORMISEMPTY")),null;var e=c=null,f=!1;0<=b?(c=a.DCondition.options[b].text,e=a.DCondition.options[b].value,0<b&&(f=!0)):-2==b?0<a.DCondition.selectedIndex&&(f=!0):1<=a.DCondition.options.length&&(f=!0);var g=[];g.value=null!=e?e:"";g.text=null!=c?c:"";g.logic=f;g.optnames=a.DCondition.optnames;g.opener=opener;$.get(ctx+"/workflow/logic2.htm",
function(a){$("#dlg_logic").dialog({title:"\u5224\u65ad\u6761\u4ef6",autoOpen:!0,resizable:!1,width:600,height:250,modal:!0,close:function(){$("#dlg_logic").dialog("destroy");$("#dlg_logic").html("<div/>")},open:function(){$("#dlg_logic").html(a);bInitLogicValue(g);LogicLoadEvent(g)},buttons:{"\u786e\u5b9a":function(){if(aLogicCheckValue(g)){var a=aLogicBuildValue(g);d(a);$(this).dialog("close")}},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function bLogicActions(b,d,a){switch(b){case 1:SelectUsers("","Group",d.target.title,null,a)}}
function bInitLogicValue(b){var d=b.text,a=b.value,c=b.logic,e=b.optnames;b=$("#logicForm")[0];if(null!=e)for(var e=e.split(";"),f=0;f<e.length;f++)bAddEntry(b.VoteOption,e[f],"[VOTE="+e[f].substring(e[f].indexOf("|")+1,e[f].length)+"]",!0);c?$("#ID_Logic",b).show():$("#ID_Logic",b).hide();if(null==a||""==a)return!1;-1!=a.indexOf("@ISMEMBER(")?(b.LogicType[2].checked=!0,e=a.substring(0,a.indexOf("@ISMEMBER(")),c&&(-1!=e.indexOf("&")?bSetFormFieldValue(b,"AndOr","&"):-1!=e.indexOf("|")&&bSetFormFieldValue(b,
"AndOr","|")),-1!=e.indexOf("(")&&bSetFormFieldValue(b,"gLBracket","("),e=a.substring(a.lastIndexOf('")')+2,a.length),-1!=e.indexOf(")")&&bSetFormFieldValue(b,"gRBracket",")"),a=a.substring(a.indexOf('@ISMEMBER("')+11,a.lastIndexOf('")')),c=a.split('","'),"<CURUSER>"!=c[0]?(b.GroupType.value=0,ID_UserField.style.display="",b.UserField.value=c[0]):"<CURUSER>"==c[0]&&(b.GroupType.value=1),b.Groups.value=c[1],d=d.substring(d.indexOf('@ISMEMBER("')+11,d.lastIndexOf('")')),b.DGroups.value=d.split('","')[1]):
-1!=a.indexOf("[VOTE=")?(b.LogicType[1].checked=!0,0==a.indexOf(" & ")?(c&&bSetFormFieldValue(b,"AndOr","&"),a=a.substring(3,a.length)):0==a.indexOf(" | ")&&(c&&bSetFormFieldValue(b,"AndOr","|"),a=a.substring(3,a.length)),0==a.indexOf("(")&&(bSetFormFieldValue(b,"vLBracket","("),a=a.substring(1,a.length)),a.lastIndexOf(")")==a.length-1&&(bSetFormFieldValue(b,"vRBracket",")"),a=a.substring(0,a.length-1)),bSetFormFieldValue(b,"VoteOption",a.substr(0,a.indexOf(" "))),a=a.substr(a.indexOf(" ")+1),bSetFormFieldValue(b,
"vOperator",a.substr(0,a.indexOf(" "))),b.vValue.value=a.substr(a.indexOf(" ")+1)):(0==a.indexOf(" & ")?(c&&bSetFormFieldValue(b,"AndOr","&"),a=a.substring(3,a.length)):0==a.indexOf(" | ")&&(c&&bSetFormFieldValue(b,"AndOr","|"),a=a.substring(3,a.length)),0==a.indexOf("(")&&(bSetFormFieldValue(b,"LBracket","("),a=a.substring(1,a.length)),a.lastIndexOf(")")==a.length-1&&(bSetFormFieldValue(b,"RBracket",")"),a=a.substring(0,a.length-1)),b.FieldName.value=a.substr(0,a.indexOf(" ")),a=a.substr(a.indexOf(" ")+
1),bSetFormFieldValue(b,"Operator",a.substr(0,a.indexOf(" "))),b.Value.value=a.substr(a.indexOf(" ")+1));bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),window);return!0}
function LogicLoadEvent(b){var d=$("#logicForm")[0],a=goWorkFlow.flowXML.selectSingleNode("./property/formID"),a=null!=a?a.text():"";JDS.call({service:"flowSchemeService.getFormFields",data:[-1,a],success:function(a){onGetFormFields("select[name=FieldNameLabel]",d,a.data);$("#FieldNameLabel").val($("#FieldName").val())}});$("#FieldNameLabel").change(function(){$("#FieldName").val($(this).val())});JDS.call({service:"flowSchemeService.getFormFields",data:[-1,a],success:function(a){onGetFormFields("select[name=UserFieldLabel]",
d,a.data);$("#UserFieldLabel").val($("#UserField").val())}});$("#UserFieldLabel").change(function(){$("#UserField").val($(this).val())});$("input[name=LogicType]",d).change(function(){bChangeLogicType(this,b)}).trigger("change");$("select[name=GroupType]",d).change(function(){"0"===$(this).val()?$("#ID_UserField",d).show():$("#ID_UserField",d).hide()}).trigger("change");a=d.Groups.value.split(",");5==a.length&&(d.DGroup1.value=a[0],d.Group1.value=a[1],d.Group2.value=a[2],d.Group4.value=a[3],d.Group8.value=
a[4]);$("#DGroups").click(function(a){a.target.title="\u9009\u62e9\u7fa4\u7ec4";bLogicActions(1,a,d)})}
function bChangeLogicType(b,d){var a=d.optnames;"2"==b.value&&(null==a||""==a)&&alert(Logic_ID_Vote.OptNamesIsEmpty);"1"==b.value&&b.checked?($("#Logic_ID_Field").show(),$("#Logic_ID_Vote").hide(),$("#Logic_ID_Group").hide()):"2"==b.value&&b.checked?($("#Logic_ID_Field").hide(),$("#Logic_ID_Vote").show(),$("#Logic_ID_Group").hide()):"3"==b.value&&b.checked&&($("#Logic_ID_Field").hide(),$("#Logic_ID_Vote").hide(),$("#Logic_ID_Group").show())}
function aLogicCheckValue(){var b=$("#logicForm")[0];if(!0==b.LogicType[0].checked){if(""==b.FieldName.value)return alert("\u8bf7\u9009\u62e9\u5b57\u6bb5!"),!1}else if(!0==b.LogicType[1].checked){if(""==b.vValue.value)return alert("\u8bf7\u8f93\u5165\u6240\u5360\u767e\u5206\u6bd4!"),!1;if(-1!=b.vValue.value.indexOf("%"))return alert("\u4e0d\u9700\u8981\u5728\u6240\u5360\u767e\u5206\u6bd4\u4e2d\u8f93\u5165\u767e\u5206\u53f7\u201c\uff05\u201d!"),!1}else if(!0==b.LogicType[2].checked){if(""==b.GroupType.value)return alert("\u8bf7\u6307\u5b9a\u6210\u5458!"),
!1;if("0"==b.GroupType.value&&""==b.UserField.value)return alert("\u8bf7\u9009\u62e9\u5b57\u6bb5!"),!1;if(""==b.DGroups.value)return alert("\u8bf7\u6307\u5b9a\u7fa4\u7ec4!"),!1}return!0}
function aLogicBuildValue(b){var d=b.logic;b=$("#logicForm")[0];b.Groups.value=$("input[name='DGroup1']",b).val()+","+$("input[name='Group1']",b).val()+","+$("input[name='Group2']",b).val()+","+$("input[name='Group4']",b).val()+","+$("input[name='Group8']",b).val();if(!0==b.LogicType[0].checked){if(""==b.FieldName.value)return alert(b.FieldName.emptymsg),null}else if(!0==b.LogicType[1].checked){if(""==b.vValue.value)return alert(b.vValue.emptymsg),null;if(-1!=b.vValue.value.indexOf("%"))return alert(b.vValue.errormsg),
null}else if(!0==b.LogicType[2].checked){if("0"==b.GroupType.value&&""==b.UserField.value)return alert(b.UserField.emptymsg),null;if(""==b.DGroups.value)return alert(b.DGroups.emptymsg),null}var a=[],c="",e="";d&&""!=b.AndOr.options[b.AndOr.selectedIndex].value&&(c=b.AndOr.options[b.AndOr.selectedIndex].text+" ",e=" "+b.AndOr.options[b.AndOr.selectedIndex].value+" ");if(!0==b.LogicType[0].checked){var f=b.Operator.options[b.Operator.selectedIndex].value,g=b.Operator.options[b.Operator.selectedIndex].text,
d=b.LBracket.options[b.LBracket.selectedIndex].value,j=b.RBracket.options[b.RBracket.selectedIndex].value,c=c+d+"["+b.FieldNameLabel.options[b.FieldNameLabel.selectedIndex].text+"] "+g+" "+b.Value.value+j,e=e+d+b.FieldName.value+" "+f+" "+b.Value.value+j;-1!=b.FieldName.value&&(a.push(c),a.push(e))}else if(!0==b.LogicType[1].checked){var g=b.vOperator.options[b.vOperator.selectedIndex].text,f=b.vOperator.options[b.vOperator.selectedIndex].value,d=b.vLBracket.options[b.vLBracket.selectedIndex].value,
j=b.vRBracket.options[b.vRBracket.selectedIndex].value,k=b.VoteOption.options[b.VoteOption.selectedIndex].value,c=c+d+"["+b.VoteOption.options[b.VoteOption.selectedIndex].text+"] "+g+" "+b.vValue.value+"%"+j,e=e+d+k+" "+f+" "+b.vValue.value+j;a.push(c);a.push(e)}else!0==b.LogicType[2].checked&&(d=b.gLBracket.options[b.gLBracket.selectedIndex].value,j=b.gRBracket.options[b.gRBracket.selectedIndex].value,f="1"==b.GroupType.value?"<CURUSER>":b.UserField.value,c=c+d+'@ISMEMBER("'+f+'","'+b.DGroups.value+
'")'+j,e=e+d+'@ISMEMBER("'+f+'","'+b.Groups.value+'")'+j,a.push(c),a.push(e));return a}
function DirectionOKEvent(b,d){loNode=d.selectSingleNode("conditions");null!=loNode&&d.removeChild(loNode);loNode=oSetElement(d,"conditions");for(var a=0;a<b.DCondition.options.length;a++){var c=b.DCondition.options[a].text,e=b.DCondition.options[a].value,f=oAddElement(loNode,"unit");f.setAttribute("type","16");oAddElement(f,"value",e);oAddElement(f,"argValue",c)}d.setAttribute("name",b.name.value);d.setAttribute("id",b.id.value);c=["fileRecipient","msgRecipient"];for(a=0;a<c.length;a++)bSetUnitFieldToXML(d,
b,c[a]);c="isDefault isEveryCheck isSendFile isSendMsg listenerName listener".split(" ");for(a=0;a<c.length;a++)oSetElement(d,c[a],sGetFormFieldValue(b,c[a]))}
function bFlowActions(b,d,a){function c(a,b,c){$.unit.open({initNames:c["D"+a+"1"].value,initIDs:c[a+"1"].value,title:b,multiple:!0,selectType:6,nameType:"21",showType:!0,type:"MyUnit",loginStatus:!1,excludeValues:null,afterSelect:function(b){null!=b&&(c["D"+a+"s"].value=b.name,c["D"+a+"1"].value=b.name,c[a+"1"].value=b.id)}})}switch(b){case 1:c("creator",d.target.title,a);break;case 2:c("user",d.target.title,a);break;case 3:SelectUsers("unit/field/option","monitor",d.target.title,null,a);break;case 4:SelectUsers("unit/field/option",
"admin",d.target.title,null,a);break;case 5:bSetField("dueTime",!1);break;case 6:SelectUsers("direction","beginDirections",d.target.title,null,a);break;case 7:SelectUsers("direction","endDirections",d.target.title,null,a);break;case 8:SelectUsers("","fileRecipient",d.target.title,null,a);break;case 9:SelectUsers("","msgRecipient",d.target.title,null,a);break;case 10:b=function(b){null!=b&&0<b.length&&(a.EQFlowName.value=b[0],a.EQFlowID.value=b[1],goWorkFlow.equalFlowID=a.EQFlowID.value)};aSelectFlow2(d.target.name,
!1,d.target.title,a.EQFlowID.value,b);break;case 11:b=function(b){null==b||""==b||bAddEntry(a.DTimer,b,b)};sGetTimer("",b,a);break;case 12:d=sGetAllEntryValue(a.DTimer,!0);if(null==d||""==d)return!1;b=function(b){null==b||""==b||bEditEntry(a.DTimer,b,b)};sGetTimer(d,b,a);break;case 13:d=sGetAllEntryValue(a.DTimer,!0);if(null==d||""==d)return!1;bMoveEntry(a.DTimer);loNode=goWorkFlow.flowXML.selectSingleNode("./timers/timer[name='"+d+"']");null!=loNode&&loNode.remove();break;case 14:b=function(b){null==
b||0==b.length||bAddEntry(a.DBackUser,b[0]+"->"+b[2],b[1]+"->"+b[3])};aGetBackUser(-1,b,a);break;case 15:d=sGetAllEntryValue(a.DBackUser,!0);if(null==d||""==d)return!1;b=function(b){null==b||0==b.length||bEditEntry(a.DBackUser,b[0]+"->"+b[2],b[1]+"->"+b[3])};aGetBackUser(a.DBackUser.selectedIndex,b,a);break;case 16:bMoveEntry(a.DBackUser);break;case 17:b=function(b){if(null!=b){var c=b.typeName+" "+b.name;null!=b.condition&&""!=$.trim(b.condition)&&(c=c+"("+b.condition+")");c=$("<option>"+c+"</option>");
c.data("value",b);$(a.DMessageTemplate,a).append(c)}};sGetMessageTemplate({},b);break;case 18:var e=$("#DMessageTemplate > option:selected",a);if(0==e.length)return!1;d=e.data("value")||{};b=function(a){if(null!=a){var b=a.typeName+" "+a.name;null!=a.condition&&""!=$.trim(a.condition)&&(b=b+"("+a.condition+")");e.text(b);e.data("value",a)}};sGetMessageTemplate(d,b);break;case 19:bMoveEntry(a.DMessageTemplate)}}
function aGetBackUser(b,d,a){var c=[];if(-1<b){var e=a.DBackUser.options[b].text.split("->");a=a.DBackUser.options[b].value.split("->");c.push(e[0]);c.push(a[0]);c.push(e[1]);c.push(a[1])}var f=[];f.User=-1==b?null:c;$.get(ctx+"/workflow/user/back2.htm",function(a){$("#dlg_user_back").dialog({title:"\u5c97\u4f4d\u4ee3\u66ff\u8bbe\u7f6e",autoOpen:!0,resizable:!0,width:600,height:220,modal:!0,overlay:{background:"#000",opacity:0.5},open:function(){$("#dlg_user_back").html(a);UserBackInitEvent(f)},buttons:{"\u786e\u5b9a":function(){if(UserBackCheck()){var a=
UserBackOKEvent();d(a);$(this).dialog("close")}},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function UserBackInitEvent(b){var d=$("#userBackForm")[0];b=b.User;null!=b&&(d.AUser.value=b[0],d.AUserID.value=b[1],d.BUsers.value=b[2],d.BUserIDs.value=b[3]);$("#AUser").click(function(){$.unit.open({initNames:d.AUser.value,initIDs:d.AUserID.value,title:"\u4eba\u5458\u9009\u62e9",multiple:!1,selectType:4,nameType:"21",showType:!0,type:"MyUnit",loginStatus:!1,excludeValues:null,afterSelect:function(a){null!=a&&(d.AUser.value=a.name,d.AUserID.value=a.id)}})});$("#BUsers").click(function(){$.unit.open({initNames:d.BUsers.value,
initIDs:d.BUserIDs.value,title:"\u4eba\u5458\u9009\u62e9",multiple:!1,selectType:4,nameType:"21",showType:!0,type:"MyUnit",loginStatus:!1,excludeValues:null,afterSelect:function(a){null!=a&&(d.BUsers.value=a.name,d.BUserIDs.value=a.id)}})})}function UserBackCheck(){var b=$("#userBackForm")[0];return""==b.AUser.value?(alert("\u8bf7\u6307\u5b9aA\u5c97\u4eba\u5458!"),!1):""==b.BUsers.value?(alert("\u8bf7\u6307\u5b9aB\u5c97\u4eba\u5458!"),!1):!0}
function UserBackOKEvent(){var b=$("#userBackForm")[0],d=[];d.push(b.AUser.value);d.push(b.AUserID.value);d.push(b.BUsers.value);d.push(b.BUserIDs.value);return d}
function sGetMessageTemplate(b,d){$.get(ctx+"/workflow/message/template.htm",function(a){$("#dlg_message_template").dialog({title:"\u6d88\u606f\u6a21\u677f",autoOpen:!0,resizable:!1,width:400,height:230,modal:!0,close:function(){$("#dlg_message_template").dialog("destroy");$("#dlg_message_template").html("<div/>")},open:function(){$("#dlg_message_template").html(a);bInitMessageTemplate(b)},buttons:{"\u786e\u5b9a":function(){var a=sMessageTemplateBuildValue(b);d(a);$(this).dialog("close")},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function bInitMessageTemplate(b){var d=b.type,a=b.id,c=b.condition,e=$("#messageTemplateForm")[0];JDS.call({service:"flowSchemeService.getMessageTemplates",data:[],success:function(b){$.each(b.data,function(){var a="<option value='"+this.id+"'>"+this.name+"</option>";$("#templateId",e).append(a)});$("#type",e).val(d);$("#templateId",e).val(a);$("#condition",e).val(c)}})}
function sMessageTemplateBuildValue(){var b=$("#messageTemplateForm")[0],d={},a=$("#type",b).val(),c=$("#type",b).find("option:selected").text(),e=$("#templateId",b).val(),f=$("#templateId",b).find("option:selected").text(),b=$("#condition",b).val();d.type=a;d.typeName=c;d.id=e;d.name=f;d.condition=b;return d}
function sGetTimer(b,d,a){var c=null;null!=b&&""!=b&&(c=goWorkFlow.flowXML.selectSingleNode("./timers/timer[name='"+b+"']"));var e=[];e.Names=sGetAllEntryValue(a.DTimer);e.Form=sGetFormFieldValue(a,"DForm");e.opener=opener;$.get(ctx+"/workflow/timer2.htm",function(a){$("#dlg_timer").dialog({title:"\u8ba1\u65f6\u7cfb\u7edf",autoOpen:!0,resizable:!1,width:600,height:480,modal:!0,close:function(){$("#dlg_timer").dialog("destroy");$("#dlg_timer").html("<div/>")},open:function(){$("#dlg_timer").html(a);
TimerLoadEvent(c,e);TimerInitEvent(c,e)},buttons:{"\u786e\u5b9a":function(){if(TimerOKCheck(c,e)){var a=TimerOKEvent(c,e);d(a);$(this).dialog("close")}},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function aSelectFlow2(b,d,a,c,e){b={view:{showIcon:!1},check:{chkStyle:"radio"},async:{enable:!0,contentType:"application/json",url:ctx+"/json/data/services",otherParam:{serviceName:"flowSchemeService",methodName:"getFlowTree",data:"-1"},type:"POST"}};$("#dlg_select_sub_flow").popupTreeWindow({title:a,initValues:c,autoOpen:!1,treeSetting:b,afterSelect:function(a){if(null!=a){var b=[];b.push(a.name);b.push(a.value);void 0!=e&&e(b)}},afterCancel:function(){},close:function(){$("#dlg_select_sub_flow").html("<div/>")}});
$("#dlg_select_sub_flow").popupTreeWindow("open")}
function SelectUsers(b,d,a,c,e){var f=null!=b&&""!=b?b:"unit/bizRole/task/field/option",g=[];g.Style=f;g.Title=a;var j=null;-1!=f.indexOf("task")&&(b=e.id?e.id.value:"",j=aGetTasks(-1!=f.indexOf("alltask")?"TASK/SUBFLOW":"",-1!=f.indexOf("nocurtask")?b:null,-1!=f.indexOf("alltask")?!0:null),g.Tasks=j,g.MulTask=!0==c?!1:!0);var k=null;-1!=f.indexOf("direction")&&(k=aGetDirections(),g.Directions=k);var h=80;-1!=f.indexOf("unit")&&(h+=50,c=[],b=e["D"+d+"1"],c.push(null!=b?b.value:""),b=e[d+"1"],c.push(null!=
b?b.value:""),g.unit=c);-1!=f.indexOf("bizRole")&&(h+=60,c=[],b=e["D"+d+"16"],c.push(null!=b?b.value:""),b=e[d+"16"],c.push(null!=b?b.value:""),g.bizRole=c);-1!=f.indexOf("field")&&(h+=40,b=e[d+"2"],g.field=null!=b?b.value:"");-1!=f.indexOf("task")&&(h+=80,b=e[d+(-1!=f.indexOf("unit")?"4":"")],g.task=null!=b?b.value:"");-1!=f.indexOf("option")&&(h+=320,b=e[d+"8"],g.option=null!=b?b.value:"");-1!=f.indexOf("direction")&&(h+=100,b=e[d],g.direction=null!=b?b.value:"");200>h&&(h+=100);$.get(ctx+"/workflow/user/select2.htm",
function(b){$("#dlg_select_user").dialog({title:a,autoOpen:!0,resizable:!0,width:600,height:h,modal:!0,close:function(){$("#dlg_select_user").dialog("destroy");$("#dlg_select_user").html("<div/>")},open:function(){$("#dlg_select_user").html(b);SelectUserLoadEvent(g);SelectUserInitEvent(g)},buttons:{"\u786e\u5b9a":function(){var a=SelectUserOKEvent($("#userSelectForm")[0],g);if(null!=a){var b=[];if(-1!=f.indexOf("unit")){var c=e["D"+d+"1"];null!=c&&(c.value=a.unit[0]);c=e[d+"1"];null!=c&&(c.value=
a.unit[1]);""!=a.unit[0]&&b.push(a.unit[0])}-1!=f.indexOf("bizRole")&&(c=e["D"+d+"16"],null!=c&&(c.value=a.bizRole[0]),c=e[d+"16"],null!=c&&(c.value=a.bizRole[1]),""!=a.bizRole[0]&&b.push(a.bizRole[0]));if(-1!=f.indexOf("field")&&(c=e[d+"2"],null!=c&&(c.value=a.field),null!=a.field&&""!=a.field)){for(var h=a.field.split(";"),m=0;m<h.length;m++)h[m]="{"+h[m]+"}";b.push(h.join(";"))}if(-1!=f.indexOf("task"))if(c=e[d+(-1!=f.indexOf("unit")?"4":"")],null!=c&&(c.value=a.task),null!=a.task&&""!=a.task&&
null!=j){h=a.task.split(";");for(m=0;m<h.length;m++){for(var l=0;l<j.length&&j[l].split("|")[1]!=h[m];l++);l<j.length&&(h[m]="<"+j[l].split("|")[0]+">")}-1==f.indexOf("unit")?(c=e["D"+d],null!=c&&(c.value=h.join(";"))):b.push(h.join(";"))}else-1==f.indexOf("unit")&&(c=e["D"+d],null!=c&&(c.value=""));if(-1!=f.indexOf("option")&&(c=e[d+"8"],null!=c&&(c.value=a.option),null!=a.option&&""!=a.option)){h=a.option.split(";");for(m=0;m<h.length;m++)h[m]="["+h[m]+"]";b.push(h.join(";"))}-1!=f.indexOf("unit")&&
(c=e["D"+d+"s"],null!=c&&(c.value=b.join(";")));if(-1!=f.indexOf("direction"))if(c=e[d],null!=c&&(c.value=a.direction),c=e["D"+d],null!=a.direction&&""!=a.direction&&null!=k){h=a.direction.split(";");for(m=0;m<h.length;m++)for(l=0;l<k.length;l++)if(a=k[l].split("|"),a[3]+"|"+a[5]==h[m]){h[m]=a[0]+"("+a[2]+"-"+a[4]+")";break}null!=c&&(c.value=h.join("\r"))}else null!=c&&(c.value="")}$(this).dialog("close")},"\u6e05\u7a7a":function(){bEmptyValue($("#userSelectForm")[0])},"\u53d6\u6d88":function(){$(this).dialog("close")}}})})}
function bTimerActions(b,d,a){switch(b){case 1:bSetField("limit",!1);break;case 2:SelectUsers("","duty",d.target.title,null,a);break;case 3:SelectUsers("task","tasks",d.target.title,null,a);break;case 4:SelectUsers("","alarmUser",d.target.title,null,a);break;case 5:b=function(b){null!=b&&0<b.length&&(a.alarmFlowName.value=b[0],a.alarmFlowID.value=b[1])};aSelectFlow2(d.target.name,!1,d.target.title,a.alarmFlowID.value,b);break;case 6:SelectUsers("","alarmFlowDoingUser",d.target.title,null,a);break;
case 7:SelectUsers("","dueUser",d.target.title,null,a);break;case 8:SelectUsers("","dueToUser",d.target.title,null,a);break;case 9:SelectUsers("alltask","dueToTask",d.target.title,!0,a);break;case 10:b=function(b){null!=b&&0<b.length&&(a.dueFlowName.value=b[0],a.dueFlowID.value=b[1])};aSelectFlow2(d.target.name,!1,d.target.title,a.dueFlowID.value,b);break;case 11:SelectUsers("","dueFlowDoingUser",d.target.title,null,a)}}
function TimerLoadEvent(b){var d=$("#timerForm")[0];if(null!=b){var a=aGetXMLFieldValue(b,"tasks");if(null!=a){d.tasks.value=a.join(";");for(var c=0;c<a.length;c++)a[c]="<"+sGetTaskNameByID(a[c])+">";d.Dtasks.value=a.join(";")}for(var e=["alarmObjects","alarmFlowDoings","dueObjects","dueFlowDoings"],c=0;c<e.length;c++)a=aGetXMLFieldValue(b,e[c]),null!=a&&bSetFormFieldValue(d,e[c],a.join(";"));c=b.selectSingleNode("alarmFlow");null!=c&&(d.alarmFlowName.value=null!=c.selectSingleNode("name")?c.selectSingleNode("name").text():
"",d.alarmFlowID.value=null!=c.selectSingleNode("id")?c.selectSingleNode("id").text():"");c=b.selectSingleNode("dueFlow");null!=c&&(d.dueFlowName.value=null!=c.selectSingleNode("name")?c.selectSingleNode("name").text():"",d.dueFlowID.value=null!=c.selectSingleNode("id")?c.selectSingleNode("id").text():"");e="duty alarmUser alarmFlowDoingUser dueUser dueToUser dueFlowDoingUser".split(" ");for(c=0;c<e.length;c++)bGetUnitXMLToField(b,d,e[c]);e="name limitTimeType limitTime1 limitTime limitUnit affectMainFlow enableAlarm enableDueDoing alarmTime alarmUnit alarmFrequency dueTime dueUnit dueFrequency dueAction dueToTask".split(" ");
for(c=0;c<e.length;c++)a=null!=b.selectSingleNode(e[c])?b.selectSingleNode(e[c]).text():null,null!=a&&""!=a&&bSetFormFieldValue(d,e[c],a);""!=d.dueToTask.value&&(d.DdueToTask.value="<"+sGetTaskNameByID(d.dueToTask.value)+">")}}
function TimerInitEvent(){var b=$("#timerForm")[0];$("#limitTimeType").change(function(){1==$(this).val()?($("#limitTimeType_1").show(),$("#limitTimeType_2").hide()):($("#limitTimeType_1").hide(),$("#limitTimeType_2").show())}).trigger("change");var d=goWorkFlow.flowXML.selectSingleNode("./property/formID"),d=null!=d?d.text():"";JDS.call({service:"flowSchemeService.getFormFields",data:[-1,d],success:function(a){onGetFormFields("#limitTimeLabel",b,a.data);$("#limitTimeLabel").val($("#limitTime").val())}});
$("#limitTimeLabel").change(function(){$("#limitTime").val($(this).val())});$("#Ddutys").click(function(a){a.target.title="\u9009\u62e9\u8d23\u4efb\u4eba";bTimerActions(2,a,b)});$("#Dtasks").click(function(a){a.target.title="\u9009\u62e9\u8ba1\u65f6\u73af\u8282";bTimerActions(3,a,b)});$("#affectMainFlow, #enableAlarm, #enableDueDoing").change(function(){this.checked?(this.value="1","enableAlarm"===this.id?$("#config_enableAlarm").show():"enableDueDoing"===this.id&&$("#config_enableDueDoing").show()):
(this.value="0","enableAlarm"===this.id?$("#config_enableAlarm").hide():"enableDueDoing"===this.id&&$("#config_enableDueDoing").hide())}).trigger("change");$("input[name=alarmTime], input[name=alarmFrequency]").blur(function(){!1==bIsDigital(this.value,1,"\u8bf7\u8f93\u5165\u6570\u5b57!")&&(this.value="1",$(this).trigger("focus"))});$("#DalarmUsers").click(function(a){a.target.title="\u9009\u62e9\u6d88\u606f\u63d0\u9192\u4eba\u5458";bTimerActions(4,a,b)});$("#alarmFlowName").click(function(a){a.target.title=
"\u9009\u62e9\u8981\u53d1\u8d77\u7684\u9884\u8b66\u6d41\u7a0b";bTimerActions(5,a,b)});$("#DalarmFlowDoingUsers").click(function(a){a.target.title="\u5176\u4ed6\u529e\u7406\u4eba\u5458";bTimerActions(6,a,b)});$("input[name=dueTime], input[name=dueFrequency]").blur(function(){!1==bIsDigital(this.value,1,"\u8bf7\u8f93\u5165\u6570\u5b57!")&&(this.value="1",$(this).trigger("focus"))});$("#DdueUsers").click(function(a){a.target.title="\u5176\u4ed6\u6d88\u606f\u901a\u77e5\u4eba\u5458";bTimerActions(7,a,
b)});$("#DdueToUsers").click(function(a){a.target.title="\u9009\u62e9\u79fb\u4ea4\u4eba\u5458";bTimerActions(8,a,b)});$("#DdueToTask").click(function(a){a.target.title="\u9009\u62e9\u8f6c\u529e\u73af\u8282";bTimerActions(9,a,b)});$("#dueFlowName").click(function(a){a.target.title="\u9009\u62e9\u8981\u53d1\u8d77\u7684\u50ac\u529e\u6d41\u7a0b";bTimerActions(10,a,b)});$("#DdueFlowDoingUsers").click(function(a){a.target.title="\u5176\u4ed6\u529e\u7406\u4eba\u5458";bTimerActions(11,a,b)});$("#alarmObjects_Other").change(function(){"checked"===
$(this).attr("checked")?$("#ID_AlarmOtherUser").show():$("#ID_AlarmOtherUser").hide()}).trigger("change");$("#alarmFlowDoings_Other").change(function(){"checked"===$(this).attr("checked")?$("#ID_AlarmFlowDoing").show():$("#ID_AlarmFlowDoing").hide()}).trigger("change");$("#dueObjects_Other").change(function(){"checked"===$(this).attr("checked")?$("#ID_DueToOtherUser").show():$("#ID_DueToOtherUser").hide()}).trigger("change");$("#dueFlowDoings_Other").change(function(){"checked"===$(this).attr("checked")?
$("#ID_DueFlowDoing").show():$("#ID_DueFlowDoing").hide()}).trigger("change");$("#dueObjects_Doing").change(function(){"checked"===$(this).attr("checked")?$("#ID_DueMsgToDoing").show():$("#ID_DueMsgToDoing").hide()}).trigger("change");$("select[name=dueAction]").change(function(){"4"==this.value?$("#ID_DueToUser").show():$("#ID_DueToUser").hide();"16"==this.value?$("#ID_DueToTask").show():$("#ID_DueToTask").hide()}).trigger("change")}
function TimerOKCheck(b,d){var a=$("#timerForm")[0],c="";null!=b&&null!=b.selectSingleNode("name")&&(c=b.selectSingleNode("name").text());return""==a.name.value?(alert("\u8bf7\u8f93\u5165\u540d\u79f0!"),!1):-1!=(";"+d.Names+";").indexOf(";"+a.name.value+";")&&a.name.value!=c?(alert("\u540d\u79f0\u5df2\u5b58\u5728\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165!"),a.name.focus(),!1):"1"==a.limitTimeType.value&&""==a.limitTime1.value||"2"==a.limitTimeType.value&&""==a.limitTime.value?(alert("\u8bf7\u8f93\u5165\u529e\u7406\u65f6\u9650!"),
!1):""!=a.Ddutys.value&&""==a.Dtasks.value?(alert("\u8bf7\u6307\u5b9a\u8ba1\u65f6\u73af\u8282!"),!1):!0}
function TimerOKEvent(b){var d=$("#timerForm")[0];if(null==b){b=$(goWorkFlow.xmlDOM.createElement("timer"));var a=goWorkFlow.flowXML.selectSingleNode("timers");a.appendChild(b)}oSetElement(b,"name",d.name.value);bSetXMLFieldValue(b,"tasks",""!=d.tasks.value?d.tasks.value.split(";"):null);for(var a=["alarmObjects","alarmFlowDoings","dueObjects","dueFlowDoings"],c=0;c<a.length;c++){var e=sGetFormFieldValue(d,a[c]);bSetXMLFieldValue(b,a[c],""!=e?e.split(";"):null)}a=oSetElement(b,"alarmFlow");oSetElement(a,
"name",d.alarmFlowName.value);oSetElement(a,"id",d.alarmFlowID.value);a=oSetElement(b,"dueFlow");oSetElement(a,"name",d.dueFlowName.value);oSetElement(a,"id",d.dueFlowID.value);a="duty alarmUser alarmFlowDoingUser dueUser dueToUser dueFlowDoingUser".split(" ");for(c=0;c<a.length;c++)bSetUnitFieldToXML(b,d,a[c]);a="name limitTimeType limitTime1 limitTime limitUnit affectMainFlow enableAlarm enableDueDoing alarmTime alarmUnit alarmFrequency dueTime dueUnit dueFrequency dueAction dueToTask".split(" ");
for(c=0;c<a.length;c++)oSetElement(b,a[c],sGetFormFieldValue(d,a[c]));return d.name.value}function aGetXMLFieldValue(b,d){var a=b.selectSingleNode(d);if(null==a)return null;var c=[],a=a.selectNodes("unit");if(null==a)return c;a.each(function(){c.push($(this).text())});return 0<c.length?c:null}
function aSetButtonRight(b,d,a){d=goWorkFlow.dictionXML.selectNodes(d);if(null!=d&&0!=d.length)for(var c=0;c<d.length;c++){var e=$(d[c]).selectSingleNode("value").text(),f=!1;if(null==a)"1"==$(d[c]).selectSingleNode("isDefault").text()&&(f=!0);else{for(var g=0;g<a.length&&e!=a[g];g++);g<a.length&&(f=!0)}!0==f&&bAddEntry(b,$(d[c]).selectSingleNode("name").text(),e,!0)}}
function bShowHideUntread(){-1!=(";"+sGetAllEntryValue(goForm.DTaskRight)+";").toLowerCase().indexOf(";untread;")?(ID_UntreadType.style.display="",ID_Untread.style.display="3"==goForm.untreadType.value?"":"none"):(ID_UntreadType.style.display="none",ID_Untread.style.display="none");return!0}function bGetForm(){var b=goWorkFlow.flowXML.selectSingleNode("./property/formID");return null!=b?b.text():""}
function bEmptyValue(b){b.DUnits.value="";b.Units.value="";b.FieldLabels.value="";b.Fields.value="";if(b.Tasks)if(null!=b.Tasks.length&&0<b.Tasks.length)for(var d=0;d<b.Tasks.length;d++)b.Tasks[d].checked=!1;else b.Tasks.checked=!1;if(b.Directions)if(null!=b.Directions.length&&0<b.Directions.length)for(d=0;d<b.Directions.length;d++)b.Directions[d].checked=!1;else b.Directions.checked=!1;for(d=0;d<b.UserOptions.length;d++)b.UserOptions[d].checked=!1}
function SelectUserOKEvent(b,d){var a=[],c=d.Style;if(-1!=c.indexOf("unit")){var e=[];e.push(b.DUnits.value);e.push(b.Units.value);a.unit=e}-1!=c.indexOf("bizRole")&&(e=[],e.push(b.DBizRoles.value),e.push(b.BizRoles.value),a.bizRole=e);-1!=c.indexOf("field")&&(a.field=b.Fields.value);-1!=c.indexOf("task")&&(a.task=sGetFormFieldValue(b,"Tasks"));-1!=c.indexOf("option")&&(a.option=sGetFormFieldValue(b,"UserOptions"));-1!=c.indexOf("direction")&&(a.direction=sGetFormFieldValue(b,"Directions"));return a}
function SelectUserLoadEvent(b){var d=$("#userSelectForm")[0],a=b.Style;-1!=a.indexOf("unit")?$("#ID_Unit").show():$("#ID_Unit").hide();-1!=a.indexOf("bizRole")?$("#ID_Biz_Role").show():$("#ID_Biz_Role").hide();-1!=a.indexOf("field")?$("#ID_Field").show():$("#ID_Field").hide();-1!=a.indexOf("task")?$("#ID_Task").show():$("#ID_Task").hide();-1!=a.indexOf("direction")?$("#ID_Direction").show():$("#ID_Direction").hide();-1!=a.indexOf("option")?$("#ID_Option_0").show():$("#ID_Option_0").hide();-1!=a.indexOf("option")?
$("#ID_Option_1").show():$("#ID_Option_1").hide();-1!=a.indexOf("task")&&-1==a.indexOf("unit")?$("#ID_TaskList").height($("#ID_TaskList").scrollTop()+100):$("#ID_TaskList").css("height",100);-1!=a.indexOf("direction")&&-1==a.indexOf("unit")&&$("#ID_DirectionList").height($("#ID_DirectionList").scrollTop()+140);var c=b.Tasks;if(null!=c){for(var e="",f=!0==b.MulTask?"checkbox":"radio",g=0;g<c.length;g++)a=c[g].split("|"),e+='<INPUT TYPE="'+f+'" class="AutoSize" NAME="Tasks" VALUE="'+a[1]+'" id="tasks_'+
g+'"><label for="tasks_'+g+'">'+a[0]+"</label><br>";$("#ID_TaskList").html(e)}c=b.Directions;if(null!=c){e="";for(g=0;g<c.length;g++)a=c[g].split("|"),f=a[3]+"|"+a[5],e+='<INPUT TYPE=checkbox class="AutoSize" NAME="Directions" VALUE="'+f+'" id="directions_'+g+'"><label for="directions_'+g+'">'+(a[0]+"("+a[2]+"-"+a[4]+")")+"</label><br>";$("#ID_DirectionList").html(e)}a=b.unit;null!=a&&($("#DUnits").val(a[0]),$("#Units").val(a[1]));e=b.bizRole;null!=a&&($("#DBizRoles").val(e[0]),$("#BizRoles").val(e[1]));
f=b.field;d.Fields.value=f;f=b.task;d.Tasks&&null!=f&&bSetFormFieldValue(d,"Tasks",f);f=b.option;null!=f&&bSetFormFieldValue(d,"UserOptions",f);f=b.direction;d.Directions&&null!=f&&bSetFormFieldValue(d,"Directions",f)}
function SelectUserInitEvent(){var b=$("#userSelectForm")[0];$("#DUnits").click(function(){$.unit.open({initNames:b.DUnits.value,initIDs:b.Units.value,title:"\u4eba\u5458\u9009\u62e9",multiple:!0,selectType:6,nameType:"21",showType:!0,type:"MyUnit",loginStatus:!1,excludeValues:null,afterSelect:function(a){null!=a&&(b.DUnits.value=a.name,b.Units.value=a.id)}})});$("#DBizRoles").comboTree({labelField:"DBizRoles",valueField:"BizRoles",autoInitValue:!1,treeSetting:{async:{otherParam:{serviceName:"flowSchemeService",
methodName:"getBizRoles",data:[]}}},width:488,height:220});var d={async:{otherParam:{serviceName:"flowSchemeService",methodName:"getFormFields",data:bGetForm()}}};$("#FieldLabels").comboTree({labelField:"FieldLabels",valueField:"Fields",initService:"flowSchemeService.getFormFieldByFieldNames",initServiceParam:[bGetForm()],treeSetting:d,width:488,height:220})}
function sGetAllEntryValue(b,d,a){var c="";a=null!=a&&""!=a?a:";";for(var e=0;e<b.options.length;e++)""!=b.options[e].value&&(!0==d&&!1==b.options[e].selected||(c=""==c?b.options[e].value:c+(a+b.options[e].value)));return c}
function bMoveEntry(b,d){var a=0,c,e;if(0==b.length||-1==b.selectedIndex)return!1;if(null!=d)for(var a=d.options.length,f=0;f<b.options.length;f++)!1!=b.options[f].selected&&(c=b.options[f].text,e=b.options[f].value,"00000"==e||""==e||(c=new Option(c,e),1==d.options.length&&""==d.options[0].text?d.options[0]=c:(d.options[a]=c,a++)));a=-1;for(f=b.options.length-1;0<=f;f--)if(!1!=b.options[f].selected&&!("00000"==b.options[f].value||""==b.options[f].value))b.options[f]=null,a=f;-1<a&&a<b.options.length?
b.options[a].selected=!0:0<b.options.length&&(b.options[b.options.length-1].selected=!0)}function bAddEntry(b,d,a,c){if(null==b||null==d||null==a)return!1;d=new Option(d,a);1==b.options.length&&""==b.options[0].text?b.options[0]=d:b.options[b.options.length]=d;!0!=c&&(b.selectedIndex=b.options.length-1);return!0}
function bInsertEntry(b,d,a){if(null==b||null==d||null==a)return!1;if(-1==b.selectedIndex)return bAddEntry(b,d,a);var c=b.options.length,e=b.selectedIndex;for(b.options[c]=new Option("","");c>e;c--)b.options[c].text=b.options[c-1].text,b.options[c].value=b.options[c-1].value;b.options[c].text=d;b.options[c].value=a;return!0}
function bEditEntry(b,d,a){if(null==b||(null==d||null==a)||0==b.length||-1==b.selectedIndex)return!1;new Option(d,a);var c=b.selectedIndex;b.options[c].text=d;b.options[c].value=a;b.selectedIndex=c;return!0}function bSetXMLFieldValue(b,d,a){var c=b.selectSingleNode(d);null!=c&&b.removeChild(c);c=oAddElement(b,d);if(null!=a)for(b=0;b<a.length;b++)oAddElement(c,"unit",a[b]).setAttribute("type","32");return!0}
function bSetUnitFieldToXML(b,d,a){var c=b.selectSingleNode(a+"s");null!=c&&0!=c.length&&b.removeChild(c);var c=oAddElement(b,a+"s"),e=d["D"+a+"1"];b=d[a+"1"];if(null!=e&&""!=e.value&&null!=b&&""!=b.value){var f=e.value.split(";"),g=b.value.split(";");for(b=0;b<f.length;b++)e=oAddElement(c,"unit"),e.setAttribute("type","1"),oAddElement(e,"value",g[b]),oAddElement(e,"argValue",f[b])}e=d["D"+a+"16"];b=d[a+"16"];if(null!=e&&""!=e.value&&null!=b&&""!=b.value){f=e.value.split(";");g=b.value.split(";");
for(b=0;b<f.length;b++)e=oAddElement(c,"unit"),e.setAttribute("type","16"),oAddElement(e,"value",g[b]),oAddElement(e,"argValue",f[b])}f=["2","4","8"];for(g=0;g<f.length;g++)if(b=d[a+f[g]],null!=b&&""!=b.value){var j=b.value.split(";");for(b=0;b<j.length;b++)e=oAddElement(c,"unit"),e.setAttribute("type",f[g]),oAddElement(e,"value",j[b])}return!0}
function bGetUnitXMLToField(b,d,a){b=b.selectSingleNode(a+"s");if(null==b)return!1;var c=b.selectNodes("unit");if(null==c||0==c.length)return!1;b=[];for(var e=[],f=[],g=[],j=[],k=[],h=[],l=[],n=0;n<c.length;n++)switch(c[n].getAttribute("type")){case "1":e.push($(c[n]).selectSingleNode("argValue").text());f.push($(c[n]).selectSingleNode("value").text());b.push($(c[n]).selectSingleNode("argValue").text());break;case "2":var p=$(c[n]).selectSingleNode("value").text();g.push(p);b.push("{"+p+"}");break;
case "4":p=$(c[n]).selectSingleNode("value").text();j.push(p);p=sGetTaskNameByID(p);b.push("<"+p+">");break;case "8":p=$(c[n]).selectSingleNode("value").text();k.push(p);b.push("["+p+"]");break;case "16":h.push($(c[n]).selectSingleNode("argValue").text()),l.push($(c[n]).selectSingleNode("value").text()),b.push($(c[n]).selectSingleNode("argValue").text())}c=d["D"+a+"s"];null!=c&&(c.value=b.join(";"));c=d["D"+a+"1"];null!=c&&(c.value=e.join(";"));c=d[a+"1"];null!=c&&(c.value=f.join(";"));c=d["D"+a+
"16"];null!=c&&(c.value=h.join(";"));c=d[a+"16"];null!=c&&(c.value=l.join(";"));c=d[a+"2"];null!=c&&(c.value=g.join(";"));c=d[a+"4"];null!=c&&(c.value=j.join(";"));c=d[a+"8"];null!=c&&(c.value=k.join(";"));return!0}
function bIsDigital(){var b=bIsDigital.arguments;if(1>b.length)return!1;var d=b[0],a=1<b.length?b[1]:3,b=2<b.length?b[2]:sGetLang("P_NOTDIGITAL");if(""==d+"")return""!=b&&alert(b),!1;var c=/^[+-]?(0|([1-9]\d*))$/,e=/^[+-]?(0|([1-9]\d*))\.\d+$/,f=/^[+-]?(((0|([1-9]\d*)))|((0|([1-9]\d*))\.\d+))$/,g=/^[+]?[1-9]\d*$/,j=/^\-[1-9]\d*$/,k=/^[+]?(([1-9]\d*\.\d+)|(0\.\d*[1-9]\d*))$/,h=/^\-(([1-9]\d*\.\d+)|(0\.\d*[1-9]\d*))$/,l=/^[+]?(([1-9]\d*)|([1-9]\d*\.\d+)|(0\.\d*[1-9]\d*))$/,n=/^\-(([1-9]\d*)|([1-9]\d*\.\d+)|(0\.\d*[1-9]\d*))$/,
p=/^(([+-]?0)|([+]?[1-9]\d*))$/,r=/^(([+-]?0)|(\-[1-9]\d*))$/,t=/^(([+]?(([1-9]\d*\.\d+)|(0\.\d+)))|([+-]?0\.[0]+))$/,m=/^((\-(([1-9]\d*\.\d+)|(0\.\d+)))|([+-]?0\.[0]+))$/,u=/^(([+-]?0)|([+]?[1-9]\d*)|([+]?(0|([1-9]\d*))\.\d+)|([+-]?0\.[0]+))$/,v=/^(([+-]?0)|(\-[1-9]\d*)|(\-(0|([1-9]\d*))\.\d+)|([+-]?0\.[0]+))$/,q=!0;1==a&&null==d.match(c)?q=!1:2==a&&null==d.match(e)?q=!1:3==a&&null==d.match(f)?q=!1:4==a&&null==d.match(g)?q=!1:-4==a&&null==d.match(j)?q=!1:5==a&&null==d.match(k)?q=!1:-5==a&&null==
d.match(h)?q=!1:6==a&&null==d.match(l)?q=!1:-6==a&&null==d.match(n)?q=!1:7==a&&null==d.match(p)?q=!1:-7==a&&null==d.match(r)?q=!1:8==a&&null==d.match(t)?q=!1:-8==a&&null==d.match(m)?q=!1:9==a&&null==d.match(u)?q=!1:-9==a&&null==d.match(v)&&(q=!1);!q&&""!=b&&alert(b);return q}function onGetFormFields(b,d,a){$.each(a,function(){var a='<option value="'+this.data+'">'+this.name+"</option>";$(b,d).append(a)})}
function showToolMsg(){var b=goSelectedTool.innerHTML,b=b.substring(b.indexOf("ico_")+4,b.indexOf(".gif"));goSelectedTool.Type=b.toUpperCase();switch(goSelectedTool.Type){case "BEELINE":b=sGetLang("FLOW_WF_BEELINE_NAME");break;case "CURVE":b=sGetLang("FLOW_WF_CURVE_NAME");break;case "TASK":b=sGetLang("FLOW_WF_TASK_NAME");break;case "SUBFLOW":b=sGetLang("FLOW_WF_SUBFLOW_NAME");break;case "FREETASK":b=sGetLang("FLOW_WF_FREETASK_NAME");break;case "CONDITION":b=sGetLang("FLOW_WF_CONDITION_NAME");break;
case "BEGIN":b=sGetLang("FLOW_WF_BEGIN_NAME");break;case "END":b=sGetLang("FLOW_WF_END_NAME");break;case "LABEL":b=sGetLang("FLOW_WF_LABEL_NAME");break;default:showMsg("");return}showMsg(sGetLang("FLOW_WF_ADDOBJECT")+b)}function showMsg(b,d){!0==d?$("#ID_MESSAGE").html("<span style='color:red'>"+b+"</span>"):$("#ID_MESSAGE").html(b)};
