var goWorkFlow={cursorX:0,cursorY:0,curAddObject:null,curObjectName:null,tasks:[],lines:[],eWFJG:null,fromObject:null,curOverObjName:null,selectTasks:[],selectObjects:[],copyObject:null,curStatus:null,isShowLineName:!0,isShowLabel:!0,dynamicTask:[],intervalName:null,intervalIndex:0,selected:!1,xmlDOM:null,dictionXML:null,flowXML:null,flowTreeXML:null,equalFlowID:null,equalFlowXML:null,historyXML:null};function checkKey(){return!0}
function bindMenu(){$("#menu_save",parent.document).click(function(b){$("#btn_save",parent.document).trigger("click");saveWorkFlow();b.stopPropagation()});$("#menu_save_version",parent.document).click(function(b){$("#btn_save",parent.document).trigger("click");saveWorkFlow(!0);b.stopPropagation()});$("#menu_clear",parent.document).click(function(b){parent.clearObject=!0;location.reload();b.stopPropagation()});$("#menu_grid",parent.document).toggle(function(b){$(".WORKBODY").addClass("WORKBODYBACKIMAGE");
$(".WORKBODY").removeClass("WORKBODY");b.stopPropagation()},function(b){$(".WORKBODYBACKIMAGE").addClass("WORKBODY");$(".WORKBODYBACKIMAGE").removeClass("WORKBODYBACKIMAGE");b.stopPropagation()});$("#menu_up",parent.document).click(function(b){moveCanvas("up");b.stopPropagation()});$("#menu_down",parent.document).click(function(b){moveCanvas("down");b.stopPropagation()});$("#menu_left",parent.document).click(function(b){moveCanvas("left");b.stopPropagation()});$("#menu_right",parent.document).click(function(b){moveCanvas("right");
b.stopPropagation()})}
function loadEvent(){bindMenu();goWorkFlow.eWFJG=new jsGraphics("ID_WORKAROUND");$("IMG").hide();goWorkFlow.xmlDOM=oGetXMLDocument_();if(-1!=parent.location.href.indexOf("id=")){var b=decodeURI(parent.location.href.substr(parent.location.href.indexOf("id=")+3));parentPromptDoing_("<NEW>"!=b?parent.sGetLang("FLOW_WF_LOADING"):"");$.ajax({url:"scheme/diction/xml.action?open",type:"GET",dataType:"xml",cache:!1,error:function(){},success:function(a){goWorkFlow.dictionXML=$(a).selectSingleNode("diction");"<NEW>"!=
b&&!0!=parent.clearObject?$.ajax({url:"scheme/flow/xml.action?open&id="+b,type:"GET",dataType:"xml",cache:!1,error:function(){},success:function(a){goWorkFlow.flowXML=$(a).selectSingleNode("flow");null!=goWorkFlow.flowXML?bLoadObject():showMsg(parent.sGetLang("FLOW_WF_ERRORDOWNLOAD"),!0);$(document).trigger("dblclick")}}):(goWorkFlow.xmlDOM=$.parseXML("<flow><property></property><timers /><tasks></tasks><directions></directions><labels /><deletes /></flow>"),goWorkFlow.flowXML=$(goWorkFlow.xmlDOM).selectSingleNode("flow"),
showMsg(""),$(document).trigger("dblclick"));parent.HideDoing_()}})}}function mouseOver(){getSelectObject();"CURVE"==goWorkFlow.curAddObject&&(null!=goWorkFlow.fromObject&&null==goWorkFlow.fromObject.cursorWay)&&(goWorkFlow.fromObject=null);return!0}function mouseOut(){"object"==typeof ID_BROKENCURVE&&$("#ID_BROKENCURVE").remove();"object"==typeof ID_BROKENBEELINE&&$("#ID_BROKENBEELINE").remove();return!0}
function mouseDown(){!1==goWorkFlow.selected?(bSetObjectStatus(goWorkFlow.curObjectName,!1),bShowTasks(null,!1),bShowErrorObject(!1)):goWorkFlow.selected=!0}function mouseUp(){}
function mouseMove(b){if(null!=goWorkFlow.curOverObjName&&("BEELINE"==goWorkFlow.curAddObject||"CURVE"==goWorkFlow.curAddObject)){var a=oGetTaskObject(goWorkFlow.curOverObjName);if(null!=a&&"LABEL"!=a.Type){getCursorPosition(b);var c=a.imgObject;if(goWorkFlow.cursorX>=c.x&&goWorkFlow.cursorX<=c.x+c.w&&goWorkFlow.cursorY>=c.y&&goWorkFlow.cursorY<=c.y+c.h)if("CURVE"==goWorkFlow.curAddObject){var d=sGetTaskCurveWay(a,goWorkFlow.cursorX,goWorkFlow.cursorY);a.cursorWay=d;null==goWorkFlow.fromObject?c.setCursor("images/cur_"+
d+"From.cur"):c.setCursor("images/cur_"+d+"To.cur")}else null==goWorkFlow.fromObject?c.setCursor("images/cur_BeelineFrom.cur"):c.setCursor("images/cur_BeelineTo.cur")}}if(null!=goWorkFlow.fromObject&&("BEELINE"==goWorkFlow.curAddObject||"CURVE"==goWorkFlow.curAddObject))getCursorPosition(b),"BEELINE"==goWorkFlow.curAddObject?bDrawBrokenBeeline():bDrawBrokenCurve();return!0}
function mouseClick(b){if(2===b.button)return bSetObjectStatus(goWorkFlow.curObjectName,!1),!0;!1==goWorkFlow.selected?(bSetObjectStatus(goWorkFlow.curObjectName,!1),!0!=bSetLabelHTML()&&(showCursorPosition(b),null==goWorkFlow.curOverObjName&&(null!=goWorkFlow.curAddObject&&"DEFAULT"!=goWorkFlow.curAddObject&&"BEELINE"!=goWorkFlow.curAddObject&&"CURVE"!=goWorkFlow.curAddObject)&&(b=oCreateTask(goWorkFlow.curAddObject,goWorkFlow.cursorX,goWorkFlow.cursorY),"LABEL"!=goWorkFlow.curAddObject&&bAdjustObject(b),
oCreateXMLNode(b),bSetObjectText(b)))):goWorkFlow.selected=!1}
function mouseDblClick(b){b=b.target;if("DIV"==b.tagName&&"LINE"==b.Type&&null!=b.parentElement&&"SPAN"==b.parentElement.tagName)return setDirectionProperty(),!1;for(;null!=b&&!(null!=b.id&&0==b.id.indexOf("img_")&&-1!=b.id.indexOf("div"));)b=b.parentElement;if(null!=b)return-1!=b.id.indexOf("img_label")?bShowLabelInput():-1!=b.id.indexOf("img_line")?(-1!=goWorkFlow.curObjectName.indexOf("img_line")&&(b=oGetLineObjectByLabel(goWorkFlow.curObjectName),null!=b&&(goWorkFlow.curObjectName=b.name)),setDirectionProperty()):
null!=goWorkFlow.historyXML?showTaskHistory():setTaskProperty(),!1;null!=goWorkFlow.historyXML?showFlowHistory():setFlowProperty()}
function contextMenu(b){bSetObjectStatus(goWorkFlow.curObjectName,!1);var a=b.target;if("DIV"==a.tagName&&"LINE"==a.Type&&null!=a.parentElement&&"SPAN"==a.parentElement.tagName){goWorkFlow.curObjectName=a.parentElement.id;bSetObjectStatus(goWorkFlow.curObjectName,!0);if(null!=a.parentElement.Type){var c=oGetLineObject(goWorkFlow.curObjectName);b=parent.document.getElementsByName("ID_MENU_DIRECTION");for(var d=0;d<b.length;d++)b[d].disabled=-1!=b[d].outerHTML.toLowerCase().indexOf(a.parentElement.Type.toLowerCase())?
!0:-1!=b[d].outerHTML.toLowerCase().indexOf("showlinename")?-1!=b[d].outerHTML.toLowerCase().indexOf("("+c.isShowName+",")?!0:!1:null!=b[d].status&&"disable"==b[d].status?!0:!1}return!1}for(;null!=a&&!(null!=a.id&&0==a.id.indexOf("img_")&&-1!=a.id.indexOf("div"));)a=a.parentElement;if(null!=a){a=a.id.substr(0,a.id.indexOf("div"));goWorkFlow.curObjectName=a;bSetObjectStatus(goWorkFlow.curObjectName,!0);if(-1==a.indexOf("img_label"))if(-1!=a.indexOf("img_line")){c=oGetLineObjectByLabel(a);goWorkFlow.curObjectName=
c.name;bSetObjectStatus(goWorkFlow.curObjectName,!0);b=parent.document.getElementsByName("ID_MENU_DIRECTION");for(d=0;d<b.length;d++)b[d].disabled=-1!=b[d].outerHTML.toLowerCase().indexOf(c.Type.toLowerCase())?!0:-1!=b[d].outerHTML.toLowerCase().indexOf("showlinename")?-1!=b[d].outerHTML.toLowerCase().indexOf("("+c.isShowName+",")?!0:!1:null!=b[d].status&&"disable"==b[d].status?!0:!1}else{b=parent.document.getElementsByName("ID_MENU_TASK");for(d=0;d<b.length;d++)-1!=b[d].outerHTML.toLowerCase().indexOf("settaskproperty")?
b[d].disabled=-1!=a.indexOf("img_begin")||-1!=a.indexOf("img_end")?!0:!1:-1!=b[d].outerHTML.toLowerCase().indexOf("before")?b[d].disabled=-1!=a.indexOf("img_begin")?!0:!1:-1!=b[d].outerHTML.toLowerCase().indexOf("after")&&(b[d].disabled=-1!=a.indexOf("img_end")?!0:!1)}return!1}if(null!=goWorkFlow.curAddObject&&"DEFAULT"!=goWorkFlow.curAddObject){if(null!=goWorkFlow.fromObject&&("BEELINE"==goWorkFlow.curAddObject||"CURVE"==goWorkFlow.curAddObject))return goWorkFlow.fromObject=null,"object"==typeof ID_BROKENBEELINE&&
(document.all.ID_BROKENBEELINE.outerHTML=""),"object"==typeof ID_BROKENCURVE&&(document.all.ID_BROKENCURVE.outerHTML=""),!1;setSelectObject("DEFAULT");getSelectObject()}else{b=$("#ID_MENU_FLOW",parent.document);for(d=0;d<b.length;d++)if(-1!=b[d].outerHTML.toLowerCase().indexOf("paste")){b[d].disabled=null==goWorkFlow.copyObject?!0:!1;break}}return!1}
function my_PickFunc(){bSetObjectStatus(goWorkFlow.curObjectName,!1);bShowTasks(null,!1);bShowErrorObject(!1);bSetLabelHTML();var b=dd.obj.name;if(-1!=b.indexOf("img_line")){var a=oGetLineObjectByLabel(b);null!=a&&(b=a.name)}bSetObjectStatus(b,!0);if(-1==dd.obj.name.indexOf("img_label")&&-1==dd.obj.name.indexOf("img_line")&&("BEELINE"==goWorkFlow.curAddObject||"CURVE"==goWorkFlow.curAddObject))null==goWorkFlow.fromObject?goWorkFlow.fromObject=oGetTaskObject(dd.obj.name):(b=oGetTaskObject(dd.obj.name),
"BEELINE"==goWorkFlow.curAddObject?("object"==typeof ID_BROKENBEELINE&&(document.all.ID_BROKENBEELINE.outerHTML=""),a=oCreateBeeline(goWorkFlow.fromObject,b)):("object"==typeof ID_BROKENCURVE&&(document.all.ID_BROKENCURVE.outerHTML=""),a=oCreateCurve(goWorkFlow.fromObject,b)),null!=oCreateXMLNode(a)&&bSetObjectText(a.labelObject),goWorkFlow.fromObject=null)}
function my_DragFunc(){if(-1==dd.obj.name.indexOf("img_label")&&-1==dd.obj.name.indexOf("img_line")){for(var b=oGetTaskObject(dd.obj.name),a=0;a<b.outLines.length;a++)null!=b.outLines[a]&&("BEELINE"==b.outLines[a].Type?oCreateBeeline(b,b.outLines[a].toTask,null,b.outLines[a]):oCreateCurve(b,b.outLines[a].toTask,null,b.outLines[a]));for(a=0;a<b.inLines.length;a++)null!=b.inLines[a]&&("BEELINE"==b.inLines[a].Type?oCreateBeeline(b.inLines[a].fromTask,b,null,b.inLines[a]):oCreateCurve(b.inLines[a].fromTask,
b,null,b.inLines[a]))}}function my_ResizeFunc(){}
function my_DropFunc(){if(-1==dd.obj.name.indexOf("img_label")&&-1==dd.obj.name.indexOf("img_line")){var b=oGetTaskObject(dd.obj.name);bAdjustObject(b);for(var a=0;a<b.outLines.length;a++)null!=b.outLines[a]&&("BEELINE"==b.outLines[a].Type?oCreateBeeline(b,b.outLines[a].toTask,null,b.outLines[a]):oCreateCurve(b,b.outLines[a].toTask,null,b.outLines[a]));for(a=0;a<b.inLines.length;a++)null!=b.inLines[a]&&("BEELINE"==b.inLines[a].Type?oCreateBeeline(b.inLines[a].fromTask,b,null,b.inLines[a]):oCreateCurve(b.inLines[a].fromTask,
b,null,b.inLines[a]))}}function my_OverFunc(b){goWorkFlow.curOverObjName=b}function my_OutFunc(b){goWorkFlow.curOverObjName=null;b=oGetTaskObject(b);null!=b&&b.imgObject.setCursor("images/cur_move.cur")}function getCursorPosition(b){goWorkFlow.cursorX=b.pageX;goWorkFlow.cursorY=b.pageY}
function getSelectObject(){goWorkFlow.curAddObject=null!=parent.goSelectedTool?parent.goSelectedTool.Type:null;ID_WORKAROUND.style.cursor=null==goWorkFlow.curAddObject||"DEFAULT"==goWorkFlow.curAddObject?"images/cur_Default.cur":"BEELINE"==goWorkFlow.curAddObject||"CURVE"==goWorkFlow.curAddObject?"images/cur_Line.cur":"LABEL"==goWorkFlow.curAddObject?"images/cur_Label.cur":"images/cur_Node.cur"}
function setSelectObject(b){goWorkFlow.curAddObject=b;if(null!=parent.goSelectedTool&&null!=b){for(var a=0;a<parent.gaTools.length;a++)-1!=parent.gaTools[a].innerHTML.indexOf("_"+b.toLowerCase()+".")?(parent.goSelectedTool=parent.gaTools[a],parent.goSelectedTool.Type=b,parent.gaTools[a].className="ToolInset"):parent.gaTools[a].className="ToolBar";parent.showToolMsg()}}
function showCursorPosition(b){getCursorPosition(b);b=goWorkFlow.cursorX+"px,"+goWorkFlow.cursorY+"px";$("#ID_Position",parent.document).text(b)}function showMsg(b,a){!0==a?$("#ID_MESSAGE",parent.document).html("<span style='color:red'>"+b+"</span>"):$("#ID_MESSAGE",parent.document).html(b)}
function parentPromptDoing_(b){showMsg(b);$("#ID_PromptDoing",parent.window.document).html('<div id="hCover" style="position:absolute; top:0; left:0; z-index:9; visibility:visible;"><TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 style="width:100%;height:1000;background-color: transparent; "><TR><TD style="background-color: transparent; "></td></tr></table></div>');$("#ID_PromptDoing",parent.window.document).show()}
function getAdjustXY(b){var a=Math.ceil(b/40);return 40*a==b?b:b<=40*(a-1)+20?40*(a-1):40*a}function bAdjustObject(b){var a=getAdjustXY(b.imgObject.x),c=getAdjustXY(b.imgObject.y);b.imgObject.moveTo(a+40-b.imgObject.w/2,c+20-b.imgObject.h/2)}function oGetTaskObject(b){for(var a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a]&&goWorkFlow.tasks[a].name==b)return goWorkFlow.tasks[a];return null}
function oGetTaskObjectByPropertyName(b){for(var a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a]&&"LABEL"!=goWorkFlow.tasks[a].Type&&null!=goWorkFlow.tasks[a].xmlObject&&goWorkFlow.tasks[a].xmlObject.getAttribute("name")==b)return goWorkFlow.tasks[a];return null}
function oGetTaskObjectByPropertyID(b){for(var a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a]&&"LABEL"!=goWorkFlow.tasks[a].Type&&null!=goWorkFlow.tasks[a].xmlObject&&goWorkFlow.tasks[a].xmlObject.getAttribute("id")==b)return goWorkFlow.tasks[a];return null}function sGetTaskNameByID(b){for(var a=null,c=aGetTasks("TASK/SUBFLOW",null,!0),d=0;d<c.length;d++){var f=c[d].split("|");if(f[1]==b){a=f[0];break}}return a}
function oGetConditionObjectByFromTaskName(b){b=oGetTaskObjectByPropertyName(b);if(null==b)return null;for(var a=0;a<b.outLines.length;a++)if(null!=b.outLines[a]&&null!=b.outLines[a].toTask&&"CONDITION"==b.outLines[a].toTask.Type)return b.outLines[a].toTask;return null}function oGetLineObject(b){for(var a=0;a<goWorkFlow.lines.length;a++)if(null!=goWorkFlow.lines[a]&&goWorkFlow.lines[a].name==b)return goWorkFlow.lines[a];return null}
function oGetLineObjectByLabel(b){for(var a=0;a<goWorkFlow.lines.length;a++)if(null!=goWorkFlow.lines[a]&&goWorkFlow.lines[a].labelObject.name==b)return goWorkFlow.lines[a];return null}function oGetLineObjectByPoint(b,a){if(null==b||null==a)return null;for(var c=0;c<goWorkFlow.lines.length;c++)if(null!=goWorkFlow.lines[c]&&!(goWorkFlow.lines[c].fromTask.name!=b.name||goWorkFlow.lines[c].toTask.name!=a.name))return goWorkFlow.lines[c];return null}
function oGetConditionObjectByFromTask(b){if(null==b)return null;for(var a=0;a<b.outLines.length;a++)if(null!=b.outLines[a]&&null!=b.outLines[a].toTask&&"CONDITION"==b.outLines[a].toTask.Type)return b.outLines[a].toTask;return null}function oGetEndTaskFromTask(b){if(null==b)return null;for(var a=0;a<b.outLines.length;a++)if(null!=b.outLines[a]&&null!=b.outLines[a].toTask&&"END"==b.outLines[a].toTask.Type)return b.outLines[a].toTask;return null}
function sGetRandom(b){for(var a,c="",d=0;d<b;d++)a=10*Math.random()+"",c+=a.substring(0,1);return c}function sGetNewName(b){var a=parent.sGetLang("FLOW_WF_"+b.Type+"_NAME"),c=a;if("TASK"==b.Type||"SUBFLOW"==b.Type||"CONDITION"==b.Type){b=1;do{for(var c=a+b,d=0;d<goWorkFlow.tasks.length&&!(null!=goWorkFlow.tasks[d]&&null!=goWorkFlow.tasks[d].xmlObject&&goWorkFlow.tasks[d].xmlObject.getAttribute("name")==c);d++);if(d>=goWorkFlow.tasks.length)break;b++}while(1)}return c}
function sGetNewFlowID(){var b;do return b="F"+sGetRandom(3);while(1)}function sGetNewTaskID(b){var a="TASK"==b.Type?"T":"S";do{b=a+sGetRandom(3);for(var c=0;c<goWorkFlow.tasks.length&&!(null!=goWorkFlow.tasks[c]&&null!=goWorkFlow.tasks[c].xmlObject&&goWorkFlow.tasks[c].xmlObject.getAttribute("id")==b);c++);if(c>=goWorkFlow.tasks.length)return b}while(1)}
function sGetNewDirectionID(){var b;do{b="D"+sGetRandom(3);for(var a=0;a<goWorkFlow.lines.length&&!(null!=goWorkFlow.lines[a]&&null!=goWorkFlow.lines[a].xmlObject&&goWorkFlow.lines[a].xmlObject.getAttribute("id")==b);a++);if(a>=goWorkFlow.lines.length)return b}while(1)}
function aGetArrow(b,a,c,d){var f,h,e,j,g=Math.atan(Math.abs(d-a)/Math.abs(c-b)),l=Math.round(10*Math.cos(Math.abs(Math.PI/9-g))),k=Math.round(10*Math.sin(Math.abs(Math.PI/9-g))),m=Math.round(10*Math.sin(Math.abs(7*Math.PI/18-g))),n=Math.round(10*Math.cos(Math.abs(7*Math.PI/18-g)));c>=b&&d>=a?(f=c-l,h=g<=Math.PI/9?d+k:d-k,e=g<=7*Math.PI/18?c-m:c+m,j=d-n):c<b&&d>=a?(f=c+l,h=g<=Math.PI/9?d+k:d-k,e=g<=7*Math.PI/18?c+m:c-m,j=d-n):c>=b&&d<a?(f=c-l,h=g<=Math.PI/9?d-k:d+k,e=g<=7*Math.PI/18?c-m:c+m,j=d+n):
c<b&&d<a&&(f=c+l,h=g<=Math.PI/9?d-k:d+k,e=g<=7*Math.PI/18?c+m:c-m,j=d+n);b=[];b[0]=f;b[1]=h;b[2]=e;b[3]=j;return b}function aGetLinePoint(b,a,c,d,f){var h=Math.atan(Math.abs(d-a)/Math.abs(c-b)),e=Math.round(f*Math.cos(h));f=Math.round(f*Math.sin(h));h=[];h[0]=c==b?c:c>b?c-e:c+e;h[1]=d==a?d:d>a?d-f:d+f;return h}
function aTaskBeelinePoint(b,a,c){var d=b.imgObject.x+b.imgObject.w/2,f=b.imgObject.y+b.imgObject.h/2,h=Math.atan(Math.abs(c-f)/Math.abs(a-d)),e=Math.atan(b.imgObject.h/b.imgObject.w),j=h<e?b.imgObject.w/2:Math.abs(a-d)*b.imgObject.h/2/Math.abs(c-f);b=h>e?b.imgObject.h/2:Math.abs(c-f)*b.imgObject.w/2/Math.abs(a-d);h=[];h[0]=a==d?d:a>d?d+j:d-j;h[1]=c==f?f:c>f?f+b:f-b;return h}
function aTaskCurvePoint(b,a,c,d){var f=b.imgObject.x,h=b.imgObject.y,e,j,g,l;if(null==c)switch(a){case "up":e=f+b.imgObject.w/2;j=h;break;case "down":e=f+b.imgObject.w/2;j=h+b.imgObject.h;break;case "left":e=f;j=h+b.imgObject.h/2;break;case "right":e=f+b.imgObject.w,j=h+b.imgObject.h/2}else if("up"==a||"down"==a){"up"==a?(a=b.upCurves,j=h):(a=b.downCurves,j=h+b.imgObject.h);g=b.imgObject.w/(a.length+1);Math.ceil(g)>g&&g--;for(var k=0;k<a.length;k++)if(a[k].name==c.name){e=f+g*(k+1);break}l=k;if(!0==
d)for(k=0;k<a.length;k++)d=a[k],null==d||d.name==c.name||(b.name==d.fromTask.name?(d.x1=f+g*(k+1),d.y1=j):(d.x2=f+g*(k+1),d.y2=j),bReDrawLine(d))}else if("left"==a||"right"==a){"left"==a?(a=b.leftCurves,e=f):(a=b.rightCurves,e=f+b.imgObject.w);g=b.imgObject.h/(a.length+1);Math.ceil(g)>g&&g--;for(k=0;k<a.length;k++)if(a[k].name==c.name){j=h+g*(k+1);break}l=k;if(!0==d)for(k=0;k<a.length;k++)d=a[k],null==d||d.name==c.name||(b.name==d.fromTask.name?(d.x1=e,d.y1=h+g*(k+1)):(d.x2=e,d.y2=h+g*(k+1)),bReDrawLine(d))}b=
[];b[0]=e;b[1]=j;b[2]=l;return b}
function aGetCurvePoint(b,a,c,d,f,h,e){var j=20;null!=e&&0<e&&(j+=10*e);e=[];var g=[];e[0]=b;g[0]=a;if(null==h)switch(e[3]=c,g[3]=d,f){case "up":e[1]=e[0];g[1]=(g[0]>g[3]?g[3]:g[0])-j;e[2]=e[3];g[2]=g[1];break;case "down":e[1]=e[0];g[1]=(g[0]<g[3]?g[3]:g[0])+j;e[2]=e[3];g[2]=g[1];break;case "left":e[1]=(e[0]>e[3]?e[3]:e[0])-j;g[1]=g[0];e[2]=e[1];g[2]=g[3];break;case "right":e[1]=(e[0]<e[3]?e[3]:e[0])+j,g[1]=g[0],e[2]=e[1],g[2]=g[3]}else{switch(f){case "up":switch(h){case "up":e[1]=e[0];g[1]=(g[0]>
d?d:g[0])-j;e[2]=c;g[2]=g[1];break;case "down":e[1]=e[0];g[1]=g[0]-j>(g[0]+d)/2?(g[0]+d)/2:g[0]-j;e[2]=(e[0]+c)/2;g[2]=g[1];e[3]=e[2];g[3]=d+j<(g[0]+d)/2?(g[0]+d)/2:d+j;e[4]=c;g[4]=g[3];break;case "left":e[1]=e[0];g[1]=g[0]-j>(g[0]+d)/2?(g[0]+d)/2:g[0]-j;e[2]=c-j>(e[0]+c)/2?(e[0]+c)/2:c-j;g[1]=e[2]>e[1]&&g[0]-j>d?d:g[1];g[2]=g[1];e[3]=e[2];g[3]=d;break;case "right":e[1]=e[0],g[1]=g[0]-j>(g[0]+d)/2?(g[0]+d)/2:g[0]-j,e[2]=c+j<(e[0]+c)/2?(e[0]+c)/2:c+j,g[1]=e[2]<e[1]&&g[0]-j>d?d:g[1],g[2]=g[1],e[3]=
e[2],g[3]=d}break;case "down":switch(h){case "up":e[1]=e[0];g[1]=g[0]+j<(g[0]+d)/2?(g[0]+d)/2:g[0]+j;e[2]=(e[0]+c)/2;g[2]=g[1];e[3]=e[2];g[3]=d-j>(g[0]+d)/2?(g[0]+d)/2:d-j;e[4]=c;g[4]=g[3];break;case "down":e[1]=e[0];g[1]=(g[0]<d?d:g[0])+j;e[2]=c;g[2]=g[1];break;case "left":e[1]=e[0];g[1]=g[0]+j<(g[0]+d)/2?(g[0]+d)/2:g[0]+j;e[2]=c-j>(e[0]+c)/2?(e[0]+c)/2:c-j;g[1]=e[2]>e[1]&&g[0]+j<d?d:g[1];g[2]=g[1];e[3]=e[2];g[3]=d;break;case "right":e[1]=e[0],g[1]=g[0]+j<(g[0]+d)/2?(g[0]+d)/2:g[0]+j,e[2]=c+j<(e[0]+
c)/2?(e[0]+c)/2:c+j,g[1]=e[2]<e[1]&&g[0]+j<d?d:g[1],g[2]=g[1],e[3]=e[2],g[3]=d}break;case "left":switch(h){case "up":e[1]=e[0]-j>(e[0]+c)/2?(e[0]+c)/2:e[0]-j;g[1]=g[0];g[2]=d-j>(g[0]+d)/2?(g[0]+d)/2:d-j;e[1]=g[2]>g[1]&&e[0]-j>c?c:e[1];e[2]=e[1];e[3]=c;g[3]=g[2];break;case "down":e[1]=e[0]-j>(e[0]+c)/2?(e[0]+c)/2:e[0]-j;g[1]=g[0];g[2]=d+j<(g[0]+d)/2?(g[0]+d)/2:d+j;e[1]=g[2]<g[1]&&e[0]-j>c?c:e[1];e[2]=e[1];e[3]=c;g[3]=g[2];break;case "left":e[1]=(e[0]>c?c:e[0])-j;g[1]=g[0];e[2]=e[1];g[2]=d;break;case "right":e[1]=
e[0]-j>(e[0]+c)/2?(e[0]+c)/2:e[0]-j,g[1]=g[0],e[2]=e[1],g[2]=(g[0]+d)/2,e[3]=c+j<(e[0]+c)/2?(e[0]+c)/2:c+j,g[3]=g[2],e[4]=e[3],g[4]=d}break;case "right":switch(h){case "up":e[1]=e[0]+j<(e[0]+c)/2?(e[0]+c)/2:e[0]+j;g[1]=g[0];g[2]=d-j>(g[0]+d)/2?(g[0]+d)/2:d-j;e[1]=g[2]>g[1]&&e[0]+j<c?c:e[1];e[2]=e[1];e[3]=c;g[3]=g[2];break;case "down":e[1]=e[0]+j<(e[0]+c)/2?(e[0]+c)/2:e[0]+j;g[1]=g[0];g[2]=d+j<(g[0]+d)/2?(g[0]+d)/2:d+j;e[1]=g[2]<g[1]&&e[0]+j<c?c:e[1];e[2]=e[1];e[3]=c;g[3]=g[2];break;case "left":e[1]=
e[0]+j<(e[0]+c)/2?(e[0]+c)/2:e[0]+j;g[1]=g[0];e[2]=e[1];g[2]=(g[0]+d)/2;e[3]=c-j>(e[0]+c)/2?(e[0]+c)/2:c-j;g[3]=g[2];e[4]=e[3];g[4]=d;break;case "right":e[1]=(e[0]<c?c:e[0])+j,g[1]=g[0],e[2]=e[1],g[2]=d}}e[e.length]=c;g[g.length]=d}b=[];b[0]=e;b[1]=g;return b}function sGetTaskCurveWay(b,a,c){if(null==b)return null;var d=b.imgObject;b=d.x+d.w/2;var f=d.y+d.h/2,h=Math.atan(Math.abs(c-f)/Math.abs(a-b)),d=Math.atan(d.h/d.w);return h<=d?a>=b?"right":"left":c>=f?"down":"up"}
function bDrawBeeline(b,a,c,d,f,h){var e=aGetLinePoint(a,c,d,f,5),j=e[0],g=e[1],e=aGetArrow(a,c,j,g),l=1;null!=h&&(l=h);goWorkFlow.eWFJG.setStroke(l);goWorkFlow.eWFJG.htm+='<span id="'+b+'" Type=\'BEELINE\' onclick="bSetObjectStatus(this.id,true);">';goWorkFlow.eWFJG.drawLine(a,c,d,f);goWorkFlow.eWFJG.drawLine(e[0],e[1],j,g);goWorkFlow.eWFJG.drawLine(e[2],e[3],j,g);goWorkFlow.eWFJG.fillPolygon([j,e[0],e[2]],[g,e[1],e[3]]);goWorkFlow.eWFJG.htm+="</span>";goWorkFlow.eWFJG.paint();return!0}
function bDrawCurve(b,a,c,d){var f=aGetLinePoint(a[a.length-2],c[c.length-2],a[a.length-1],c[c.length-1],5),h=f[0],e=f[1],f=aGetArrow(a[a.length-2],c[c.length-2],h,e),j=1;null!=d&&(j=d);goWorkFlow.eWFJG.setStroke(j);goWorkFlow.eWFJG.htm+='<span id="'+b+'" Type=\'CURVE\' onclick="bSetObjectStatus(this.id,true);">';goWorkFlow.eWFJG.drawPolyline(a,c);goWorkFlow.eWFJG.drawLine(f[0],f[1],h,e);goWorkFlow.eWFJG.drawLine(f[2],f[3],h,e);goWorkFlow.eWFJG.fillPolygon([h,f[0],f[2]],[e,f[1],f[3]]);goWorkFlow.eWFJG.htm+=
"</span>";goWorkFlow.eWFJG.paint();return!0}function bDrawBrokenBeeline(){"object"==typeof ID_BROKENBEELINE&&$("#ID_BROKENBEELINE").remove();var b=aTaskBeelinePoint(goWorkFlow.fromObject,goWorkFlow.cursorX,goWorkFlow.cursorY);bDrawBeeline("ID_BROKENBEELINE",b[0],b[1],goWorkFlow.cursorX,goWorkFlow.cursorY);return!0}
function bDrawBrokenCurve(){var b=null!=goWorkFlow.curOverObjName&&goWorkFlow.curOverObjName!=goWorkFlow.fromObject.name?oGetTaskObject(goWorkFlow.curOverObjName):null,a=goWorkFlow.fromObject.cursorWay,b=null!=b?b.cursorWay:null,c=aTaskCurvePoint(goWorkFlow.fromObject,a,null),b=aGetCurvePoint(c[0],c[1],goWorkFlow.cursorX,goWorkFlow.cursorY,a,b),a=b[0],b=b[1];"object"==typeof ID_BROKENCURVE&&$("#ID_BROKENCURVE").remove();bDrawCurve("ID_BROKENCURVE",a,b);return!0}
function bSetObjectStatus(b,a,c,d){var f=null;if(!(null==b&&null==c)){null!=c?f=c:(goWorkFlow.curObjectName=b,f=oGetLineObject(b));if(null!=f&&("BEELINE"==f.Type||"CURVE"==f.Type)){b=f.htmlObject;for(c=0;c<b.children.length;c++)b.children[c].style.backgroundColor=!1==a?"#000000":"#FF0000"}else{null==f&&(f=oGetTaskObject(b));if(null==f)return;"LABEL"==f.Type?(b=f.htmlObject,b.style.border=!1==a?null!=b.innerText&&""!=b.innerText?"0px solid":"#000000 1px solid":"#FF0000 1px solid"):(b=f.imgObject,b.is_image&&
(c=unescape(b.src),c=-1!=c.indexOf("~.gif")?c.substr(0,c.indexOf("~.gif")):-1!=c.indexOf("^.gif")?c.substr(0,c.indexOf("^.gif")):-1!=c.indexOf("_.gif")?c.substr(0,c.indexOf("_.gif")):c.substr(0,c.indexOf(".gif")),!0==a?b.swapImage(c+"_.gif"):-1==a?b.swapImage(c+"~.gif"):-2==a?b.swapImage(c+"^.gif"):b.swapImage(c+".gif")))}!0==a&&(goWorkFlow.selected=!0,void 0!=d&&null!=d&&(d.cancelBubble=!0))}}
function bShowTasks(b,a,c,d){if(!0==a)if(!0==c)for(var f=0;f<b.inLines.length;f++){if(b.inLines[f].fromTask.name!=d){for(var h=0;h<goWorkFlow.selectTasks.length&&goWorkFlow.selectTasks[h].name!=b.inLines[f].fromTask.name;h++);h<goWorkFlow.selectTasks.length||(goWorkFlow.selectTasks[goWorkFlow.selectTasks.length]=b.inLines[f].fromTask,bSetObjectStatus(null,-1,b.inLines[f].fromTask),bShowTasks(b.inLines[f].fromTask,a,c,d))}}else for(f=0;f<b.outLines.length;f++){if(b.outLines[f].toTask.name!=d){for(h=
0;h<goWorkFlow.selectTasks.length&&goWorkFlow.selectTasks[h].name!=b.outLines[f].toTask.name;h++);h<goWorkFlow.selectTasks.length||(goWorkFlow.selectTasks[goWorkFlow.selectTasks.length]=b.outLines[f].toTask,bSetObjectStatus(null,-1,b.outLines[f].toTask),bShowTasks(b.outLines[f].toTask,a,c,d))}}else if(null!=goWorkFlow.selectTasks&&0<goWorkFlow.selectTasks.length){for(f=0;f<goWorkFlow.selectTasks.length;f++)bSetObjectStatus(null,!1,goWorkFlow.selectTasks[f]);goWorkFlow.selectTasks=[]}return!0}
function oCreateTask(b,a,c){var d="img_"+b.toLowerCase();dd.elements[d].copy();var f={};f.imgObject=dd.elements[d].copies[dd.elements[d].copies.length-1];f.name=f.imgObject.name;f.Type=b;f.imgObject.show();a=a>f.imgObject.w/2?a-f.imgObject.w/2:0;c=c>f.imgObject.h/2?c-f.imgObject.h/2:0;a=a+f.imgObject.w>ID_WORKAROUND.offsetWidth?ID_WORKAROUND.offsetWidth-f.imgObject.w:a;c=c+f.imgObject.h>ID_WORKAROUND.offsetHeight?ID_WORKAROUND.offsetHeight-f.imgObject.h:c;f.imgObject.moveTo(a,c);f.imgObject.setCursor("images/cur_move.cur");
f.htmlObject=dd.getDiv(f.name+"div");"LABEL"==b?f.htmlObject.style.border="#000000 1px solid":"LINE"!=b&&(f.outLines=[],f.inLines=[],f.upCurves=[],f.downCurves=[],f.leftCurves=[],f.rightCurves=[],f.cursorWay=null);"LINE"!=b&&(goWorkFlow.tasks[goWorkFlow.tasks.length]=f);if("LABEL"==b)b="#"+$(f.htmlObject).attr("id"),$(b).contextMenu("ID_MENU_LABEL",{bindings:{cutLabel:function(){bDealObject("cut")},copyLabel:function(){bDealObject("copy")},deleteLabel:function(){bDealObject("delete")}},onKeyDown:function(a){try{contextMenu(a)}catch(b){}},
onShowMenu:function(a,b){return b}});else if("LINE"==b)b="#"+$(f.htmlObject).attr("id"),bindLineContextMenu(b,f);else{var h="#"+$(f.htmlObject).attr("id");$(h).contextMenu("ID_MENU_TASK",{bindings:{taskProperty:function(){setTaskProperty()},showBeforeTasks:function(){showTasks("before")},showAfterTasks:function(){showTasks("after")},cutTask:function(){bDealObject("cut")},copyTask:function(){bDealObject("copy")},deleteTask:function(){bDealObject("delete")}},onKeyDown:function(a){try{contextMenu(a)}catch(b){}},
onShowMenu:function(a,b){-1!=h.indexOf("img_begin")?$("#taskProperty, #showBeforeTasks",b).remove():-1!=h.indexOf("img_end")&&$("#taskProperty, #showAfterTasks",b).remove();return b}})}return f}
function oCreateXMLNode(b){var a=null,c=parent.sGetLang("FLOW_WF_"+b.Type+"_NAME"),d=sGetNewName(b);switch(b.Type){case "TASK":a=goWorkFlow.xmlDOM.createElement("task");a.setAttribute("name",d);a.setAttribute("id",sGetNewTaskID(b));a.setAttribute("type","1");c=goWorkFlow.flowXML.find("tasks");c.append($(a));break;case "SUBFLOW":a=goWorkFlow.xmlDOM.createElement("task");a.setAttribute("name",d);a.setAttribute("id",sGetNewTaskID(b));a.setAttribute("type","2");c=goWorkFlow.flowXML.find("tasks");c.append($(a));
break;case "BEELINE":case "CURVE":if("CONDITION"==b.toTask.Type)break;c=parent.sGetLang("FLOW_WF_SENDTOTASK")+b.toTask.xmlObject.attr("name");a=goWorkFlow.xmlDOM.createElement("direction");a.setAttribute("name",c);a.setAttribute("id",sGetNewDirectionID());a.setAttribute("type","CONDITION"==b.fromTask.Type?"2":"1");goWorkFlow.flowXML.find("directions").append($(a));break;case "LABEL":a=goWorkFlow.xmlDOM.createElement("label");c=goWorkFlow.xmlDOM.createElement("html");c.appendChild(goWorkFlow.xmlDOM.createTextNode(""));
a.appendChild(c);goWorkFlow.flowXML.find("labels").append($(a));break;case "CONDITION":a=goWorkFlow.xmlDOM.createElement("task");a.setAttribute("name",d);a.appendChild(goWorkFlow.xmlDOM.createTextNode(""));break;case "BEGIN":a=goWorkFlow.xmlDOM.createElement("task");a.setAttribute("name",c);break;case "END":a=goWorkFlow.xmlDOM.createElement("task"),a.setAttribute("name",c)}if(null==a)return b.xmlObject=a;b.xmlObject=$(a);return $(a)}
function bDeleteTask(b){for(var a=0;a<goWorkFlow.tasks.length;a++)if(!(null==goWorkFlow.tasks[a]||goWorkFlow.tasks[a].name!=b)){if("LABEL"!=goWorkFlow.tasks[a].Type){for(var c=goWorkFlow.tasks[a],d=0,f=c.outLines.length;d<f;d++)null!=c.outLines[c.outLines.length-1]&&bDeleteLine(c.outLines[c.outLines.length-1].name);d=0;for(f=c.inLines.length;d<f;d++)null!=c.inLines[c.inLines.length-1]&&bDeleteLine(c.inLines[c.inLines.length-1].name)}goWorkFlow.tasks[a].imgObject.hide();"object"==typeof goWorkFlow.tasks[a].htmlObject&&
(goWorkFlow.tasks[a].htmlObject.style.display="none");null!=goWorkFlow.tasks[a].xmlObject&&(null!=goWorkFlow.tasks[a].xmlObject.getAttribute("uuid")&&""!=goWorkFlow.tasks[a].xmlObject.getAttribute("uuid"))&&(c=goWorkFlow.flowXML.selectSingleNode("deletes"),"TASK"==goWorkFlow.tasks[a].Type||"SUBFLOW"==goWorkFlow.tasks[a].Type?oAddElement(c,"task",goWorkFlow.tasks[a].xmlObject.getAttribute("uuid")):"LABEL"==goWorkFlow.tasks[a].Type&&oAddElement(c,"label",goWorkFlow.tasks[a].xmlObject.getAttribute("uuid")));
null!=goWorkFlow.tasks[a].xmlObject&&goWorkFlow.tasks[a].xmlObject.remove();goWorkFlow.tasks[a]=null}return!0}
function oCreateBeeline(b,a,c,d,f){if(b.name==a.name)return void 0!=f&&null!=f&&(f.cancelBubble=!0),null;if(null!=d)"CURVE"==d.Type&&(d.Type="BEELINE",bDeleteWayElement(b,d.fromWay+"Curves",d.name),bDeleteWayElement(a,d.toWay+"Curves",d.name),d.fromWay=null,d.toWay=null);else{var h=goWorkFlow.lines.length;d={};d.name="ID_LINE_"+h;d.Type="BEELINE";d.htmlObject=null;d.fromTask=b;d.toTask=a;d.stroke=c;d.isShowName=goWorkFlow.isShowLineName;d.labelObject=oCreateTask("LINE",0,0);d.labelObject.parent=d;
d.labelObject.imgObject.setCursor("default");d.labelObject.imgObject.hide();goWorkFlow.lines[h]=d;b.outLines[b.outLines.length]=d;a.inLines[a.inLines.length]=d}d.x2=a.imgObject.x+a.imgObject.w/2;d.y2=a.imgObject.y+a.imgObject.h/2;b=aTaskBeelinePoint(b,d.x2,d.y2);d.x1=b[0];d.y1=b[1];b=aTaskBeelinePoint(a,d.x1,d.y1);d.x2=b[0];d.y2=b[1];bReDrawLine(d);a="#"+$(d.htmlObject).attr("id");bindLineContextMenu(a,d);void 0!=f&&null!=f&&(f.cancelBubble=!0);return d}
function bindLineContextMenu(b,a){$(b).contextMenu("ID_MENU_DIRECTION",{bindings:{directionProperty:function(){setDirectionProperty()},arrow:function(){bSetDirection("arrow")},curve:function(){bSetDirection("curve")},beeline:function(){bSetDirection("beeline")},showDLineName:function(){showLineName(!0,!0)},hideDLineName:function(){showLineName(!1,!0)},deleteDirection:function(){bDealObject("delete")}},onKeyDown:function(a){try{contextMenu(a)}catch(b){}},onShowMenu:function(b,d){"BEELINE"==a.Type?
$("#beeline",d).remove():"CURVE"==a.Type&&$("#curve",d).remove();return d}})}
function oCreateCurve(b,a,c,d,f){if(b.name==a.name)return void 0!=f&&null!=f&&(f.cancelBubble=!0),null;var h=!1;if(null!=d){var e=d;"BEELINE"==e.Type&&(e.Type="CURVE",e.fromWay=sGetTaskCurveWay(b,e.x1,e.y1),e.toWay=sGetTaskCurveWay(a,e.x2,e.y2),setPoObject(b,e.fromWay,e),setPoObject(a,e.toWay,e),h=!0)}else h=!0,d=goWorkFlow.lines.length,e={},e.fromWay=b.cursorWay,e.toWay=a.cursorWay,e.name="ID_LINE_"+d,e.Type="CURVE",e.htmlObject=null,e.fromTask=b,e.toTask=a,e.stroke=c,e.isShowName=goWorkFlow.isShowLineName,
e.labelObject=oCreateTask("LINE",0,0),e.labelObject.parent=e,e.labelObject.imgObject.setCursor("default"),e.labelObject.imgObject.hide(),goWorkFlow.lines[d]=e,b.outLines[b.outLines.length]=e,a.inLines[a.inLines.length]=e,setPoObject(b,b.cursorWay,e),setPoObject(a,a.cursorWay,e);e.x1=b.imgObject.x+b.imgObject.w/2;e.y1=b.imgObject.y+b.imgObject.h/2;e.x2=a.imgObject.x+a.imgObject.w/2;e.y2=a.imgObject.y+a.imgObject.h/2;c=aTaskCurvePoint(b,e.fromWay,e,h,e.x2,e.y2);e.x1=c[0];e.y1=c[1];b=c[2];c=aTaskCurvePoint(a,
e.toWay,e,h,e.x1,e.y1);e.x2=c[0];e.y2=c[1];a=c[2];e.maxIndex=b>a?b:a;bReDrawLine(e);void 0!=f&&null!=f&&(f.cancelBubble=!0);f="#"+$(e.htmlObject).attr("id");$(f).contextMenu("ID_MENU_DIRECTION",{bindings:{directionProperty:function(){setDirectionProperty()},arrow:function(){bSetDirection("arrow")},curve:function(){bSetDirection("curve")},beeline:function(){bSetDirection("beeline")},showDLineName:function(){showLineName(!0,!0)},hideDLineName:function(){showLineName(!1,!0)},deleteDirection:function(){bDealObject("delete")}},
onKeyDown:function(a){try{contextMenu(a)}catch(b){}},onShowMenu:function(a,b){"BEELINE"==e.Type?$("#beeline",b).remove():"CURVE"==e.Type&&$("#curve",b).remove();return b}});return e}function setPoObject(b,a,c){"up"===a?b.upCurves[b.upCurves.length]=c:"down"===a?b.downCurves[b.downCurves.length]=c:"left"===a?b.leftCurves[b.leftCurves.length]=c:"right"===a&&(b.rightCurves[b.rightCurves.length]=c)}
function bReDrawLine(b){if("BEELINE"==b.Type){null!=b.htmlObject&&"object"==typeof b.htmlObject&&(b.htmlObject.outerHTML="");bDrawBeeline(b.name,b.x1,b.y1,b.x2,b.y2,b.stroke);b.htmlObject=dd.getDiv(b.name);var a=(b.x1+b.x2)/2,c=(b.y1+b.y2)/2}else if("CURVE"==b.Type)if(null!=b.htmlObject&&"object"==typeof b.htmlObject&&(b.htmlObject.outerHTML=""),c=aGetCurvePoint(b.x1,b.y1,b.x2,b.y2,b.fromWay,b.toWay,b.maxIndex),bDrawCurve(b.name,c[0],c[1],b.stroke),b.htmlObject=dd.getDiv(b.name),6==c[0].length)a=
(c[0][2]+c[0][3])/2,c=(c[1][2]+c[1][3])/2;else{var a=Math.abs(c[0][1]==c[0][2]?c[1][2]-c[1][1]:c[0][2]-c[0][1]),d=Math.abs(c[0][3]==c[0][2]?c[1][2]-c[1][3]:c[0][2]-c[0][3]);a>d?(a=(c[0][2]+c[0][1])/2,c=(c[1][2]+c[1][1])/2):(a=(c[0][2]+c[0][3])/2,c=(c[1][2]+c[1][3])/2)}"load"!=goWorkFlow.curStatus&&b.labelObject.imgObject.moveTo(a-b.labelObject.imgObject.w/2,c-b.labelObject.imgObject.h);return!0}
function bDeleteLine(b){for(var a=0;a<goWorkFlow.lines.length;a++)if(!(null==goWorkFlow.lines[a]||goWorkFlow.lines[a].name!=b)){var c=goWorkFlow.lines[a].fromTask,d=goWorkFlow.lines[a].toTask;"CURVE"==goWorkFlow.lines[a].Type&&(bDeleteWayElement(c,goWorkFlow.lines[a].fromWay+"Curves",b),bDeleteWayElement(d,goWorkFlow.lines[a].toWay+"Curves",b));"object"==typeof goWorkFlow.lines[a].htmlObject&&(goWorkFlow.lines[a].htmlObject.outerHTML="");bDeleteWayElement(c,"outLines",b);bDeleteWayElement(d,"inLines",
b);goWorkFlow.lines[a].labelObject.imgObject.hide();"object"==typeof goWorkFlow.lines[a].labelObject.htmlObject&&(goWorkFlow.lines[a].labelObject.htmlObject.style.display="none");null!=goWorkFlow.lines[a].xmlObject&&(null!=goWorkFlow.lines[a].xmlObject.getAttribute("uuid")&&""!=goWorkFlow.lines[a].xmlObject.getAttribute("uuid"))&&(b=goWorkFlow.flowXML.selectSingleNode("deletes"),oAddElement(b,"direction",goWorkFlow.lines[a].xmlObject.getAttribute("uuid")));null!=goWorkFlow.lines[a].xmlObject&&goWorkFlow.lines[a].xmlObject.remove();
goWorkFlow.lines[a]=null;break}return!0}function bDeleteWayElement(b,a,c){var d,f;f=[];d=b[a];for(var h=0;h<d.length;h++)d[h].name!=c&&(f[f.length]=d[h]);b[a]=f;return!0}
function bShowLabelInput(b){b=oGetTaskObject(null!=b?b:goWorkFlow.curObjectName);if(null==b||"LABEL"!=b.Type)return!1;var a=dd.getDiv("ID_LABELVALUEDIV");a.style.display="";a.style.left=b.imgObject.x;a.style.top=b.imgObject.y-1;a.style.width=b.imgObject.w+19;a.style.height=b.imgObject.h+2;a.style.zIndex=1E4;b=b.xmlObject.selectSingleNode("html");document.all.ID_LABELVALUE.value=null!=b.text()?b.text():"";document.all.ID_LABELVALUE.focus();document.onselectstart=Function("return true;");return!0}
function bSetLabelHTML(b){b=oGetTaskObject(null!=b?b:goWorkFlow.curObjectName);var a=dd.getDiv("ID_LABELVALUEDIV");return""==a.style.display?(document.onselectstart=Function("return false;"),a.style.display="none",a=b.xmlObject.selectSingleNode("html"),0<a.length&&(a.get(0).childNodes[0].nodeValue=document.all.ID_LABELVALUE.value,bSetObjectText(b)),!0):!1}
function bSetObjectText(b){var a="BEGIN"==b.Type||"END"==b.Type?Font.BOLD:Font.PLAIN,c="LABEL"==b.Type?b.xmlObject.selectSingleNode("html").text():"LINE"==b.Type?b.parent.xmlObject.getAttribute("name"):b.xmlObject.getAttribute("name");null==c&&(c="");if("LINE"==b.Type&&null!=c&&""!=c){var d=b.imgObject.x+b.imgObject.w/2;b.imgObject.resizeTo(10+12*c.length,b.imgObject.h);b.imgObject.moveTo(d-b.imgObject.w/2,b.imgObject.y)}for(var c='<TABLE border=0 cellpadding=0 cellspacing=0><TR><TD style="vertical-align:middle;text-align:center;font-family:\u5b8b\u4f53,Verdana,Arial;font-size:12px;word-wrap:break-word;width:'+
(b.imgObject.w-10)+"px;height:"+(b.imgObject.h-10)+"px;"+a+'">'+c+"</TD></TR></TABLE>",d=b.htmlObject,f=0;f<d.children.length;f++)if("DIV"==d.children[f].tagName){a=$(d.children[f]);a.html(c);"LINE"==b.Type?null==a.text()||""==a.text()?b.imgObject.hide():!0==b.parent.isShowName?b.imgObject.show():b.imgObject.hide():"LABEL"==b.Type&&(d=$(b.htmlObject),null!=d.text()&&""!=d.text()?d.css("border","0px solid"):d.css("border","#000000 1px solid"),!0==goWorkFlow.isShowLabel?b.imgObject.show():b.imgObject.hide());
return}d=new jsGraphics(b.name+"div");d.setColor("#000000");d.setFont("\u5b8b\u4f53,Verdana,Arial","12px",a);d.drawString(c,5,5);d.paint();"LINE"==b.Type?(d=$(b.htmlObject),null==d.text()||""==d.text()?b.imgObject.hide():!0==b.parent.isShowName?b.imgObject.show():b.imgObject.hide()):"LABEL"==b.Type&&(d=$(b.htmlObject),null!=d.text()&&""!=d.text()?d.css("border","0px solid"):d.css("border","#000000 1px solid"),!0==goWorkFlow.isShowLabel?b.imgObject.show():b.imgObject.hide())}
function moveCanvas(b){for(var a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a]){var c=goWorkFlow.tasks[a];switch(b){case "up":c.imgObject.moveTo(c.imgObject.x,c.imgObject.y-40);break;case "down":c.imgObject.moveTo(c.imgObject.x,c.imgObject.y+40);break;case "left":c.imgObject.moveTo(c.imgObject.x-40,c.imgObject.y);break;case "right":c.imgObject.moveTo(c.imgObject.x+40,c.imgObject.y)}}for(a=0;a<goWorkFlow.lines.length;a++)null!=goWorkFlow.lines[a]&&("BEELINE"==goWorkFlow.lines[a].Type?
oCreateBeeline(goWorkFlow.lines[a].fromTask,goWorkFlow.lines[a].toTask,null,goWorkFlow.lines[a]):oCreateCurve(goWorkFlow.lines[a].fromTask,goWorkFlow.lines[a].toTask,null,goWorkFlow.lines[a]))}
function showLineName(b,a){var c=null;null!=goWorkFlow.curObjectName&&""!=goWorkFlow.curObjectName&&(c=oGetLineObject(goWorkFlow.curObjectName));if(null!=c&&!0==a)c.isShowName=b,!0==c.isShowName?c.labelObject.imgObject.show():c.labelObject.imgObject.hide();else{goWorkFlow.isShowLineName=b;for(c=0;c<goWorkFlow.lines.length;c++)null!=goWorkFlow.lines[c]&&(goWorkFlow.lines[c].isShowName=goWorkFlow.isShowLineName,null!=goWorkFlow.lines[c].xmlObject&&null!=goWorkFlow.lines[c].xmlObject.getAttribute("name")&&
""!=goWorkFlow.lines[c].xmlObject.getAttribute("name")?!0==goWorkFlow.lines[c].isShowName?goWorkFlow.lines[c].labelObject.imgObject.show():goWorkFlow.lines[c].labelObject.imgObject.hide():goWorkFlow.lines[c].labelObject.imgObject.hide())}}function showLabel(b){goWorkFlow.isShowLabel=b;for(b=0;b<goWorkFlow.tasks.length;b++)null==goWorkFlow.tasks[b]||"LABEL"!=goWorkFlow.tasks[b].Type||(!0==goWorkFlow.isShowLabel?goWorkFlow.tasks[b].imgObject.show():goWorkFlow.tasks[b].imgObject.hide())}
function saveWorkFlow(b){if(!0==checkWorkFlow()){var a=goWorkFlow.flowXML.getAttribute("version");if(null==a||""==a)a="1.0",goWorkFlow.flowXML.setAttribute("version","1.0");else if(!0==b){a=goWorkFlow.flowXML.getAttribute("lastVer");if(void 0==a||null==a)a="1.0";a=(a-0+0.111+"").substring(0,3);goWorkFlow.flowXML.setAttribute("version",a);goWorkFlow.flowXML.setAttribute("uuid","")}var c=goWorkFlow.flowXML.selectSingleNode("./property/categorySN"),c=goWorkFlow.dictionXML.selectSingleNode("/diction/categorys/category[code='"+
c.text()+"']"),c=c.selectSingleNode("name").text();parent.document.title=c+"/"+goWorkFlow.flowXML.getAttribute("name")+"/"+a;parentPromptDoing_(parent.sGetLang("FLOW_WF_FLOWSAVING"));for(a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a]&&null!=goWorkFlow.tasks[a].xmlObject)switch(c=goWorkFlow.tasks[a].xmlObject,goWorkFlow.tasks[a].Type){case "TASK":case "SUBFLOW":oSetElement(c,"X",goWorkFlow.tasks[a].imgObject.x+goWorkFlow.tasks[a].imgObject.w/2+"");oSetElement(c,"Y",goWorkFlow.tasks[a].imgObject.y+
goWorkFlow.tasks[a].imgObject.h/2+"");var d=oGetConditionObjectByFromTaskName(c.getAttribute("name"));null!=d?(oSetElement(c,"conditionName",d.xmlObject.getAttribute("name")),oSetElement(c,"conditionBody",d.xmlObject.text()),oSetElement(c,"conditionX",d.imgObject.x+d.imgObject.w/2+""),oSetElement(c,"conditionY",d.imgObject.y+d.imgObject.h/2+""),d=goWorkFlow.tasks[a].outLines[0],"BEELINE"==d.Type?oSetElement(c,"conditionLine","BEELINE"):oSetElement(c,"conditionLine","CURVE;"+d.fromWay+";"+d.toWay)):
(oSetElement(c,"conditionName",""),oSetElement(c,"conditionBody",""),oSetElement(c,"conditionX",""),oSetElement(c,"conditionY",""),oSetElement(c,"conditionLine",""));break;case "LABEL":oSetElement(c,"X",goWorkFlow.tasks[a].imgObject.x+goWorkFlow.tasks[a].imgObject.defw/2+""),oSetElement(c,"Y",goWorkFlow.tasks[a].imgObject.y+goWorkFlow.tasks[a].imgObject.defh/2+""),oSetElement(c,"W",goWorkFlow.tasks[a].imgObject.w+""),oSetElement(c,"H",goWorkFlow.tasks[a].imgObject.h+"")}for(a=0;a<goWorkFlow.lines.length;a++)if(null!=
goWorkFlow.lines[a]&&null!=goWorkFlow.lines[a].xmlObject){var d=null,f="",h="";"BEGIN"==goWorkFlow.lines[a].fromTask.Type?(d=goWorkFlow.lines[a].fromTask,f="<StartFlow>"):f="CONDITION"==goWorkFlow.lines[a].fromTask.Type?goWorkFlow.lines[a].fromTask.inLines[0].fromTask.xmlObject.getAttribute("id"):goWorkFlow.lines[a].fromTask.xmlObject.getAttribute("id");"END"==goWorkFlow.lines[a].toTask.Type?(d=goWorkFlow.lines[a].toTask,h="<EndFlow>"):h=goWorkFlow.lines[a].toTask.xmlObject.getAttribute("id");c=goWorkFlow.lines[a].xmlObject;
!0==b&&c.setAttribute("uuid","");c.setAttribute("fromID",f);c.setAttribute("toID",h);null!=d?(oSetElement(c,"terminalName",d.xmlObject.getAttribute("name")),oSetElement(c,"terminalType",d.Type),oSetElement(c,"terminalX",d.imgObject.x+d.imgObject.w/2+""),oSetElement(c,"terminalY",d.imgObject.y+d.imgObject.h/2+""),oSetElement(c,"terminalBody",d.xmlObject.text())):(oSetElement(c,"terminalName",""),oSetElement(c,"terminalType",""),oSetElement(c,"terminalX",""),oSetElement(c,"terminalY",""),oSetElement(c,
"terminalBody",""));d=goWorkFlow.lines[a];oSetElement(c,"lineLabel",d.labelObject.imgObject.x+";"+d.labelObject.imgObject.y);"BEELINE"==d.Type?oSetElement(c,"line","BEELINE"):oSetElement(c,"line","CURVE;"+d.fromWay+";"+d.toWay);oSetElement(c,"isShowName",!0==d.isShowName?"1":"0")}c=XMLtoString(goWorkFlow.flowXML.get(0));$.ajax({url:"scheme/save.action?pbNew="+(!0==b),type:"POST",data:c,contentType:"text/xml;charset=UTF-8",dataType:"xml",error:function(a){417===a.status?showMsg(a.responseText,!0):
showMsg(parent.sGetLang("FLOW_WF_SAVEFAILURE"),!0);parent.HideDoing_()},success:function(a){goWorkFlow.flowXML=$(a).selectSingleNode("flow");var b=goWorkFlow.flowXML.selectNodes("./tasks/task");null!=b&&b.each(function(){var a=$(this),b=oGetTaskObjectByPropertyID(a.getAttribute("id"));null!=b&&(b.xmlObject=a)});for(a=0;a<goWorkFlow.lines.length;a++)null!=goWorkFlow.lines[a]&&null!=goWorkFlow.lines[a].xmlObject&&(b=goWorkFlow.lines[a].xmlObject.getAttribute("id"),b=goWorkFlow.flowXML.selectSingleNode("./directions/direction[@id='"+
b+"']"),goWorkFlow.lines[a].xmlObject=b);b=goWorkFlow.flowXML.selectNodes("./labels/label");for(a=0;a<goWorkFlow.tasks.length;a++)if(!(null==goWorkFlow.tasks[a]||null==goWorkFlow.tasks[a].xmlObject)&&"LABEL"==goWorkFlow.tasks[a].Type&&null!=b&&0<b.length)for(var c=goWorkFlow.tasks[a].xmlObject.getAttribute("uuid"),d=goWorkFlow.tasks[a].xmlObject.selectSingleNode("html").text(),f=0;f<b.length;f++)if(null!=c&&""!=c&&c==$(b[f]).getAttribute("uuid")||$(b[f]).selectSingleNode("html").text()==d){goWorkFlow.tasks[a].xmlObject=
$(b[f]);break}showMsg(parent.sGetLang("FLOW_WF_SAVESUCCESS"));parent.HideDoing_()}})}}
function checkWorkFlow(){var b=goWorkFlow.flowXML,a=b.selectSingleNode("property");if(null==a)return showMsg(parent.sGetLang("FLOW_WF_FLOWPROPERTYISEMPTY"),!0),!1;if(null==b.getAttribute("name")||""==b.getAttribute("name"))return showMsg(parent.sGetLang("FLOW_WF_FLOWNAMEISEMPTY"),!0),!1;if(null==b.getAttribute("id")||""==b.getAttribute("id"))return showMsg(parent.sGetLang("FLOW_WF_FLOWALIASISEMPTY"),!0),!1;if(null==a.selectSingleNode("categorySN")||""==a.selectSingleNode("categorySN").text())return showMsg(parent.sGetLang("FLOW_WF_FLOWTYPEISEMPTY"),
!0),!1;var c=a.selectSingleNode("./property/equalFlow/name");if(null!=c&&""!=c.text()){b=!1;for(a=0;a<goWorkFlow.tasks.length;a++)if(!(null==goWorkFlow.tasks[a]||"LABEL"==goWorkFlow.tasks[a].Type)){b=!0;break}if(!0==b)return showMsg(parent.sGetLang("FLOW_WF_EQFLOWMOREOBJECT"),!0),!1;showMsg(parent.sGetLang("FLOW_WF_SETTINGTRUE"));return!0}for(var d=";",f=";",h=";",e=null,j=0,g="",a=0;a<goWorkFlow.tasks.length;a++)if(null!=goWorkFlow.tasks[a])switch(j=0,goWorkFlow.tasks[a].Type){case "BEGIN":if(null==
e)e=goWorkFlow.tasks[a];else return showMsg(parent.sGetLang("FLOW_WF_BEGINISMORE"),!0),!1;break;case "END":for(var l=0;l<goWorkFlow.tasks[a].outLines.length&&null==goWorkFlow.tasks[a].outLines[l];l++);if(l<goWorkFlow.tasks[a].outLines.length)goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_ENDOBJECTEXISTOUTLINE"));else{for(l=0;l<goWorkFlow.tasks[a].inLines.length&&!(null!=goWorkFlow.tasks[a].inLines[l]&&(j++,1<j));l++);if(l<goWorkFlow.tasks[a].inLines.length||
0==j)goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_ENDOBJECTMOREINLINE"));else if("SUBFLOW"==goWorkFlow.tasks[a].Type&&(null==goWorkFlow.tasks[a].xmlObject||null==goWorkFlow.tasks[a].xmlObject.getAttribute("name")||""==goWorkFlow.tasks[a].xmlObject.getAttribute("name")))goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_SUBFLOWPROPERTYISEMPTY"))}break;case "LABEL":if(null==
goWorkFlow.tasks[a].xmlObject||null==goWorkFlow.tasks[a].xmlObject.selectSingleNode("html")||""==goWorkFlow.tasks[a].xmlObject.selectSingleNode("html").text())goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_LABELHTMLISEMPTY"));break;case "TASK":var l=j=null,k=!1,m=!1,c=b.selectSingleNode("./property/isFree");null!=c&&"1"==c.text()&&(m=!0);null!=goWorkFlow.tasks[a].xmlObject&&(j=goWorkFlow.tasks[a].xmlObject.getAttribute("name"),l=goWorkFlow.tasks[a].xmlObject.getAttribute("id"),
c=goWorkFlow.tasks[a].xmlObject.selectSingleNode("isSetUser"),null!=c&&"1"==c.text()&&(c=goWorkFlow.tasks[a].xmlObject.selectSingleNode("./task/users/unit"),null==c&&(k=!0)));null==goWorkFlow.tasks[a].xmlObject||null==j||""==j||-1!=d.indexOf(";"+j+";")||null==l||""==l||-1!=h.indexOf(";"+l+";")||!0==k?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_TASKPROPERTYERROR"))):!1==m&&1>goWorkFlow.tasks[a].outLines.length?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=
goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_OBJECTOUTLINEISEMPTY"))):(c=oGetConditionObjectByFromTaskName(goWorkFlow.tasks[a].xmlObject.getAttribute("name")),null!=c&&1<goWorkFlow.tasks[a].outLines.length?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_TASKMOREOUTLINEFORCD"))):(d+=j+";",h+=l+";"));break;case "SUBFLOW":l=j=null;k=!1;null!=goWorkFlow.tasks[a].xmlObject&&(j=goWorkFlow.tasks[a].xmlObject.getAttribute("name"),
l=goWorkFlow.tasks[a].xmlObject.getAttribute("id"),c=goWorkFlow.tasks[a].xmlObject.selectSingleNode("isSetFlow"),null!=c&&"1"==c.text()&&(c=goWorkFlow.tasks[a].xmlObject.selectSingleNode("/task/newFlows/unit"),null==c&&(k=!0)));null==goWorkFlow.tasks[a].xmlObject||null==j||""==j||-1!=d.indexOf(";"+j+";")||null==l||""==l||-1!=h.indexOf(";"+l+";")||!0==k?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_SUBFLOWPROPERTYERROR"))):(c=oGetConditionObjectByFromTaskName(goWorkFlow.tasks[a].xmlObject.getAttribute("name")),
null!=c&&1<goWorkFlow.tasks[a].outLines.length?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_SUBFLOWMOREOUTLINEFORCD"))):(d+=j+";",h+=l+";"));break;case "CONDITION":j=null,m=!1,c=b.selectSingleNode("./property/isFree"),null!=c&&"1"==c.text()&&(m=!0),null!=goWorkFlow.tasks[a].xmlObject&&(j=goWorkFlow.tasks[a].xmlObject.getAttribute("name")),null==goWorkFlow.tasks[a].xmlObject||null==j||""==j||1!=goWorkFlow.tasks[a].inLines.length||
"TASK"!=goWorkFlow.tasks[a].inLines[0].fromTask.Type&&"SUBFLOW"!=goWorkFlow.tasks[a].inLines[0].fromTask.Type?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_CONDICTIONERROR"))):!1==m&&1>goWorkFlow.tasks[a].outLines.length&&(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.tasks[a],""==g&&(g=parent.sGetLang("FLOW_WF_OBJECTOUTLINEISEMPTY")))}for(a=0;a<goWorkFlow.lines.length;a++)null!=goWorkFlow.lines[a]&&("CONDITION"!=
goWorkFlow.lines[a].toTask.Type&&(null==goWorkFlow.lines[a].xmlObject||null==goWorkFlow.lines[a].xmlObject.getAttribute("name")||""==goWorkFlow.lines[a].xmlObject.getAttribute("name"))?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=goWorkFlow.lines[a],""==g&&(g=parent.sGetLang("FLOW_WF_LINEPROPERTYERROR"))):"BEGIN"==goWorkFlow.lines[a].fromTask.Type&&("END"==goWorkFlow.lines[a].toTask.Type||"SUBFLOW"==goWorkFlow.lines[a].toTask.Type||"CONDITION"==goWorkFlow.lines[a].toTask.Type)?(goWorkFlow.selectObjects[goWorkFlow.selectObjects.length]=
goWorkFlow.lines[a],""==g&&(g=parent.sGetLang("FLOW_WF_LINETOTASKERRORFORBEGIN"))):null!=goWorkFlow.lines[a].xmlObject&&null!=goWorkFlow.lines[a].xmlObject.getAttribute("name")&&(f+=goWorkFlow.lines[a].xmlObject.getAttribute("name")+";"));if(null==e)return showMsg(parent.sGetLang("FLOW_WF_NOBEGIN"),!0),!1;for(a=j=0;a<e.outLines.length;a++)if(null!=e.outLines[a]&&(j++,1<j))return showMsg(parent.sGetLang("FLOW_WF_BEGINOUTLINEISMORE"),!0),!1;if(0==j)return showMsg(parent.sGetLang("FLOW_WF_NOBEGINOUTLINE"),
!0),!1;for(a=0;a<e.inLines.length;a++)if(null!=e.inLines[a])return showMsg(parent.sGetLang("FLOW_WF_BEGINLINEERROR"),!0),!1;if(0<goWorkFlow.selectObjects.length)return bShowErrorObject(!0),""==g?showMsg(parent.sGetLang("FLOW_WF_SETTINGERROR"),!0):showMsg(g,!0),!1;showMsg(parent.sGetLang("FLOW_WF_SETTINGTRUE"));return!0}
function bShowErrorObject(b){for(var a=!0==b?-1:!1,c=0;c<goWorkFlow.selectObjects.length;c++)bSetObjectStatus(null,a,goWorkFlow.selectObjects[c]);!0!=b&&0<goWorkFlow.selectObjects.length&&(goWorkFlow.selectObjects=[]);return!0}
function bLoadObject(){goWorkFlow.curStatus="load";parent.bSetVersionInfo(goWorkFlow.flowXML.getAttribute("verType"),parent);var b=goWorkFlow.flowXML.selectSingleNode("./property/categorySN"),b=goWorkFlow.dictionXML.selectSingleNode("/diction/categorys/category[code='"+b.text()+"']"),b=b.selectSingleNode("name").text();parent.document.title+=" --- "+b+"/"+goWorkFlow.flowXML.getAttribute("name")+"/"+goWorkFlow.flowXML.getAttribute("version");var a=goWorkFlow.flowXML.selectNodes("./tasks/task");null!=
a&&a.each(function(){var a=$(this),b=oCreateTask("1"==a.getAttribute("type")?"TASK":"SUBFLOW",a.selectSingleNode("X").text()-0,a.selectSingleNode("Y").text()-0);bAdjustObject(b);b.xmlObject=a;bSetObjectText(b);var f=null!=a.selectSingleNode("conditionName")?a.selectSingleNode("conditionName").text():"",h=null!=a.selectSingleNode("conditionLine")?a.selectSingleNode("conditionLine").text():"";if(""!=f&&""!=h){var e=b,b=oCreateTask("CONDITION",a.selectSingleNode("conditionX").text()-0,a.selectSingleNode("conditionY").text()-
0);bAdjustObject(b);var j=oCreateXMLNode(b);j.setAttribute("name",f);j.text(null!=a.selectSingleNode("conditionBody")?a.selectSingleNode("conditionBody").text():"");bSetObjectText(b);a=b;null!=e&&null!=a&&(0==h.indexOf("BEELINE")?oCreateBeeline(e,a):(h=h.split(";"),e.cursorWay=h[1],a.cursorWay=h[2],oCreateCurve(e,a)))}});a=goWorkFlow.flowXML.selectNodes("./directions/direction");null!=a&&a.each(function(){var a=$(this),b=a.getAttribute("fromID");if("<StartFlow>"==b){var f=oCreateTask(a.selectSingleNode("terminalType").text(),
a.selectSingleNode("terminalX").text()-0,a.selectSingleNode("terminalY").text()-0);bAdjustObject(f);var h=oCreateXMLNode(f);h.setAttribute("name",a.selectSingleNode("terminalName").text());bSetObjectText(f);b=f}else"2"==a.getAttribute("type")?(loTask=oGetTaskObjectByPropertyID(b),b=oGetConditionObjectByFromTask(loTask)):b=oGetTaskObjectByPropertyID(b);f=a.getAttribute("toID");"<EndFlow>"==f?(f=oCreateTask(a.selectSingleNode("terminalType").text(),a.selectSingleNode("terminalX").text()-0,a.selectSingleNode("terminalY").text()-
0),bAdjustObject(f),h=oCreateXMLNode(f),h.setAttribute("name",a.selectSingleNode("terminalName").text()),bSetObjectText(f)):f=oGetTaskObjectByPropertyID(f);null!=b&&null!=f&&(h=a.selectSingleNode("line").text(),0==h.indexOf("BEELINE")?f=oCreateBeeline(b,f):(h=h.split(";"),b.cursorWay=h[1],f.cursorWay=h[2],f=oCreateCurve(b,f)),f.isShowName="0"==a.selectSingleNode("isShowName").text()?!1:!0,f.xmlObject=a,bSetObjectText(f.labelObject),h=a.selectSingleNode("lineLabel").text().split(";"),f.labelObject.imgObject.moveTo(h[0]-
0,h[1]-0))});a=goWorkFlow.flowXML.selectNodes("./labels/label");null!=a&&a.each(function(){var a=$(this),b=oCreateTask("LABEL",a.selectSingleNode("X").text()-0,a.selectSingleNode("Y").text()-0);b.imgObject.resizeTo(a.selectSingleNode("W").text()-0,a.selectSingleNode("H").text()-0);b.xmlObject=a;bSetObjectText(b)});showMsg(b+"/"+goWorkFlow.flowXML.getAttribute("name")+parent.sGetLang("FLOW_WF_LOADFINISH"));parent.HideDoing_();goWorkFlow.curStatus=null;return!0}
function bGetEQFlowXML(){var b=null;if(null!=goWorkFlow.equalFlowID&&""!=goWorkFlow.equalFlowID)b=goWorkFlow.equalFlowID;else{if(null==goWorkFlow.flowXML)return!1;var a=goWorkFlow.flowXML.selectSingleNode("./property/equalFlow/id");null!=a&&(b=a.text())}if(null==b||""==b)return!1;(null==goWorkFlow.equalFlowXML||b!=$(goWorkFlow.equalFlowXML).getAttribute("id"))&&$.ajax({url:"scheme/flow/xml/id?open&id="+b,type:"GET",dataType:"xml",cache:!1,async:!1,error:function(){},success:function(a){goWorkFlow.equalFlowXML=
$(a).selectSingleNode("flow")}});return null==goWorkFlow.equalFlowXML?!1:!0}
function aGetTasks(b,a,c){var d=[];b=null!=b&&""!=b?b:"TASK";a=null!=a?a:"";if(!0==bGetEQFlowXML()){var f=goWorkFlow.equalFlowXML.selectNodes("./tasks/task");if(null!=f)for(var h=0;h<f.length;h++){var e="1"==f[h].getAttribute("type")?"TASK":"SUBFLOW";-1!=b.indexOf(e)&&(null==f[h].getAttribute("name")||""==f[h].getAttribute("name")||null==f[h].getAttribute("id")||""==f[h].getAttribute("id")||a!=f[h].getAttribute("id")&&d.push(f[h].getAttribute("name")+"|"+f[h].getAttribute("id")))}}else for(h=0;h<
goWorkFlow.tasks.length;h++)null==goWorkFlow.tasks[h]||null==goWorkFlow.tasks[h].xmlObject||-1!=b.indexOf(goWorkFlow.tasks[h].Type)&&(null==goWorkFlow.tasks[h].xmlObject.getAttribute("name")||""==goWorkFlow.tasks[h].xmlObject.getAttribute("name")||null==goWorkFlow.tasks[h].xmlObject.getAttribute("id")||""==goWorkFlow.tasks[h].xmlObject.getAttribute("id")||a!=goWorkFlow.tasks[h].xmlObject.getAttribute("id")&&d.push(goWorkFlow.tasks[h].xmlObject.getAttribute("name")+"|"+goWorkFlow.tasks[h].xmlObject.getAttribute("id")));
null!=c&&!0==c&&d.push(parent.sGetLang("FLOW_WF_ENDTASKNAME")+"|<EndFlow>");return d}
function aGetDirections(){var b=[],a,c;if(!0==bGetEQFlowXML()){var d=goWorkFlow.equalFlowXML.selectNodes("./directions/direction");if(null!=d)for(var f=0;f<d.length;f++){c=a=null;if("<StartFlow>"==d[f].getAttribute("fromID"))a=parent.sGetLang("FLOW_WF_BEGINTASKNAME")+"|<StartFlow>";else{var h=goWorkFlow.equalFlowXML.selectSingleNode("./tasks/task[@id='"+d[f].getAttribute("fromID")+"']");null!=h&&(a=h.getAttribute("name")+"|"+h.getAttribute("id"))}"<EndFlow>"==d[f].getAttribute("toID")?c=parent.sGetLang("FLOW_WF_ENDTASKNAME")+
"|<EndFlow>":(h=goWorkFlow.equalFlowXML.selectSingleNode("./tasks/task[@id='"+d[f].getAttribute("toID")+"']"),null!=h&&(c=h.getAttribute("name")+"|"+h.getAttribute("id")));null!=a&&(""!=a&&null!=c&&""!=c)&&b.push(d[f].getAttribute("name")+"|"+d[f].getAttribute("id")+"|"+a+"|"+c)}}else for(f=0;f<goWorkFlow.lines.length;f++)if(c=a=null,!(null==goWorkFlow.lines[f]||null==goWorkFlow.lines[f].xmlObject||null==goWorkFlow.lines[f].xmlObject.getAttribute("name")||"CONDITION"==goWorkFlow.lines[f].toTask.Type)){if("BEGIN"==
goWorkFlow.lines[f].fromTask.Type)a=parent.sGetLang("FLOW_WF_BEGINTASKNAME")+"|<StartFlow>";else if("CONDITION"==goWorkFlow.lines[f].fromTask.Type){d=goWorkFlow.lines[f].fromTask.inLines[0];if(null==d)continue;null!=d.fromTask.xmlObject&&null!=d.fromTask.xmlObject.getAttribute("id")&&(a=d.fromTask.xmlObject.getAttribute("name")+"|"+d.fromTask.xmlObject.getAttribute("id"))}else null!=goWorkFlow.lines[f].fromTask.xmlObject&&null!=goWorkFlow.lines[f].fromTask.xmlObject.getAttribute("id")&&(a=goWorkFlow.lines[f].fromTask.xmlObject.getAttribute("name")+
"|"+goWorkFlow.lines[f].fromTask.xmlObject.getAttribute("id"));"END"==goWorkFlow.lines[f].toTask.Type?c=parent.sGetLang("FLOW_WF_ENDTASKNAME")+"|<EndFlow>":null!=goWorkFlow.lines[f].toTask.xmlObject&&null!=goWorkFlow.lines[f].toTask.xmlObject.getAttribute("id")&&(c=goWorkFlow.lines[f].toTask.xmlObject.getAttribute("name")+"|"+goWorkFlow.lines[f].toTask.xmlObject.getAttribute("id"));null!=a&&(""!=a&&null!=c&&""!=c)&&b.push(goWorkFlow.lines[f].xmlObject.getAttribute("name")+"|"+goWorkFlow.lines[f].xmlObject.getAttribute("id")+
"|"+a+"|"+c)}return b}function setFlowProperty(){parent.setFlowProperty(goWorkFlow,this)}function setTaskProperty(){var b=oGetTaskObject(goWorkFlow.curObjectName);if(null==b)return!1;"BEGIN"==b.Type||"END"==b.Type||parent.setTaskProperty(b,this,goWorkFlow)}function setDirectionProperty(){var b=oGetLineObject(goWorkFlow.curObjectName);if(null==b||null==b.xmlObject)return!1;parent.setDirectionProperty(b,window,goWorkFlow)}
function showTasks(b){var a=oGetTaskObject(goWorkFlow.curObjectName);null!=a&&bShowTasks(a,!0,"before"==b?!0:!1,goWorkFlow.curObjectName)}
function bSetDirection(b){var a=oGetLineObject(goWorkFlow.curObjectName);if(null!=a)switch(b){case "arrow":b=a.fromTask;var c=a.toTask;if("CURVE"==a.Type){bDeleteWayElement(b,a.fromWay+"Curves",a.name);bDeleteWayElement(c,a.toWay+"Curves",a.name);var d=a.fromWay;a.fromWay=a.toWay;a.toWay=d;setPoObject(c,a.fromWay,a);setPoObject(b,a.toWay,a)}bDeleteWayElement(b,"outLines",a.name);bDeleteWayElement(c,"inLines",a.name);a.fromTask=c;a.toTask=b;a.fromTask.outLines[a.fromTask.outLines.length]=a;a.toTask.inLines[a.toTask.inLines.length]=
a;"CURVE"==a.Type?oCreateCurve(a.fromTask,a.toTask,null,a):oCreateBeeline(a.fromTask,a.toTask,null,a);break;case "beeline":oCreateBeeline(a.fromTask,a.toTask,null,a);break;case "curve":oCreateCurve(a.fromTask,a.toTask,null,a)}}
function bDealObject(b){if("cut"==b||"copy"==b){var a=oGetTaskObject(goWorkFlow.curObjectName);goWorkFlow.copyObject={};goWorkFlow.copyObject.xmlObject=null!=a.xmlObject?a.xmlObject.cloneNode(!0):null;goWorkFlow.copyObject.x=a.imgObject.x+a.imgObject.w/2;goWorkFlow.copyObject.y=a.imgObject.y+a.imgObject.h/2;goWorkFlow.copyObject.Type=a.Type;"cut"==b&&bDeleteTask(a.name)}else"paste"==b?null!=goWorkFlow.copyObject&&(a=oCreateTask(goWorkFlow.copyObject.Type,goWorkFlow.copyObject.x+5,goWorkFlow.copyObject.y+
5),a.imgObject.maximizeZ(),null!=goWorkFlow.copyObject.xmlObject&&(a.xmlObject=goWorkFlow.copyObject.xmlObject.cloneNode(!0),"LABEL"!=a.Type&&a.xmlObject.setAttribute("name",sGetNewName(a)),"TASK"==a.Type||"SUBFLOW"==a.Type?(a.xmlObject.setAttribute("id",sGetNewTaskID(a)),b=goWorkFlow.flowXML.selectSingleNode("tasks"),b.appendChild(a.xmlObject)):"LABEL"==a.Type&&(b=goWorkFlow.flowXML.selectSingleNode("labels"),b.appendChild(a.xmlObject)),bSetObjectText(a))):"delete"==b&&(bDeleteTask(goWorkFlow.curObjectName),
bDeleteLine(goWorkFlow.curObjectName))}function oAddElement(b,a,c){null==goWorkFlow.xmlDOM&&(goWorkFlow.xmlDOM=oGetXMLDocument_());a=$(goWorkFlow.xmlDOM.createElement(a));null!=c&&a.appendChild($(goWorkFlow.xmlDOM.createTextNode(c)));b.appendChild(a);return a}
function oSetElement(b,a,c){null==goWorkFlow.xmlDOM&&(goWorkFlow.xmlDOM=oGetXMLDocument_());var d=b.selectSingleNode(a);if(null==d||0==d.length)d=$(goWorkFlow.xmlDOM.createElement(a)),b.appendChild(d);null!=c&&(0<d.get(0).childNodes.length?d.get(0).childNodes[0].nodeValue=c:d.append($(goWorkFlow.xmlDOM.createTextNode(c))));return d}
function bSetFormFieldValue(b,a,c){for(var d=";"+c+";",f=0;f<b.elements.length;f++)if(!(null==b.elements[f].name||b.elements[f].name!=a))switch(b.elements[f].type){case "radio":if(-1!=d.indexOf(";"+b.elements[f].value+";")&&(b.elements[f].checked=!0,b.elements[f].onclick))b.elements[f].onclick();break;case "checkbox":if(-1!=d.indexOf(";"+b.elements[f].value+";")){if(b.elements[f].checked=!0,b.elements[f].onclick)b.elements[f].onclick()}else b.elements[f].checked=!1;break;case "select-one":case "select-multiple":for(var h=
0;h<b.elements[f].options.length;h++)b.elements[f].options[h].selected=-1!=d.indexOf(";"+b.elements[f].options[h].value+";")||-1!=d.indexOf(";"+b.elements[f].options[h].text+";")?!0:!1;if(b.elements[f].onchange)b.elements[f].onchange();break;case "hidden":case "text":case "textarea":b.elements[f].value=c}return!0}
function sGetFormFieldValue(b,a){for(var c="",d=0;d<b.elements.length;d++)if(!(null==b.elements[d].name||b.elements[d].name!=a))switch(b.elements[d].type){case "radio":if(!0==b.elements[d].checked)return c=b.elements[d].value;break;case "checkbox":!0==b.elements[d].checked&&(c=""==c?b.elements[d].value:c+(";"+b.elements[d].value));break;case "select-one":case "select-multiple":for(var f=0;f<b.elements[d].options.length;f++)!0==b.elements[d].options[f].selected&&(c=null!=b.elements[d].options[f].value&&
""!=b.elements[d].options[f].value?""==c?b.elements[d].options[f].value:c+(";"+b.elements[d].options[f].value):""==c?b.elements[d].options[f].text:c+(";"+b.elements[d].options[f].text));return c;case "hidden":case "text":case "textarea":return c=b.elements[d].value}return c}
function bSetVersionInfo(b,a){if(!(null==b||""==b)){var c=a.document.getElementsByTagName("SPAN");if(null!=c)for(var d=0;d<c.length;d++)null!=c[d].Version&&(-1!=c[d].Version.indexOf(b)?("ID_PageContent"==c[d].id&&(c[d].id=""),c[d].style.display="none"):c[d].style.display="");c=a.document.getElementsByTagName("TR");if(null!=c)for(d=0;d<c.length;d++)null!=c[d].Version&&(c[d].style.display=-1!=c[d].Version.indexOf(b)?"none":"");c=a.document.getElementsByTagName("TD");if(null!=c)for(d=0;d<c.length;d++)null!=
c[d].Version&&(c[d].style.display=-1!=c[d].Version.indexOf(b)?"none":"");return!0}}function vOpenModal_(b,a,c,d,f){c=1>=c?screen.width*c:c;d=1>=d?screen.height*d:d;null==f&&(f="");return showModalDialog(b,a,f+" dialogWidth:"+c+"px;dialogHeight:"+d+"px;center:yes;status:no;help:no")}
function oGetXmlHttpRequest_(){if(window.XMLHttpRequest)return new XMLHttpRequest;if(window.ActiveXObject)try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(a){return null}}else return null}function XMLtoString(b){var a;try{serializer=new XMLSerializer,a=serializer.serializeToString(b)}catch(c){a=b.xml}return a}function oGetXMLDocument_(){return $.parseXML("<flow/>")};
