alter table ORG_USER add HOME_PHONE VARCHAR2(255 CHAR);
alter table ORG_USER add PERSONNEL_AREA VARCHAR2(255 CHAR);

alter table ORG_USER add MAJOR_JOB_NAME VARCHAR2(255 CHAR);
alter table ORG_USER add OTHER_JOB_NAMES VARCHAR2(255 CHAR);
alter table ORG_USER add PRINCIPAL_COMPANY VARCHAR2(255 CHAR);

alter table ORG_USER add EXTERNAL_ID  VARCHAR2(255 CHAR);

alter table ORG_DEPARTMENT add EXTERNAL_ID  VARCHAR2(255 CHAR);
alter table ORG_DEPARTMENT add DEPARTMENT_LEVEL VARCHAR2(255 CHAR);
alter table ORG_DEPARTMENT add FUNCTION_NAMES VARCHAR2(255 CHAR);


CREATE TABLE ORG_DEPARTMENT_FUNCTION
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
        "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"FUNCTION_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("DEPARTMENT_UUID", "FUNCTION_UUID")
);


--部门权限表 后面没用到了 考虑去掉
CREATE TABLE ORG_DEPARTMENT_PRIVILEGE
   (  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("DEPARTMENT_UUID", "PRIVILEGE_UUID")
);

--群组权限表 后面没用到了
CREATE TABLE ORG_GROUP_PRIVILEGE
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("GROUP_UUID", "PRIVILEGE_UUID")
);

--用户权限表 后面没用到了
CREATE TABLE ORG_USER_PRIVILEGE
   (  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("USER_UUID", "PRIVILEGE_UUID")
);