CREATE TABLE ORG_DUTY
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
        "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR),
  "DUTY_LEVEL" VARCHAR2(255 CHAR),
  "SERIES_NAME" VARCHAR2(255 CHAR),
  "SERIES_UUID" VARCHAR2(255 CHAR),
   "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "EXTERNAL_ID"  VARCHAR2(255 CHAR),
  "REMARK" VARCHAR2(255 CHAR),
  PRIMARY KEY ("UUID")
  
)

--职务角色关联表
CREATE TABLE ORG_DUTY_ROLE
   (  "DUTY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("DUTY_UUID", "ROLE_UUID")
);

--职务群组关联表
CREATE TABLE ORG_GROUP_DUTY
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "DUTY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   PRIMARY KEY ("GROUP_UUID", "DUTY_UUID")
);
