alter table AUDIT_ROLE add SOURCE_UUID VARCHAR2(255 CHAR);

alter table AUDIT_ROLE add CATEGORY_UUID VARCHAR2(255 CHAR);
alter table audit_privilege add CATEGORY_UUID VARCHAR2(255 CHAR);


alter table AUDIT_ROLE add CATEGORY_NAME VARCHAR2(255 CHAR);
alter table audit_privilege add CATEGORY_NAME VARCHAR2(255 CHAR);

ALTER TABLE  cd_data_dict add SOURCE_UUID VARCHAR2(255 CHAR);
ALTER TABLE  cd_data_dict add SOURCE_TYPE VARCHAR2(255 CHAR);