alter table IS_EXCHANGE_DATA_REPEST  add USER_ID  VARCHAR2(255 CHAR);
alter table IS_EXCHANGE_DATA_REPEST  add TENANT_ID  VARCHAR2(255 CHAR);

alter table DYTABLE_FORM_DEFINITION add  FORM_SIGN varchar2(255 CHAR);