-- Add/modify columns 
alter table DYTABLE_FORM_RELATION add GROUP_SHOW_TITLE VARCHAR2(255 CHAR);
alter table DYTABLE_FORM_RELATION add IS_GROUP_SHOW_TITLE VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_DEFINITION add SET_URL_ONLY_READ VARCHAR2(255 CHAR);