/*此表已弃用*/
DROP TABLE USERFORM_MATTERS_DEFINE;


-- 公文交换
DELETE FROM EXCHANGE_LOG;
DELETE FROM EXCHANGE_OPTION;
DELETE FROM EXCHANGE_SENDEE;
DELETE FROM EXCHANGE_SENDER;
DELETE FROM EXCHANGE_DOCUMENT;
DROP TABLE EXCHANGE_LOG;
DROP TABLE EXCHANGE_OPTION;
DROP TABLE EXCHANGE_SENDEE;
DROP TABLE EXCHANGE_SENDER;
DROP TABLE EXCHANGE_DOCUMENT;


-- 公共库相关
DROP TABLE MT_ADMIN;
DROP TABLE MT_DATABASE_CONFIG;
DROP TABLE MT_ID_GENERATOR;
DROP TABLE MT_TENANT;
DROP TABLE TEST_FILEUPLOAD;
DROP TABLE UNIT_BUSINESS_TREE;
DROP TABLE UNIT_BUSINESS_TYPE;
DROP TABLE UNIT_COMMON_UNIT_TREE;
DROP TABLE UNIT_DEPARTMENT_USER;
DROP TABLE UNIT_COMMON_USER;
DROP TABLE UNIT_COMMON_DEPARTMENT;
DROP TABLE UNIT_COMMON_UNIT;