-- Add/modify columns 
alter table XZSP_BANJIAN add OWNER_UNIT_CODE VARCHAR2(255 CHAR);
alter table XZSP_BANJIAN add BANJIAN_SERIAL_NUMBER VARCHAR2(255 CHAR);
alter table XZSP_BANJIAN add PROMISE_DEAL_LIMIT_TIME NUMBER(10);
alter table XZSP_BANJIAN add CHUWEN_FILE VARCHAR2(255 CHAR);
alter table XZSP_BANJIAN add APPROVAL_NUMBER VARCHAR2(255 CHAR);
alter table XZSP_BANJIAN add CHUWEN_TIME TIMESTAMP(6);
alter table XZSP_BANJIAN add PICKUP_TIME TIMESTAMP(6);