--流水号定义新增属性
alter table DYTABLE_FIELD_DEFINITION add IS_SAVE_DB VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_DEFINITION add UN_EDIT_DESIGNATED_ID VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_DEFINITION add UN_EDIT_IS_SAVE_DB VARCHAR2(255 CHAR);