-- Add/modify columns 
alter table DYTABLE_FORM_RELATION add SUBR_RELATION_DATA_DEFIANTION VARCHAR2(255 CHAR);
alter table DYTABLE_FORM_RELATION add SUBFORM_APPLY_TABLE_ID VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_DEFINITION add RELATION_DATA_SHOW_METHOD VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_RELATION add uuid2 VARCHAR2(255 CHAR);
alter table DYTABLE_FIELD_RELATION add SUB_COL_HIDDEN VARCHAR2(255 CHAR);