ALTER TABLE FM_FOLDER ADD FILE_CREATE_MSG_FORMAT_ID   VARCHAR2(255 CHAR);
ALTER TABLE FM_FOLDER ADD FILE_CREATE_MSG_FORMAT_NAME VARCHAR2(255 CHAR);
ALTER TABLE FM_FOLDER ADD FILE_EDITOR_MSG_FORMAT_ID   VARCHAR2(255 CHAR);
ALTER TABLE FM_FOLDER ADD FILE_EDITOR_MSG_FORMAT_NAME VARCHAR2(255 CHAR);
