alter table DYVIEW_VIEW_CUSTOM_BUTTON add RESAULT_NAME VARCHAR2(255 CHAR);
alter table DYVIEW_SELECT_DEFINITION add FOR_TIME_SOLT NUMBER(1);
alter table DYVIEW_SELECT_DEFINITION add SEARCH_FIELD VARCHAR2(255 CHAR);